### ISSUE TITLE
Stepper component

### ISSUE THREAD

**Issue by SuperDJ** [microsoft/fluentui#14299]
### Description

A stepper component. This could be used to indicate the progress a action. A action could be something like the following:

- Checkout a order;
- Fill out a form in multiple steps;
- Indicate the progress of a review or something. A stepper shouldn't be bound to a form.

### Which product teams/scenarios need this control

- Checkout a order;
- Fill out a form in multiple steps;
- Indicate the progress of a review or something. A stepper shouldn't be bound to a form.
- Could also indicate the progress of a checklist;

### Design assets

There could be a horizontal and vertical version:
- ![image](https://user-images.githubusercontent.com/6484766/89105050-3d410480-d41e-11ea-8d16-be170eed9e52.png)
- ![image](https://user-images.githubusercontent.com/6484766/89105069-5a75d300-d41e-11ea-8514-a3aabf38b49a.png)

- https://vuetifyjs.com/en/components/steppers/
- https://material-ui.com/components/steppers/
- https://material.io/archive/guidelines/components/steppers.html#steppers-specs

### Imports/Dependencies

- [Basic list](https://developer.microsoft.com/en-us/fluentui#/controls/web/list) as a vertical stepper
- [Pivot](https://developer.microsoft.com/en-us/fluentui#/controls/web/pivot) as a horizontal stepper

### Exports/Component breakdown

- stepper. A wrapper around each step;
- stepper-step. A step could be a separate component. It's a wrapper around the components below.
- stepper-step-head. Indicating the header of a step.
- stepper-step-content. The actual content of a step. 

### Intended package/s

Stepper

### Example code

```
<stepper alternative-labels>
    <stepper-step checked checked-icon="ReminderPerson" label="A">
        <stepper-step-head>User details</stepper-step-head>

       <stepper-step-content>
        <TextField label="First name" />
        <TextField label="Last name" />
        <TextField label="Password" />
        <TextField label="Email" />   

         <DefaultButton text="Next step" onClick={next} />
       </stepper-step-content>
   </stepper-step>

    <stepper-step label="2">
        <stepper-step-head>User address</stepper-step-head>

       <stepper-step-content>
        <TextField label="Street" />
        <TextField label="City" />
        <TextField label="Zipcode" />

         <DefaultButton text="Register" onClick={register}/>
       </stepper-step-content>
   </stepper-step>
</stepper
```

#### stepper
| Name | Type | Description           |
| ---- | ---- | --------------------- |
| root | div  | The outermost element |

#### stepper-step
| Name | Type | Description           |
| ---- | ---- | --------------------- |
| label | div  | The label of a step |

#### stepper-step-header
| Name | Type | Description           |
| ---- | ---- | --------------------- |
| root | div  | The title of a stepper |

#### stepper-step-content
| Name | Type | Description           |
| ---- | ---- | --------------------- |
| root | div  | The content of the stepper step |

#### stepper
| Name      | Type   | Default Value | Description                                 |
| --------- | ------ | ------------- | ------------------------------------------- |
| alternative-labels | boolean | false | Weter the labels should be on the right side or below the step indicator  |
| vertical | boolean | false | On false the stepper should be horizontal when true it should be vertical |
| color | string | primary | The color of the stepper | 
| active | string/ integer | 0 | The value of the step being active. If no value is provided it should be the key |

#### stepper-step
| Name      | Type   | Default Value | Description                                 |
| --------- | ------ | ------------- | ------------------------------------------- |
| checked | boolean | false | Indicated if the step is completed |
| checked-icon | string | CheckMark | Icon the be displayed when a step is checked |
| label | string/integer | 1 | The label of a step which is shown before a step is checked for example 1, 2, 3, 4 etc. |

### Todos

- [ ] Change the list component for use in a stepper;
- [ ] Change the pivot component for use in a stepper;
- [ ] Decide styling 
- [ ] If the existing components can't be changed to be used in a stepper the individual components need to be created
  - [ ] Create stepper wrapper component
  - [ ] Create a stepper-step wrapper component
  - [ ] Create a stepper-step-header component
  - [ ] Create a stepper-step-content component 

### Steps

- [ ] Themable
- [ ] Unit tests
- [ ] Visual tests
- [ ] Documentation and examples
- [ ] Keyboard Accessible
- [ ] High Constrast Support
- [ ] RTL Support
- [ ] Design Review
- [ ] API review
- [ ] Public Preview
- [ ] Ready for Publishing

**Comment by akhilmhdh** [comment]
Hey there, Can i work on this one.

**Comment by paulgildea** [comment]
@SuperDJ Thanks for the feedback and request! This is super detailed!

I’ll mark this as a feature request and add it to our backlog, but we’re likely not going to get to it for a while as we’re currently focused on larger coherence across our two react package in the near term. However this is a great feature request as this fit in the Step/Wizard domain and I don't have any timelines to share when we will get to this feature.

Thanks for the feedback!

**Comment by dimitropoulos** [comment]
hey :smile: I noticed that you're working on building a Stepper.  The [react-ui-roundup](https://github.com/dimitropoulos/react-ui-roundup) has a lot of other examples of Steppers that might be interesting or useful points of reference to you while you're developing it for fluent-ui.

https://react-ui-roundup.dimitrimitropoulos.com/#Stepper

> Tip: if you view from the website you can open click `OPEN ALL IN NEW TABS` and see them all at once.

**Comment by paulgildea** [comment]
@dimitropoulos Thanks for the callout. 

@SuperDJ we're in the initial stages of planning and bootstrapping a process for these types of components that are composites basic Fluent UI Components. Would you be interested in helping us trailblaze that process to enable more types of these components be build in more of a community focused way?

**Comment by skp7111994** [comment]
Is this component available at this point in time?

**Comment by AndrewCraswell** [comment]
This is a component I find myself needing on every project. Would love to see it live in Fluent! There is precedent already for this across Microsoft. Here are some examples:

**Teams UI LIbrary / @fluentui/react-teams**
[Wizard](https://dev-int.teams.microsoft.com/storybook/main/index.html?path=/story/ui-templates-wizard--kitchen-sink-in-base-surface)

**M365 Admin Controls**
[Wizard](https://admincontrolsdemoapps.blob.core.windows.net/release/admin-controls/45.0.2/index.html#/examples/wizard)
[SubwayNav](https://admincontrolsdemoapps.blob.core.windows.net/release/admin-controls/45.0.2/index.html#/examples/subwaynav)
 
I think that the M365 Admin Control Wizard is the likliest candidate to start with. And I would probably not migrate the whole thing, just take the Stepper functionality and shift it into Fluent.
