### ISSUE TITLE
FluentUI build system optimizations

### ISSUE THREAD

**Issue by kenotron** [microsoft/fluentui#14449]
#### Describe the feature that you would like added

I've been looking to optimize the build times in PR / CI with the integration of `lage` which provides caching, scoping, and pipelining. To completely get to an optimized build, we should have these bits of work done:

- [x] optimize the speed of component info generation (#14590)
- [x] make all the build steps run from a package, rather than assuming they're run globally through a root level gulpfile.js (#14472 #14547)
- [ ] speed up v7 ts only typecheck once
- [x] @fluentui/docs build & @fluentui/react-northstar test both generate component info - and they both take 4-5 minutes uncached, CI is suffering from that (#14590)

#### What component or utility would this be added to

/packages/fluentui/*

#### Have you discussed this feature with our team, and if so, who

Discussing this with @layershifter, @dzearing, @ecraig12345, @jurokapsiar, @miroslavstastny

**Comment by layershifter** [comment]
@kenotron it seems that all things from v0 side are done there. Is there something that we need to change?

**Comment by ecraig12345** [comment]
Closing this since most elements are done and any issues moving forward will be tracked elsewhere.
