### ISSUE TITLE
Validate v8 release

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#14644]
- [x] Schedule bug bash for team (focused on converted function components)
  - [x] Beforehand, document areas of particular emphasis for testing
  - [x] Add tests if possible for bugs found
- [x] Verify perf of converted function components has not regressed (including in more realistic scenarios)
- [ ] Directly work with partners to test areas of particular concern
  - [ ] Need to identify these partners and get the work on their radar
  - [ ] Watch for perf regressions
- [x] Add ref conformance test #15334
