### ISSUE TITLE
Re-export date-time components from react

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#14679]
(from @ecraig12345)

Part 2/4 in a series of changes that must happen in master *after* v7 development moves to a branch, but *before* beta publishing:
1. #15152 OUFR/react-next merge 
2. (this) #14679 ~~Move~~ Re-export date-time components
3. #13384 uifabric/fluentui package renames
4. #14689 set up beta releases

### Motivation
 
We'd like to re-export the `@uifabric/date-time` versions of Calendar and DatePicker by default from the suite (because they're strict mode compliant and otherwise better). ~~but we can't have the suite re-export components from date-time since they depend on other components which currently still live in the suite.~~ EDIT: Now that we have `react-internal`, this is easier!

### Proposed solution

We were able to break the dependency cycle by putting everything `date-time` depends on in `react-internal`, so now we can just have `react` re-export from `date-time`.
- [ ] Delete Calendar and DatePicker from `react-internal`
- [ ] In `react`, add dep on `date-time` and re-export Calendar and DatePicker from `date-time`
- [x] In `react-examples`:
  - [x] Copy over `react/{Calendar,DatePicker}/{docs,*.doc.tsx}` to `date-time` (the docs from the main package are more up to date)
  - [x] Update example list and import paths in .doc.tsx to reflect the date-time package
  - [x] In the `react-examples/src/date-time`, delete CalendarPage, DatePickerPage, and the old `demo` folder
  - [x] Delete old Calendar and DatePicker examples from `react-examples/src/react`
- [x] Update files in `fabric-website` and `fabric-website-resources` to reference the `date-time` package
- [ ] Ensure release notes reflect this change

<details>
<summary>Click to show OLD plan</summary>
- ~~Move existing Calendar and DatePicker to `/compat` in suite (there are enough API changes that I'm hesitant to delete them entirely)~~ (EDIT: there are not actually that many API changes, so we may skip this)
- Move date-time Calendar and DatePicker to suite and export by default
- Make date-time re-export suite Calendar and DatePicker
- Update release notes about this

This must be done in the final beta prep period since it involves code moves in packages besides react-next. (It's a very straightforward change which anyone could do.)
</details>

**Comment by ecraig12345** [comment]
Did a more complete comparison of the APIs between OUFR and date-time, and actually the only major changes are the following:
- Conversion of Calendar from SCSS (module-style not globals) to CSS-in-JS
- Removed the following from `ICalendarProps`:
  - `autoNavigateOnSelection?: boolean;`
  - `selectDateOnClick?: boolean;`
  - `shouldFocusOnMount?: boolean;`
  - `yearPickerHidden?: boolean;`

So it's probably okay to entirely delete the OUFR versions and have people migrate. (If that creates too many problems, we can always add back compat versions later.)

@lorejoh12 Do you know what the intended replacements are for the removed props listed above? Or were they added to OUFR after the date-time package was created and need to be ported over?
