### ISSUE TITLE
Final setup for release

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#14692]
(from @ecraig12345)

Once we're ready to release, these are the few final items which must be done. This may require a short code freeze.

- [x] Prepare master branch for release (may require short code freeze)
  - [x] Last check for 7.0 changes to cherry-pick
  - [x] Pause publishing
  - [x] Update version numbers/publishing config to remove prerelease - #17169
  - [x] ~~Sync version numbers of non-major-bumped packages to those in 7.0 branch~~ *(irrelevant with current plan)*
  - [x] ~~Update changelogs of sub-packages to include (under the proper non-beta versions) any changes that were published out of 7.0~~ *(not worth it, they should be in 8 as beta changes too)*
- [x] ~~In 7.0 branch, delete packages which didn't major bump and pull the latest versions from npm instead~~ *should be done*
- [x] Update beachball settings:
  - [x] Use `latest` npm tag (no `-t`) for master - #17169
  - [x] Use `lts-7` npm tag (`-t lts-7`) for 7.0 - #17191
  - [x] Change 6.0 to `lts-6` - b192fad856483024b9b66f39629e1e8595dc1965
  - [x] ~~Remove `sync:beachball` command from 7.0 (it won't work)~~ *??*
- [x] Publish!
- [x] Re-run everyone's builds

At time of release or slightly after:
- [x] Un-pin and close relevant issues with comments
- [x] Add a release notes link to the repo and package readmes - #17193
- [x] Add a release banner to the website
- [x] Switch aka.ms/fabricdemo to show 8 by default
- [x] Remove beta-specific contributing docs
- [x] Update https://aka.ms/themedesigner to point back to `master` pr-deploy site. *(it's also pointing to the wrong domain currently)*

Others:
- [x] Add a bot rule on PRs to 7
![image](https://user-images.githubusercontent.com/5864305/109243871-8d086400-7792-11eb-8df4-d28ee24f4d90.png)
![image](https://user-images.githubusercontent.com/5864305/109243901-9c87ad00-7792-11eb-8306-3d85b536334b.png)
