### ISSUE TITLE
PRs targeting the 7.0 branch that will need porting into master

### ISSUE THREAD

**Issue by khmakoto** [microsoft/fluentui#15285]
### Fluent UI:
- [x] #14606 - ~Make FocusTrapZone useful for focusing the first item in a virtual list~
  - Asked author to port to master branch once the PR merges.
- [x] #15321 - ~Fix propagation of items and groups props from DetailsList through GroupedList~
  - Ported in #15605
- [x] #15335 - ~Fix issue in GroupedList where paging new data into existing groups did not re-render~
  - Ported in #15628
- [x] #15339 - ~Fix lint rule for import paths~
  -  Cherry picking results in 0 changes. All of the impacted paths are either unchanged or have been replaced with `export * from @fluentui...`
- [x] #15395 - ~Azure-theme pivots + dropdowns for 7.0~
  - Ported in #15633
- [x] #15405 - ~Expose FileTypeIcons as HTML strings~
  - Asked author to port to master branch once the PR merges.
- [x] #15450 - ~SearchBox: role=search is removed, but can be optionally defined via role prop~
  - Ported in #15621
- [x] #15469 - ~fix for positioning logic land on fractional values~
  - Asked author to port to master branch once the PR merges.
- [x] #15471 - ~withSlots: refactor out redundant React.Children traversal~
  - Ported in #15462
- [x] #15478 - ~Add custom KeyUp support to Group Header~
  - Ported in #15624
- [x] #15511 - ~CommandBar: fix incorrect aria role~
  - Ported in #15614
- [x] #15649 - ~Update fluid note filetype icon~
  - Ported in #15687
- [x] #15673 - ~Use type from state iff canRevealPassword is true~
  - Asked author to port to master branch once the PR merges.

### Charting:

See history for ordering: https://github.com/microsoft/fluentui/commits/7.0/packages/charting

- [x] #14597 - ~Color Fill Bars Feature for Line Chart Component~
  - Ported in #15660
- [x] #15295 - ~Charting: Refactoring of Vertical bar chart~
  - Ported in #15639
- [x] #15296 - ~introducing the the heat map chart~
  - Ported in #15664
- [x] #15298 - ~Charting: Custom callout support for Horizontal bar chart, Stacked bar chart and Donut chart~
  - Ported in #15697
- [x] #15299 - ~Charting: Area chart - Graph update after data change issue resolved and memoize implemented~
  - Ported in #15647
- [x] #15361 - ~Custom callout for charts~
  - Ported in #15684
- [x] #15403 - ~minor edits to the area chart~
  - Ported in #15686
- [x] #15447 - ~Charting: Vertical stacked bar chart minor changes including uncaught type error issue fix~
  - Ported in #15699
- [x] #15468 - ~charting: Grouped vertical bar chart code refactor~
  - Asked author to port to master branch once the PR merges.
- [x] #15505 - ~introducing new feature in vertical bar chart. added line~
  - Ported in #15705
- [x] #15507 - ~Charting: Test cases for linechart~
  - Ported in #15700
- [x] #15520 - ~Charting: Area chart unit test cases~
  - Ported in #15702
- [x] #15522 - ~Charting: Vertical stacked bar chart unit test cases~
  - Ported in #15709
- [x] #15523 - ~Charting: Vertical bar chart unit test cases updated~
  - Ported in #15703
- [x] #15551 - ~adding lines in vertical stacked bar chart complex combo chart~
  - Asked author to port to master branch once the PR merges.
- [x] #15578 - ~Charting: Unit test cases to the Stacked bar chart and Multi stacked bar charts~
  - Ported in #15708
- [x] #15579 - ~Charting: Horizontal bar chart basic unit test cases~
  - Ported in #15706
- [x] #15606 - ~[VerticalStackedBarChart] bar gaps and rounded corners~
  - Ported in #15704
- [x] #15640 - ~Charting: Basic unit test cases for Heat map chart and Pie chart~
  - Ported in #15711

### Web Components:
- [x] #15313 - ~export design system interface~
  - Ported in #15637
- [x] #15382 - ~feat: close shadow roots of all web components~
  - Ported in #15637 
- [x] #15397 - ~add skeleton as a new web component~
  - Ported in #15637 
- [x] #15429 - ~fix: correct palette generation behavior in Card~
  - Ported in #15637 
- [x] #15435 - ~fix WC button font inheritance issues~
  - Ported in #15637 
- [x] #15502 - ~Operate Dialog in open mode to ensure accessible focus behavior~
  - Ported in #15637 
- [x] #15509 - ~fix: updates FluentCard to correctly resolve designSystem properties and set background-color / neutralPalette context~
  - Ported in #15637 
~~- [ ] #15536 - ensure elevated-corner-radius is applied to dialog~~ (CLOSED, Chris will re-target this to master)
- [x] #15611 - ~Fix web-components yarn test --production~
  - Ported in #15637
