### ISSUE TITLE
[FEATURE] New and actual WinUI ProgressBar (current ProgressIndicator is not consistent with WinUI)

### ISSUE THREAD

**Issue by SFM61319** [microsoft/fluentui#15745]
## Component details
A new, and better `ProgressBar` (replaces `ProgressIndicator`) consistent with [WinUI](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/progress-controls)

### Description

A better `ProgressBar` component/control consistent with the latest version of WinUI (and future versions).  
  
I have made this keeping consistency in mind.

### Which product teams/scenarios need this control

This control isn't restricted to a group of teams/scenarios. It's a progress bar, and hence can be used anywhere to show a running process.

### Design assets

1. WinUI's `ProgressBar` (both determinate and indeterminate)  
###### *WinUI's Indeterminate ProgressBar*
![WinUI's Indeterminate `ProgressBar`](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/images/progressbar-indeterminate.gif)
###### *WinUI's Determinate ProgressBar*
![WinUI's Determinate `ProgressBar`](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/images/progressbar-determinate.png)

2. My `ProgressBar` (both determinate and indeterminate)
###### *My Indeterminate ProgressBar*
![My Indeterminate `ProgressBar`](https://user-images.githubusercontent.com/45308169/97461198-88a67880-1963-11eb-8c53-8fb6adde3675.gif)
###### *Indeterminate (Dark mode)*
![Indeterminate (Dark mode)](https://user-images.githubusercontent.com/45308169/97462356-9d374080-1964-11eb-9b35-441a4ee10fdf.gif)

*(Sorry for the low quality GIF)*

###### *My Determinate ProgressBar*
![My Determinate `ProgressBar`](https://user-images.githubusercontent.com/45308169/97461512-d7541280-1963-11eb-9245-003a039c9530.png)
###### *Determinate (Dark mode)*
![Determinate (Dark mode)](https://user-images.githubusercontent.com/45308169/97462568-e091af00-1964-11eb-8409-01c7d6fca821.png)

### Component ownership

I am the only one who can help maintain this component.

### Imports/Dependencies

No dependencies. Written in pure CSS and JS (can and will be written in React in the future if accepted).

### Exports/Component breakdown

Only one component.

### Intended package/s

`ProgressIndicators`? (question is kinda unclear)

### Example code

```html
<!DOCTYPE html>
<html>
  <head>
    <!-- Pure HTML, CSS, JS -->
    <link rel="stylesheet" href="path/to/progress-bar.css" />
    <script src="path/to/progressBar.js"></script>
  </head>
  <body>
    <div class="progress-bar"></div>
    <div class="progress-bar indeterminate"></div>
  </body>
</html>
```

### Public methods

| Name  | Type       | Description               |
| ----- | ---------- | ------------------------- |
| buildProgressBars | () => void | Builds progress bars |

### Slots

| Name | Type | Description           |
| ---- | ---- | --------------------- |
| - | - | - |

### Tokens

| Name      | Type  | Default Value | Description                |
| --------- | ----- | ------------- | -------------------------- |
| - | - | - | - |

### Props

| Name      | Type   | Default Value | Description                                 |
| --------- | ------ | ------------- | ------------------------------------------- |
| `indeterminate` | string |      `progress-bar`         | Optional class name to be added to the progress-bar (decides if `progress-bar` is `indeterminate` or not |

## Component Progress
Code written in pure CSS and JS. React code yet to be written.

### Current state
Working (in pure CSS and JS)

### Todos

- [ ] Make sure everything is the same as/close to WinUI's progress bars.
- [ ] Write the CSS+JS working code in React

### Steps

- [x] Themable
- [ ] Unit tests
- [x] Visual tests
- [x] Documentation and examples
- [ ] Keyboard Accessible
- [ ] High Constrast Support
- [ ] RTL Support
- [ ] Design Review
- [ ] API review
- [ ] Public Preview
- [ ] Ready for Publishing

**Comment by SFM61319** [comment]
I didnt really know what to fill in the tables `Slots` and `Tokens`

**Comment by SFM61319** [comment]
But i have the code which *almost* implements `ProgressBar` (some values need to be adjusted to implement the perfect progress bar, which im pretty close to) right now which i can paste here or use a pasting service like pastebin

**Comment by SFM61319** [comment]
Bruh at least tell me the directory this fits in and the file name this has/should have along with the "important" stuff that must be written along with the code in the source so that i can create a PR myself, or at least just tell me if this isn't needed so that i can close this feature request issue and not waste my time writing the react version of my css+js code

**Comment by paulgildea** [comment]
@SFM61319 Thanks for filing the issue. You are correct in that there are some differences between the designs between WinUI and Fluent UI React.

Since this touches mostly on the design side, I'd recommend pausing your development for the time being until we reach out to our design team to see if the WinUI motion is the recommended approach here.

@JustSlone Let me know if you think otherwise.

I'm super grateful for the contribution, we just need to me mindful of folks that have already taken a dependency on the look feel of the progress indicator and as well as the designs defined the Figma UI Toolkit.

**Comment by SFM61319** [comment]
> @SFM61319 Thanks for filing the issue. You are correct in that there are some differences between the designs between WinUI and Fluent UI React.
> 
> Since this touches mostly on the design side, I'd recommend pausing your development for the time being until we reach out to our design team to see if the WinUI motion is the recommended approach here.
> 
> @JustSlone Let me know if you think otherwise.
> 
> I'm super grateful for the contribution, we just need to me mindful of folks that have already taken a dependency on the look feel of the progress indicator and as well as the designs defined the Figma UI Toolkit.
> 
> 

Ah, got it.  
  
Also, I'm really sorry my previous comment came out rude.  
  
I see people complaining about inconsistencies everywhere (especially on [r/Windows](https://reddit.com/r/windows) and [r/Windows10](https://reddit.com/r/windows10) and thought removing inconsistencies as early as possible is good for development so I didnt want to waste time.  
  
I'll hold my development for now and work on making the current code as efficient as possible and match(?) the other components in the file structure and tests.  
  
Thank you for responding :)

**Comment by SFM61319** [comment]
@paulgildea I've started working on WinUI's `ProgressRing` in pure CSS+JS (more like SVG `circle` + CSS + JS). Will open a feature request issue for that soon.  
  
Till then, I hope this request gets accepted so that I can work with someone on your team to implement `ProgressBar` but in React (and not just vanilla css+js, which I have initially written the code in)

**Comment by SFM61319** [comment]
> @SFM61319 Thanks for filing the issue. You are correct in that there are some differences between the designs between WinUI and Fluent UI React.
> 
> Since this touches mostly on the design side, I'd recommend pausing your development for the time being until we reach out to our design team to see if the WinUI motion is the recommended approach here.
> 
> @JustSlone Let me know if you think otherwise.
> 
> I'm super grateful for the contribution, we just need to be mindful of folks that have already taken a dependency on the look feel of the progress indicator and as well as the designs defined the Figma UI Toolkit.

hey @paulgildea can you give me an update on your team's decision? should I continue my development (in react, cause I have finished writing in vanilla js for the same) or not? It's been 3 weeks...  
  
I also wanted to let you know that I have begun writing most of the controls as they are not consistent with [WinUI](https://github.com/microsoft/microsoft-ui-xaml). I'll open feature-request issues for them respectively, if this gets accepted first.

**Comment by SFM61319** [comment]
I also have some new components in mind (new to this repo, not WinUI), which I've started working on. Should I open an issue for them now or after completely developing them in vanilla css+js?

**Comment by SFM61319** [comment]
Uhhh, @paulgildea? anyone?

**Comment by SFM61319** [comment]
> @paulgildea I've started working on WinUI's `ProgressRing` in pure CSS+JS (more like SVG `circle` + CSS + JS). Will open a feature request issue for that soon.  
>   
> Till then, I hope this request gets accepted so that I can work with someone on your team to implement `ProgressBar` but in React (and not just vanilla css+js, which I have initially written the code in)

I opened a feature-request issue for this: #16088

**Comment by SFM61319** [comment]
Hey @paulgildea, can you tell me where the actual source for `ProgressIndicator` is and what files to change so that I can go through to code to see what to change for the PR?  
  
I didn't get any response from the team so I thought I should start working on the PR (since my vanilla code works and it's been over a month since I opened this issue) and maybe ping you for the PR and close this issue.  
  
Also, should I rename it to [`ProgressBar`](https://github.com/microsoft/microsoft-ui-xaml/tree/master/dev/ProgressBar) for consistency or leave it as is?

**Comment by SFM61319** [comment]
@paulgildea / @JustSlone (didn't know who to ping), I think I have achieved visual precision  
  
![Screengrab](https://user-images.githubusercontent.com/45308169/101369120-f08aa000-38cd-11eb-9785-ff3e584df0a4.gif)  
  
*(The top one is written in CSS+JS, the bottom one is the WinUI one - on [XAML Controls Gallery](https://github.com/microsoft/Xaml-Controls-Gallery))*
