### ISSUE TITLE
Divider Convergence

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#15759]
# Preparation:

- [x] Started prep
- [x] Open UI Research complete
- [x] Comparison on v7 and v0 complete
  - In [Spec.md](https://github.com/microsoft/fluentui/blob/master/packages/react-divider/Spec.md)
- [x] Gather open GitHub issues related to component in epic issue
  - No issues found
- [x] react-* package scaffolded
  - https://github.com/microsoft/fluentui/tree/master/packages/react-divider
- [x] Component Spec authored and reviewed
  - In [Spec.md](https://github.com/microsoft/fluentui/blob/master/packages/react-divider/Spec.md)
- [x] **Deliverable:** Reviewed component spec 

# Implementation

[link to react-* package folder]

- [x] Started impl
- [x] Implement component
- [x] Add storybook stories
- [x] using hooks
- [x] using makeStyles
- [x] respects Figma tokens (and using provider)
- [x] respects API principles, shorthands and slots handling
- [x] no dependency on v0/v7
- [x] Add tests - Conformance, Unit, and VR
  - [x] Conformance tests
  - [x] Unit tests
  - [x] VR tests
  - [ ] accessibility behavior tests 
- [x] Write README.md covering basic usage
- [x] Write initial MIGRATION.md guide (include v8 and v0)
- [x] **Deliverable:** Experimental component ready for partner use

# Validation

- [ ] Started validating
- [ ] Add and validate in UI Builder
- [ ] Add and validate in docs site
- [ ] Validate with token pipeline
- [ ] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods 
- [ ] **Deliverable:** Preview component ready for broader/3rd party use

**Comment by JustSlone** [comment]
Jan Update:
- Spec in draft state, more work to be done
- Starting to prototype implementation

**Comment by JustSlone** [comment]
Update:
- Converting over to make-styles
- Spec review on schedule for tomorrow

**Comment by joschemd** [comment]
Target for end of Feb,
Deliver spec.md 
Initial implement component / w makeStyles and storybook stories, documentation readme and migration guides

**Comment by khmakoto** [comment]
The component is stable now. Closing in favor of smaller issues if they arise in the future.
