### ISSUE TITLE
Separator Convergence Implementation

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#16085]
Work for initial Separator implementation

- [ ] Package scaffolded with /next folder
  - [link to package]
- [ ] Implement component
- [ ] Add storybook stories
  - [link to stories]
- [ ] Add tests - Conformance, Unit, and VR
  - [link to tests]
- [ ] Write README.md covering basic usage
- [ ] Write initial MIGRATION.md guide (include v7 and v0)
- [ ] **Deliverable:** Experimental component ready for partner use
