### ISSUE TITLE
Memory consumption measurement

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#16098]
## Goal 
Create baseline memory consumption measurements for `react-northstar` components. 

## Tasks
- [x] Manual measure some test scenarios to identify what useful metrics are
- [ ] Implement automation for capturing following memory metrics for a given test scenario
- WSS 
- Private memory 
- Used JS heap 
- Total JS heap 
- Total number of DOM elements rendered 
- [ ] Add perf test for each of the following high-usage components:
`Flex`, `Box`, `Avatar`, `Chat.Item`, `Popup`, `Status`, `Button`, `Grid`,` Toolbar`, `SvgIcon`

**Comment by JustSlone** [comment]
silly bot

**Comment by JustSlone** [comment]
Jan Update:
- On hold during January

**Comment by xugao** [comment]
Update: moving this to freezer since this is deprioritized. still writeup details for remaining work

**Comment by ecraig12345** [comment]
Moved doc to [shared location](https://microsoft.sharepoint-df.com/:w:/r/teams/FluentUIInternal/_layouts/15/doc2.aspx?sourcedoc=%7B9ea0b5d3-063b-40c5-bc94-779e8c03b128%7D)
