### ISSUE TITLE
WinUI Acrylic material for Fluent UI React

### ISSUE THREAD

**Issue by SFM61319** [microsoft/fluentui#16128]
### Description
  
An [`Acrylic`](https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic) component for Fluent UI React. Elements using this component will follow all rules and conditions laid for WinUI's Acrylic material.   
  
### Which product teams/scenarios need this control
  
All scenarios.  
This component (along with [`Reveal`](https://docs.microsoft.com/en-us/windows/uwp/design/style/reveal), which I have been working on and will open another issue for in the near future) will bring __Fluent UI React__ a lot closer to WinUI. Chromium Edge will have Legacy Edge's `Acrylic` title bar and Fluent context menus. The lost Fluent UI can be brought back to Edge.  
  
###### *Body without any elements*
![Empty `body`](https://user-images.githubusercontent.com/45308169/101022195-0d099e00-3597-11eb-80fb-728a3b38d0c1.png)  
  
###### *Body with a `div` having an `Acrylic` background and dummy text*
![Body with acrylic `div`](https://user-images.githubusercontent.com/45308169/101023922-6d99da80-3599-11eb-87b7-c162f66db70a.png)
  
### Component ownership
  
I'm the sole author of this component.  
  
### Imports/Dependencies

None.

### Exports/Component breakdown

Single element (`<AcrylicBrush />`)

### Intended package/s

`./Material/Acrylic`(?)

### Example code
  
*NOTE: Haven't decided on the structure yet. Need help deciding on the following two:*  
  
```jsx
<div>
  <AcrylicBrush TintColor={someColor} TintOpacity={someOpacity} />
  /* Similar to XAML */

  // Content
</div>
```
  
*OR*  
  
```jsx
<AcrylicBrush TintColor={someColor} TintOpacity={someOpacity}>
  <div>
    // Content
  </div>
</AcrylicBrush>
```

### Public methods

| Name  | Type       | Description               |
| ----- | ---------- | ------------------------- |
| - | - | - |

### Slots

| Name | Type | Description           |
| ---- | ---- | --------------------- |
| * | *  | - |

### Tokens

| Name      | Type  | Default Value | Description                |
| --------- | ----- | ------------- | -------------------------- |
| `TintColor` | color | theme.white   | Background color for the control |
| `TintOpacity` | number | 0.8 | Background color opacity for the control |
| `TintLuminosityOpacity` | number | *Calculated based on `TintColor` and `TintOpacity`* | Background saturation level/opacity for the control |
| `FallbackColor` | color | *Changes with `TintColor`* | Fallback color for the control (when window is inactive/blur) |

### Props

| Name      | Type   | Default Value | Description                                 |
| --------- | ------ | ------------- | ------------------------------------------- |
| - | - | - | - |

### Current state
  
Mostly working. Almost done.  
  
### Todos

- [ ] Calculate and apply __correct__ `backgroundColor`, `saturate` and `brightness` values based on `TintColor`, `TintOpacity`, and `TintLuminosityOpacity`
- [ ] Write change event functions.

### Steps

- [x] Themable
- [ ] Unit tests
- [x] Visual tests
- [ ] Documentation and examples
- [ ] Keyboard Accessible
- [x] High Constrast Support
- [x] RTL Support
- [ ] Design Review
- [ ] API review
- [ ] Public Preview
- [ ] Ready for Publishing

**Comment by JustSlone** [comment]
@SFM61319 thanks for the proposal, Acrylic isn't in our plans right now, but there is a long term goal of alignment between the various Fluent UI platforms. I'll talk to folks and see what we want to do here. Unfortunately with holidays it probably won't be until January next year.

Also, I'd recommend checking out our new model for constructing components. you can see it done with button here: https://github.com/microsoft/fluentui/tree/master/packages/react-button/src/components/Button

It's still in preview, but should be fairly stable soon, in particular useButtonClasses will likely change a bit in the near future.

**Comment by SFM61319** [comment]
Ohkay got it. I will propose `Reveal` after this gets accepted then. Proposing this for UI consistency across all platforms :)
