### ISSUE TITLE
Finish up Version 8 release tasks

### ISSUE THREAD

**Issue by JustSlone** [microsoft/fluentui#16357]
Main priorities:
- [x] Fix fabricdemo
- [x] Finish initial release mop-up items in #14692
- [x] Add version 8 to website - #14691 and #15308
- [ ] Ensure API docs on docs.microsoft.com at least aren't entirely broken (or remove and redirect to website) - #14783
- [ ] Remaining issues on [Version 8 board](https://github.com/microsoft/fluentui/projects/36) as appropriate

**Comment by JustSlone** [comment]
Update:
- Announcements shared through channels
- Looking into React 17, will hold off until after release

Main focus this week:
- Version 8 on the website
- Review outstanding workitems

**Comment by JustSlone** [comment]
Update:
- Working on version 8 on website
- Initial release mop up

**Comment by layershifter** [comment]
@JustSlone is it still a thing? ⌚
