### ISSUE TITLE
Avatar convergence

### ISSUE THREAD

**Issue by behowell** [microsoft/fluentui#16373]
# Preparation:

- [x] Started prep
- [x] Open UI Research complete
  - https://open-ui.org/components/avatar.research
- [x] Comparison on v8 and v0 complete
  - In [SPEC.md](https://github.com/microsoft/fluentui/blob/master/packages/react-avatar/SPEC.md)
- [x] Gather open GitHub issues related to component in epic issue
  - Avatar: Open issues to resolve in converged #16518
- [x] react-\* package scaffolded
  - https://github.com/microsoft/fluentui/tree/master/packages/react-avatar
- [x] Component Spec authored and reviewed
  - [SPEC.md](https://github.com/microsoft/fluentui/blob/master/packages/react-avatar/SPEC.md)
- [x] **Deliverable:** Reviewed component spec

# Implementation

- [x] Started impl
- [x] Implement component
- [x] Add storybook stories
- [x] using hooks
- [x] using makeStyles
- [x] respects Figma tokens (and using provider)
- [x] respects API principles, shorthands and slots handling
- [x] no dependency on v0/v7
- [x] Add tests - Conformance, Unit, and VR
  - [x] Conformance
  - [x] Unit
  - [x] VR/Screener (PR: #16525)
  - [x] accessibility behavior tests 
- [x] Write README.md covering basic usage
- [x] Write initial MIGRATION.md guide (include v8 and v0)
- [x] Fix outstanding implementation issues
  - [x] #18566
- [x] **Deliverable:** Experimental component ready for partner use

# Validation

- [ ] Started validating
- [ ] Add and validate in UI Builder
- [x] Add and validate in docs site
- [ ] Validate with token pipeline
- [ ] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods
- [ ] **Deliverable:** Preview component ready for broader/3rd party use

**Comment by JustSlone** [comment]
Blocked on updating scss styles to makeStyles
- FYI @layershifter (let @behowell know when makeStyles is ready for Avatar)

**Comment by behowell** [comment]
Goals for February:
* Convert styling from scss to makeStyles once it's available.
* Add support for colorful avatars. https://github.com/microsoft/fluentui/issues/16628
* Fix accessibility. https://github.com/microsoft/fluentui/issues/16670

**Comment by JustSlone** [comment]
Update:
- mainly waiting on makeStyles change

**Comment by behowell** [comment]
Update:
* makeStyles styling refresh is merged
* Support for colorful avatars PR is out: https://github.com/microsoft/fluentui/pull/17131

**Comment by behowell** [comment]
Update 3-2-2021:
* Colorful avatars are merged

March goals
* Connect to converged `PresenceBadge` and `Icon` once those components are ready
* Add accessibility behavior tests

**Comment by behowell** [comment]
Update 3-9-2021:
* No change since last week

**Comment by behowell** [comment]
Update 3-16-2021:
* No change since last week

**Comment by behowell** [comment]
June goals:
* Replace old MDL2 icons with new Fluent icons
* Accessibility behavior tests
* Clean up spec to match current API

**Comment by behowell** [comment]
8-9 update @behowell 
* PR merged to use new Fluent icons 🎉: #18566

**Comment by behowell** [comment]
8-16 update @behowell 
* Refactoring to remove `mergeProps`, PR forthcoming
* Updating spec to match latest API changes
