### ISSUE TITLE
create official CRA template for fluentui/react

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#16427]
Our getting started guide uses [CRA repo](https://github.com/microsoft/create-react-app-uifabric) which needs to be cloned, which is not an ideal approach anymore as CRA support custom templates since v3.4.

Goal is to create custom CRA template within our monorepo and update docs accordingly

```diff
-git clone https://github.com/microsoft/create-react-app-uifabric.git my-app
+npx create-react-app --template @fluentui/cra my-app
cd my-app
yarn
``` 

### Tasks
- [x] Fix our CRA repo so it works with fluent v7 https://github.com/microsoft/create-react-app-uifabric/pull/24
- [x] Migrate CRA repo to latest CRA v4  https://github.com/microsoft/create-react-app-uifabric/pull/26
- [x] Create new package within fluentui monorepo - CRA template
  - [x] Setup CI
  - [x] Add e2e coverage (booting up new CRA with our template) 
- [x] Setup releases to npm registry (semver bump, npm publish etc)
- [x] Update website getting started docs how to kickoff CRA with fluent ui template https://github.com/microsoft/fluentui/pull/16629
- [x] Archive [current CRA repo](https://github.com/microsoft/create-react-app-uifabric)
