### ISSUE TITLE
FluentUI Ecosystem

### ISSUE THREAD

**Issue by jdhuntington** [microsoft/fluentui#16445]
# Goal

Establish shared vision across disciplines and iterate plan to build out FluentUI ecosystem, which aims to encourage 1st and 3rd party component contributions.

# Tasks

- [x] Sync with design team building new Fluent brand experience _(Status: in progress, next sync planned)_
- [x] Prototype automatic integration of documentation/demo generation _(Status: in progress)_
- [ ] Iterate on shared storybook w/ CHP experience and extensive addon API

**Comment by JustSlone** [comment]
Jan Update:
- Split into two pieces
   - Waiting on design document website
   - Iterating on shared storybook inner dev loop
