### ISSUE TITLE
Link Convergence

### ISSUE THREAD

**Issue by paulgildea** [microsoft/fluentui#16572]
# Preparation:

- [x] Started prep
- [x] Open UI Research complete
  - https://open-ui.org/components/link.research
  - Pending PR: WICG/open-ui#253
- [x] Comparison on v8 and v0 complete
  - In [SPEC.md](https://github.com/microsoft/fluentui/blob/master/packages/react-link/SPEC.md)
- [x] Gather open GitHub issues related to component in epic issue
  - In #16622
- [x] react-* package scaffolded
  - https://github.com/microsoft/fluentui/tree/master/packages/react-link
- [x] Component Spec authored and reviewed
  - In [SPEC.md](https://github.com/microsoft/fluentui/blob/master/packages/react-link/SPEC.md)
- [x] **Deliverable:** Reviewed component spec 

# Implementation
https://github.com/microsoft/fluentui/tree/master/packages/react-link
- [x] Started impl
- [x] Implement component
- [x] Add storybook stories
- [x] Using hooks
- [x] Using makeStyles
- [x] Respects Figma tokens (and using provider)
- [x] Respects API principles, shorthands and slots handling
- [x] No dependency on v0/v7
- [x] Add tests - Conformance, Unit, and VR
  - [x] Conformance tests
  - [x] Unit tests
  - [x] VR tests
  - [x] Accessibility behavior tests 
- [x] Write README.md covering basic usage
  -  In [README.md](https://github.com/microsoft/fluentui/blob/master/packages/react-link/README.md)
- [x] Write initial MIGRATION.md guide (include v8 and v0)
  -  In [MIGRATION.md](https://github.com/microsoft/fluentui/blob/master/packages/react-link/MIGRATION.md)
- [x] Manual a11y review
  - In #19922 
- [x] **Deliverable:** Experimental component ready for partner use

# Validation
- [ ] Started validating
- [ ] Add and validate in UI Builder
- [ ] Add and validate in docs site
- [ ] Validate with token pipeline
- [ ] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods 
- [ ] **Deliverable:** Preview component ready for broader/3rd party use

**Comment by khmakoto** [comment]
__February Milestone Goals:__

Finish up `Preparation` and `Implementation` sections above.

**Comment by khmakoto** [comment]
We'll pick up the `validation` section in the `April` milestone.

**Comment by khmakoto** [comment]
This is no longer part of the `April` milestone.

**Comment by khmakoto** [comment]
The component is stable now. Closing in favor of smaller issues if they arise in the future.
