### ISSUE TITLE
Image Convergence

### ISSUE THREAD

**Issue by kubkon** [microsoft/fluentui#16658]
# Preparation:
- [x] Started prep
- [x] Open UI Research _complete_
  - [WICG/open-ui#274](https://github.com/WICG/open-ui/pull/274)
- [x] Comparison on v8 and v0 complete
  - #17608
- [x] Gather open GitHub issues related to component in epic issue
  - [#18176](https://github.com/microsoft/fluentui/issues/18176)
- [x] react-* package scaffolded
  - migration to new DX [#18606](https://github.com/microsoft/fluentui/pull/18606)
  - react-image redo for convergence [#16894](https://github.com/microsoft/fluentui/pull/16894)
- [x] Component Spec authored and reviewed
  - #18935 
  - https://github.com/microsoft/fluentui/blob/master/packages/react-image/Spec.md
- [x] **Deliverable:** Reviewed component spec 

# Implementation
 [packages/react-image](https://github.com/microsoft/fluentui/tree/master/packages/react-image)

- [x] Started impl
- [x] Implement component
   - #19687 
   - #19688 
   - #19821 
   -  #19858   
- [x] Add storybook stories
- [x] Using hooks
- [x] Using makeStyles
- [x] Respects Figma tokens (and using provider)
- [x] Respects API principles, shorthands and slots handling
- [x] No dependency on v0/v7
- [x] Add tests - Conformance, Unit, and VR
  - [x] Bundle size fixtures
  - [x] Conformance tests
  - [x] Unit tests - #19521 
  - [x] VR tests - #19532 
  - [x] Accessibility behavior tests
- [x] Write README.md covering basic usage
  - #19802  
- [x] Write initial MIGRATION.md guide (include v8 and v0)
  - #20028 
- [x] Set component ownership in CODEOWNERS
  - #18997
- [x] **Deliverable:** Experimental component ready for partner use, component re-exported in `react-components`

# Validation

- [ ] Started validating
- [ ] Add and validate in UI Builder
- [ ] Add and validate in docs site
- [ ] Validate with token pipeline
- [ ] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods

**Comment by kubkon** [comment]
# Goals for February:
* OpenUI research drafted
* Spec draft (v0 vs v8)
* revamp current impl to use `makeStyles` and React hooks
* add basic storybook stories

For that one, I'm super tempted to forego scaffolding in favour of initially starting off with something clean, in a separate repo/dir with clean (minimal) build structure.

**Comment by kubkon** [comment]
Update:

Making some good progress on aligning the existing react-image with the convergenve RFC and makeStyles for styling. The changes are still in draft but feel free to drop comments now.

**Comment by kubkon** [comment]
### Update 16-02-2021

`react-image` is now up to date with the convergence direction and the changes are ready for merging here #16894.

**Comment by kubkon** [comment]
## Update 23-02-2021

I've started doing OpenUI research for `Image`/`img`, and gathering intel what's out there in the wild. I hope for the first draft PR into the OpenUI repo to be ready by tomorrow.

**Comment by kubkon** [comment]
## Goals for March:

* Land OpenUI research PR [WICG/open-ui#274](https://github.com/WICG/open-ui/pull/274)
* Spec draft (v0 vs v7)

**Comment by JustSlone** [comment]
Update:
- getting started on Spec draft (v0 vs v7)

**Comment by JustSlone** [comment]
Update:
- Open UI has been merged! (thank you @levithomason)

Working on:
- Spec draft for v0 vs v8 (based on @andrefcdias work on flex)
