### ISSUE TITLE
Tooltip Convergence

### ISSUE THREAD

**Issue by behowell** [microsoft/fluentui#16735]
# Preparation:

- [x] Started prep
- [x] Open UI Research complete
  - https://open-ui.org/components/tooltip.research
  - PR: https://github.com/WICG/open-ui/pull/265
- [x] Comparison on v8 and v0 complete
- [x] Gather open GitHub issues related to component in epic issue
  - https://github.com/microsoft/fluentui/issues/15102
- [x] react-* package scaffolded
  - PR: https://github.com/microsoft/fluentui/pull/17133
- [x] Component Spec authored and reviewed
  - PR: https://github.com/microsoft/fluentui/pull/17261
- [x] **Deliverable:** Reviewed component spec 
  - https://github.com/microsoft/fluentui/blob/master/packages/react-tooltip/Spec.md

# Implementation

- [x] Started impl
- [x] Implement component
  - https://github.com/microsoft/fluentui/tree/master/packages/react-tooltip
  - PRs: https://github.com/microsoft/fluentui/pull/17812, https://github.com/microsoft/fluentui/pull/18043
- [x] Add storybook stories
- [x] using hooks
- [x] using makeStyles
- [x] respects Figma tokens (and using provider)
- [x] respects API principles, shorthands and slots handling
- [x] no dependency on v0/v7
- [x] Add tests - Conformance, Unit, and VR
  - [x] Conformance tests
  - [x] Unit tests: #19046
  - [x] VR tests: #19047
  - [x] accessibility behavior tests: #19049
- [ ] Write README.md covering basic usage
- [x] Write initial MIGRATION.md guide (include v8 and v0)
- [x] Fix outstanding implementation issues
  - [x] #18610
  - [x] #19045
- [x] **Deliverable:** Experimental component ready for partner use

# Validation

- [ ] Started validating
- [ ] Add and validate in UI Builder
- [ ] Add and validate in docs site
- [ ] Validate with token pipeline
- [ ] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods 
- [ ] **Deliverable:** Preview component ready for broader/3rd party use

**Comment by behowell** [comment]
February goals:
* Reviewed spec and background research complete
* Working implementation (draft or final)

**Comment by behowell** [comment]
Update:
* Investigating options to structure API to solve issues mentioned in https://github.com/microsoft/fluentui/issues/15102, and reduce bundle size bloat for components that use tooltip internally
* Spec is in progress
* Package scaffolding PR: https://github.com/microsoft/fluentui/pull/17133

**Comment by behowell** [comment]
Update 3-2-2021:
* Spec will be ready for review in tomorrow's office hours
* Proof of concept implementation

Goal for March:
* Completed Tooltip implementation

**Comment by behowell** [comment]
Update 3-9-2021:
* Spec is out for review #17261
* Got some good feedback on the spec. Rethinking some of the design to support aria-describedby correctly.
* Draft implementation working based on the initial spec

Goals:
* Update the spec for aria-describedby, and have it reviewed in for tomorrow's office hours
* Update the implementation based on spec changes

**Comment by behowell** [comment]
Update 3-16-2021:
* Spec is updated/re-worked to correctly handle aria-describedby:  #17261
* Implementation updates are in progress

Goals:
* Have spec reviewed; make changes from review feedback
* Publish implementation PR

**Comment by behowell** [comment]
June goals:
- [ ] Replace onlyIfTruncated with onBeforeShow callback that allows clients to implement the truncated behavior if needed
- [ ] Update spec to match implementation changes
- [ ] (tentative) Add way to show tooltip through imperative API and controlled prop

**Comment by behowell** [comment]
8-10 update @behowell
* No updates this week

**Comment by behowell** [comment]
8-16 update @behowell 
* Refactoring to remove `mergeProps`, PR forthcoming
* Updating spec to match latest changes
