### ISSUE TITLE
Button Convergence

### ISSUE THREAD

**Issue by khmakoto** [microsoft/fluentui#16746]
# Preparation:
- [x] Started prep
- [x] Open UI Research complete
  - https://open-ui.org/components/button
- [x] Comparison on v8 and v0 complete
  - In [SPEC.md](https://github.com/microsoft/fluentui/blob/master/packages/react-button/src/components/Button/SPEC.md)
- [x] Gather open GitHub issues related to component in epic issue
  - In #16819 
- [x] react-* package scaffolded
  - https://github.com/microsoft/fluentui/tree/master/packages/react-button
- [x] Component Spec authored and reviewed
  - In [SPEC.md](https://github.com/microsoft/fluentui/blob/master/packages/react-button/src/components/Button/SPEC.md)
- [x] **Deliverable:** Reviewed component spec 

# Implementation
- [x] Started impl
https://github.com/microsoft/fluentui/tree/master/packages/react-button
- [x] Implement component
- [x] Add storybook stories (see Documentation section below)
- [x] Using hooks
- [x] Using makeStyles
- [x] Respects Figma tokens (and using provider)
- [x] Respects API principles, shorthands and slots handling
- [x] No dependency on v0/v7
- [x] Add tests - Conformance, Unit, and VR
  - [x] Conformance tests
  - [x] Unit tests
  - [x] VR tests
  - [x] Accessibility behavior tests 
- [x] Write README.md covering basic usage
  - In [README.md](https://github.com/microsoft/fluentui/blob/master/packages/react-button/README.md)
- [x] Write initial MIGRATION.md guide (include v8 and v0)
  - In [MIGRATION.md](https://github.com/microsoft/fluentui/blob/master/packages/react-button/src/components/Button/MIGRATION.md)
- [x] **Deliverable:** Experimental component ready for partner use

# Styling variants
- [x] `block`
- [x] `circular`
- [x] `outline`
- [x] `primary`
- [x] `subtle`
- [x] `transparent`

# Component variants
- [x] CompoundButton
- [x] ToggleButton

# Validation
- [ ] Started validating
- [ ] Add and validate in UI Builder
- [ ] Add and validate in docs site
- [ ] Validate with token pipeline
- [ ] Validate in product
  - Currently being validated in Ribbon 
- [ ] Finalize migration guide
  - [ ] Author codemods 
- [ ] **Deliverable:** Preview component ready for broader/3rd party use

**Comment by khmakoto** [comment]
February goal:
- [ ] Comparison on v8 and v0 complete
- [ ] Gather open GitHub issues related to component in epic issue
- [ ] Component Spec authored and reviewed
- [ ] Write README.md covering basic usage
- [ ] Write initial MIGRATION.md guide (include v8 and v0)

**Comment by levithomason** [comment]
Note, I checked off "Using makeStyles" as this was done in #17060

**Comment by khmakoto** [comment]
We'll pick this up during the `April` milestone. We need to:
- Return the variants work.
- Move all other variants beside default to new `makeStyles`.
- Make changes based on spec feedback.
- Do validation steps above.

**Comment by khmakoto** [comment]
The goal for `April` is to:
- [x] Re-introduce `subtle` styling variant
- [x] Re-introduce `transparent` styling variant
  - Pending PR #17736
- [x] Re-introduce `CompoundButton` component
- [x] Re-introduce `ToggleButton` component
