### ISSUE TITLE
Icon Convergence

### ISSUE THREAD

**Issue by paulgildea** [microsoft/fluentui#16745]
# Preparation:

- [x] Started prep
- [x] Open UI Research complete
  - [link to https://open-ui.org/](https://github.com/WICG/open-ui/pull/273)
- [x] Comparison on v8 and v0 complete
   - [Comparison](https://hackmd.io/7zuk352RT7-H7CAXn5AG4g) 
- [x] Gather open GitHub issues related to component
   - #17212  
- [x] react-\* package scaffolded
  - [link to package](https://www.npmjs.com/package/@fluentui/react-icons-preview/v/1.1.102)
- [ ] Component Spec authored and reviewed
  - [link to spec in component package]
- [ ] **Deliverable:** Reviewed component spec

# Implementation

[link to react-* package folder]

- [x] Started impl
- [x] Implement component
- [ ] Add storybook stories
- [ ] Using hooks
- [ ] Using makeStyles
- [ ] Respects Figma tokens (and using provider)
- [ ] Respects API principles, shorthands and slots handling
- [x] No dependency on v0/v7
- [ ] Add tests - Conformance, Unit, and VR
  - [ ] Conformance tests
  - [ ] Unit tests
  - [ ] VR tests
  - [ ] Accessibility behavior tests 
- [x] Write README.md covering basic usage
- [x] Write initial MIGRATION.md guide (include v8 and v0)
- [ ] **Deliverable:** Experimental component ready for partner use

# Validation

- [ ] Started validating
- [ ] Add and validate in UI Builder
- [ ] Add and validate in docs site
- [ ] Validate with token pipeline
- [ ] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods
- [ ] **Deliverable:** Preview component ready for broader/3rd party use

**Comment by tomi-msft** [comment]
# Goal for February:
- Compile a list of questions/feedback from partners who have begun to switch/making the switch from font based icon package to svg icon package
   - [Icon Migration Questions]
- Comparison on v8 and v0 complete
- Gather open GitHub issues related to component in epic issue
  - [link to issue]
- react-icons package published
  - [link to package]
- Icon Spec authored and reviewed
  - [link to spec in component package]
- **Deliverable:** Reviewed component spec

**Comment by tomi-msft** [comment]
Update:
- [Icon Migration Questions](https://hackmd.io/JhsO5tanTbiVDW3HCv4GIg)

To Do Tuesday:
- Comparison on v8 and v0
- Gather open GitHub issues related to component in epic issue

**Comment by tomi-msft** [comment]
Update:

- Update build script to include esnext build to make package tree shakeable
- Add interface to help label icons for narrator to improve accessibility

[Updated here](https://github.com/microsoft/fluentui-system-icons/pull/206)

**Comment by behowell** [comment]
8-2 update @tomi-msft 
* Working on including default styling in the package, replacing webpack with microsoft-load-theme-styles
* Fixing issue with `primaryFill` prop to avoid spreading it on the root `span`

**Comment by behowell** [comment]
8-9 update @tomi-msft 
* Wrote RFC for a build tool to trim bundle size per-project: #19279
* Working on using react-make-styles for styling

**Comment by behowell** [comment]
8-16 update @tomi-msft 
* Build tool not the direction we're going
* Researching best way to handle the size attribute
* Updated styling in react-icon to use makeStyles
