### ISSUE TITLE
Button: Open issues to resolve when converging

### ISSUE THREAD

**Issue by khmakoto** [microsoft/fluentui#16819]
Open issues worth addressing for `Button` when converged. From a search of: [`is:issue is:open button`](https://github.com/microsoft/fluentui/issues?q=is%3Aissue+is%3Aopen+button), [`is:open is:issue label:"Component: Button"`](https://github.com/microsoft/fluentui/issues?q=is%3Aopen+is%3Aissue+label%3A%22Component%3A+Button%22), [`is:open is:issue label:"Component: CompoundButton"`](https://github.com/microsoft/fluentui/issues?q=is%3Aopen+is%3Aissue+label%3A%22Component%3A+CompoundButton%22), [`is:open is:issue label:"Component: IconButton"`](https://github.com/microsoft/fluentui/issues?q=is%3Aopen+is%3Aissue+label%3A%22Component%3A+IconButton%22) and [`is:open is:issue label:"Component: ToggleButton"`](https://github.com/microsoft/fluentui/issues?q=is%3Aopen+is%3Aissue+label%3A%22Component%3A+ToggleButton%22).

#### Issues related specifically to convergence
- [x] ~#17555 - Update makeMergePropsCompat to makeMergeProps in react-button~
- [x] ~#16818 - Remove all v0/v8 dependencies in react-button~
- [x] ~#16820 - Button: Integrate makeStyles in react-button's Button~

#### react-button issues
- [x] ~#16610 - MenuButton onClick is not dismissing after clicking~
- [x] ~#16607 - Context menu is not showing when MenuButton clicked~
- [x] ~#16562 - React-button font size to be adjustable~
- [x] ~#15613 - Fix IE11 support in new Button~
- [x] ~#15542 - @fluentui/react-button can't correctly handle click event with menuProps on mobile browser~

#### v7/v8 issues
- [x] ~#17606 - Button component does not display tooltip when disabled~
- [ ] #17407 - Sizes for IconButton
- [ ] #17186 - JAWS reads Contextual Menu Button as "Button, Menu" which is incorrect
- [ ] #17164 - Web contextual menu button doesn't come out of menu when I press 'tab' key
- [x] ~#16837 - Border color of icon button not changing from hover state until re-hovered~
- [ ] #16201 - Transition for color of *Button components is delayed
- [x] ~#16031 - IconButton/ CommandButton menus do not close when invoked twice in safari~
- [x] ~#15329 - CompoundButton loses child control alignments when clicked~
- [x] ~#14969 - SplitButton - glitchy button border~
- [x] ~#14588 - Please add an option to choose the tag of button~
- [x] ~#14303 - SplitButton - main action not reachable on mobile~
- [ ] #14159 - button not visible properly
- [x] ~#13889 - IconButton mouseOut called when opening submenu~
- [x] ~#13746 - IconButton triggering onDismiss as soon as the menu is launched on iPhone~
- [x] ~#13708 - RTL split button style messed up~
- [ ] #13336 - Dialog footer buttons vertically misaligned when icon is present
- [x] ~#13020 - First time keyboard navigation focus box is not visible.~
- [x] ~#12998 - overflow hidden on the button makes the text chop off~
- [ ] #12814 - Buttons are not styleable via styles function
- [ ] #12699 - Sizes for toggle button
- [x] ~#12639 - do we have toggle buttons or button groups?~
- [x] ~#12291 - No visible focus when button programmatically focused~
- [x] ~#10896 - IButtonProps should support string index sig~
- [x] ~#10863 - Primary Button label missing in fluent theme with strong scheme~
- [ ] #10676 - LinkButton component that will render a link styled as a Button
- [ ] #10453 - onItemClick not invoked on split buttons
- [x] ~#9418 - ActionButton does not use semantic slot for disabled text color~

#### v0 issues
- [ ] #16853 - Disabled property is missing on a Button when disabled and loading props are both true
- [ ] #16205 - borderRadius in ButtonVariables doesn't work in ButtonGroup

**Comment by compulim** [comment]
Is the work for #12699 completed? Or is it wrongly closed by the bot?

**Comment by khmakoto** [comment]
@compulim wrongly closed, I just reopened it.

**Comment by idolize** [comment]
https://github.com/microsoft/fluentui/issues/13746 should also still be open? - I can still reproduce on `8.46.0` in Safari

**Comment by khmakoto** [comment]
@idolize I will reopen it since it is still relevant 😄

**Comment by idolize** [comment]
@khmakoto thanks - I see it is reopened but it says I cannot comment there.

Anyway, what I was going to comment is that I was able to come up with a temporary fix for Safari by disabling 'resize' dismiss events. This seems to trigger a resize instantly whenever the menu popup opens in Safari (thus instantly closing it), so turning this off is a workaround:

```jsx
    <IconButton
      menuProps={{
        items: menuItems,
        calloutProps: {
          // !! Needed to fix issue in Safari
          preventDismissOnEvent: (e) => e.type === 'resize',
        },
      }}
      role="menuitem"
      title="More options"
    />
```

I also had to do this in my Callout menus as well:

```jsx
        <Callout
          onDismiss={handleClose}
          // !! Needed to fix issue in Safari
          preventDismissOnEvent={(e) => e.type === 'resize'}
        >
```

**Comment by khmakoto** [comment]
@idolize I've unlocked the conversation, would you mind pasting the comment above on that issue so that the discussion is kept on that same thread?
