### ISSUE TITLE
Text Convergence

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#16847]
# Preparation:

- [x] Started prep
- [x] Open UI Research complete
  - https://github.com/openui/open-ui/pull/351
  - [link to https://open-ui.org/]
- [x] Comparison on v8 and v0 complete
  - Addressed in the PR: https://github.com/microsoft/fluentui/pull/18462
- [x] Gather open GitHub issues related to component
  - https://github.com/microsoft/fluentui/issues/16840
- [x] react-\* package scaffolded
  - https://github.com/microsoft/fluentui/pull/18571
- [x] Component Spec authored and reviewed
  - https://github.com/microsoft/fluentui/pull/18462
  - https://github.com/microsoft/fluentui/blob/master/packages/react-text/Spec.md
- [x] **Deliverable:** Reviewed component spec

# Implementation

https://github.com/microsoft/fluentui/tree/master/packages/react-text

- [x] Started impl
- [x] Implement component
  - [x] Text
    - https://github.com/microsoft/fluentui/pull/18590
  - [x] make-styles rules
    - https://github.com/microsoft/fluentui/pull/18778
  - [x] Wrappers
    - https://github.com/microsoft/fluentui/pull/18817
    - https://github.com/microsoft/fluentui/pull/18956
- [x] Add storybook stories
  - [x] Text
  - [x] Wrappers
- [x] Using hooks
- [x] Using makeStyles
- [x] Respects Figma tokens (and using provider)
- [x] Respects API principles, shorthands and slots handling
- [x] No dependency on v0/v7
- [x] Add tests - Conformance, Unit, and VR
  - [x] Bundle size fixtures
  - [x] Conformance tests
    - [x] Text
    - [x] Wrappers
  - [x] Unit tests
    - [x] Text
    - [x] Wrappers
  - [x] VR tests - https://github.com/microsoft/fluentui/pull/19022
    - [x] Text
    - [x] Wrappers
  - [x] Accessibility behavior tests
    - N/A
- [x] Write README.md covering basic usage
  - https://github.com/microsoft/fluentui/pull/19073
- [x] Write initial MIGRATION.md guide (include v8 and v0)
  - https://github.com/microsoft/fluentui/pull/19120
- [x] Set component ownership in CODEOWNERS
  - https://github.com/microsoft/fluentui/pull/18997
- [x] **Deliverable:** Experimental component ready for partner use, component re-exported in `react-components`
   - https://github.com/microsoft/fluentui/pull/19107
   - https://github.com/microsoft/fluentui/pull/19363

# Validation

- [ ] Started validating
- [ ] Add and validate in UI Builder
- [ ] Add and validate in docs site
- [ ] Validate with token pipeline
- [ ] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods
- [ ] **Deliverable:** Preview component ready for broader/3rd party use

**Comment by Hotell** [comment]
## February Project cycle

Goals:

* Preparation phase 

Stretch goals:

* Implementation phase
  - implementation draft + test
  - stories

**Comment by Hotell** [comment]
No progress so far. I'll remove this from Feb Cycle as I'm might not get a chance to focus on this because of build system tweaks -> https://github.com/microsoft/fluentui/issues/16889
