### ISSUE TITLE
Badge convergence

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#16925]
# Preparation:

- [x] Started prep
- [x] Open UI Research complete: https://github.com/WICG/open-ui/pull/224
- [x] Comparison on v8 and v0 complete
- [x] Gather open GitHub issues related to component
- [x] react-\* package scaffolded
  - https://github.com/microsoft/fluentui/tree/master/packages/react-badge
- [x] Component Spec authored and reviewed
  - https://github.com/microsoft/fluentui/blob/master/packages/react-badge/Spec.md
- [ ] **Deliverable:** Reviewed component spec

# Implementation

[link to react-* package folder]

- [ ] Started impl
- [ ] Implement component
- [ ] Add storybook stories
- [ ] Using hooks
- [ ] Using makeStyles
- [ ] Respects Figma tokens (and using provider)
- [ ] Respects API principles, shorthands and slots handling
- [ ] No dependency on v0/v7
- [ ] Add tests - Conformance, Unit, and VR
  - [ ] Conformance tests
  - [ ] Unit tests
  - [ ] VR tests
  - [ ] Accessibility behavior tests 
- [ ] Write README.md covering basic usage
- [ ] Write initial MIGRATION.md guide (include v8 and v0)
- [ ] **Deliverable:** Experimental component ready for partner use

# Validation

- [ ] Started validating
- [ ] Add and validate in UI Builder
- [ ] Add and validate in docs site
- [ ] Validate with token pipeline
- [ ] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods
- [ ] **Deliverable:** Preview component ready for broader/3rd party use

**Comment by JustSlone** [comment]
Update:
- Spec in review
- Base Badge PR in review

- Implementation in progress

**Comment by JustSlone** [comment]
Update:
- Spec merged!
- Base Badge merged!
- Implementation of specific components in progress
