### ISSUE TITLE
Release alpha version of converged Provider, Theme, Avatar and Button

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#17056]
# First Converged components alpha release

The release is planned for Feb 24th and will include:
- **Provider**, **Theme**, **Avatar** and **Button**
- limited documentation describing basic principles of component usage and styling

**Note**: API, theming or internals might change after this date, we will support partners with the transition

## What's missing / not finished
- icons - @fluentui/react (mdl2) or @fluentui/react-northstar icons can temporarily be used as a replacement in appropriate slots
- component tokens - can be achieved using style overrides
- animations
- full storybook documentation - but a URL with interim doc will be shared

## Converged component requirements
- uses `makeStyles`
- has no v0/v7 dependencies
- uses design tokens

**Comment by miroslavstastny** [comment]
### Packages to be released (checked means ready to be released, NOT released)
- [ ] `react-provider`
- [ ] `react-theme`
- [ ] `make-styles`
- [ ] `react-make-styles`
- [x] `react-avatar` - merged to master, done
- [ ] `react-button` - WIP, to be merged by the end of the week
- [x] `react-link` - merged to master, done
- [x] `react-image`
- [ ] `react-divider` - ?

### To discuss
Versioning? -> 10am
Suite package?
Manually triggered vs nightly release?

**Comment by miroslavstastny** [comment]
These are the current dependencies of `react-components` package:
![image](https://user-images.githubusercontent.com/9615899/108878228-569adf80-7600-11eb-9ce6-e805b4b4d0b1.png)

Green circle means the package is part of converged.
Red circle means the package is part of v7/8 and should be removed from the dependency tree.
Red question marks require further discussion.
`compat` - those will be removed once we will remove `compat` layer from `react-theme-provider`.

**Comment by miroslavstastny** [comment]
### TODO before release
- [x] bump everything to 9.0.0-alpha .0
	- [x] agree on dist tag - `alpha` or `latest`? - **`alpha`  and let's face the issues, this should be short term only (~3m)**
	- [x] have a list of bumped components which are not part of `react-components`
		- [x] what exactly should we bump? - **only the ones re-exported in `react-components`**
- [ ] create `react-components` package
	- [ ] revisit stories
	- [ ] documentation for `makeStyles`, provider
- [ ] add/verify screener tests
- [ ] package test for converged?
- [ ] discuss `react-provider` vs `react-theme-provider` split?
- [ ] test in codesandbox, CRA, CRA-ts
- [ ] remove avatar dependency on `@fluentui/react-icons-mdl2`
- [ ] remove compat layer from `react-theme-provider` (that is used only for to-be-converged components, not in production)

### TODO not blocking release
- [ ] add dependency check to CI
	- there is still converged -> v7/8 dep by `react-utilities` - conclusion is to break (copy&paste) the dependency
	- then add the check (allow-list of converged dependencies)
- [ ] token overrides?
- [ ] makeStyles vs makeOverrides
- [ ] cleanup hooks (as)
	- dig into `mergeProps` and prepare for a discussion on that
- [ ] makeStyles build time transform
- [ ] bundle size test
- [ ] performance tests (with Flamegrill) for converged components
- [ ] do we need `set-version` for converged?
- [ ] move react-compose to v0 (react-bindings) as it is used in some components
