### ISSUE TITLE
Open Issues to track as part of the converged icon component

### ISSUE THREAD

**Issue by tomi-msft** [microsoft/fluentui#17212]
### Describe the issue:

Open issues to keep track of as part of the converged icon work.

- [ ] Looking for Fluent UI Microsoft Icons in SVG (M365 and D365) #17166 
- [ ] Update package names in aka.ms/fluentui-icons #15957 
- [ ] Is there a CDN link to the latest fabric icon set css file? #15939
- [ ] Add CheckboxIndeterminateCombo #15305
- [ ] No way to use brand ()365) multi-color icons #14151
- [ ] "StatusCircle" icon does not have the outer circle #13542
- [ ] Mirrored Icons in RTL mode #12697
- [ ] Font and IconFont alternative for non-office-related applications #12488
     - They should be able to use `@fluentui/react-icons-mdl2` or `@fluentui/react-icons` to accomplish this
- [ ] Missing shape icons #11478
- [ ] When empty string is passed as iconName in DefaultButton the icon placeholder isn't rendered #12425
- [ ] Improve typedefs for icon names #10092
- [ ] There is a "+" missing in one of the icons in Fabric UI icon library #9938
- [ ] Missing icons from Fabric MDL2 external icon font #9444

**Comment by SiemvandenBerg** [comment]
Hello,
Is this work going to resolve the issues there are with fabricmdl2icons missing icons? To clarify, some of the glyphs you can copy from https://uifabricicons.azurewebsites.net/ are not part of the font you can download on https://developer.microsoft.com/en-us/fluentui#/resources. I think I can pull the the font from the former by means of the network tab in dev tools. But I'd rather not. I really hope you can just have the same latest version of the icon set available on all channels, because it is sometimes really messing up our UX and development process.
