### ISSUE TITLE
Build and/or shield mop-up work (Elizabeth)

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#17229]
Placeholder issue for 2nd half of March work: 

#### Build-related
- [ ] Finish or close package structure/naming RFCs #16577 and #16772 
- [ ] Finish PR deploy storage/Azure access fix #16304
- [ ] Finish pre-react 17 test fixes #17050
- [ ] Possibly: get tests running with react 17 #16886 (will require jest upgrade; should get TS upgrade done first)
- [ ] Assist with TS upgrade and other build work as needed

#### Shield
Go through assigned issues and at least get them past needs triage/investigation state (close or propose future action)

**Comment by JustSlone** [comment]
In Progress:
- PR Deploy to storage/Azure in progress
- Cleanup: Removed cruft and extra dependencies from packages
- Fixing optimization in react-conformance (and error message bubbling)
