### ISSUE TITLE
Stabilize react-components 

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#17242]
In previous milestones, we delivered converged styling (#16372) and released alpha version of converged `@fluentui/react-components` (#17056).

We gathered feedback and created a list of follow-up tasks. Now it's time to address the list.

- [ ] **Token overrides, component tokens**
- [ ] **Storybook**
  - [ ] tokens addon
  - [ ] revisit stories
  - [ ] documentation for `makeStyles`, provider
  - [ ] Figma links to each component
  - [ ] How to have v7/v8 with converged
  - [ ] How to have v0 with converged
- [ ] **upgrade styling to `makeOverrides`**
- [ ] **makeStyles build time transform**
- [ ] add/verify screener tests
- [ ] package test for converged?
- [ ] discuss `react-provider` vs `react-theme-provider` split?
- [ ] add dependency check to CI - converged should not depend on anything from northstar or v7/8
- [ ] cleanup hooks (as)
	- dig into `mergeProps` and prepare for a discussion on that
- [ ] bundle size test
- [ ] performance tests (with Flamegrill) for converged components - sync with @kubkon 
- [ ] move react-compose to v0 (react-bindings) as it is used in some components

## Additional tasks

These tasks were originally not in scope but appeared later.

- [ ] automatically publish storybook
- [ ] add ability to specify different `font-family` for different languages
- [ ] how/when do we inject static styles - normalize, and theme-specific root styles (font, color, background)
- [ ] DOC: how partners consume theme and style their components (`makeStyles` docs)

**Comment by paulgildea** [comment]
@miroslavstastny, @gouttierre - I've converted this list into this project: https://github.com/microsoft/fluentui/projects/42 

Right now everything are cards, but we can convert to issues as needed so we can assign out to folks or they can self assign to pick up an issue and run with it.

**Comment by JustSlone** [comment]
Update:
- Not many updates since last week
- Bernardo migrating components to newer make-styles
- Working on high-contrast theme

**Comment by miroslavstastny** [comment]
Update Apr 20:

- `Accordion` merged and published
  - still plan to do a perf analysis as there are potentially unnecessary re-renders
  - discussion re Aria in Accordion
- build time styles - babel plugin PR out #17803
  - Next step is to add it to build/CI
  - we need to do the same for `makeStaticStyles` (to get rid of runtime dependencies)
- Portal PR #17779
- E2E tests merged #17778

**Comment by miroslavstastny** [comment]
Closing, the remaining work is tracked in https://github.com/microsoft/fluentui/projects/42
