### ISSUE TITLE
upgrade styling to makeOverrides()

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#17334]
We have recently merged RFC for updates into `makeStyles()` API (see #17076 for more details).

This issue contains a proposal/an implementation plan for these changes.

## Action items

Upgrading styles in all components at the same time may be not possible, that's why it's sliced into smaller chunks.

- rename `makeStyles` to `makeStylesCompat` 
  - [x] in `@fluentui/make-styles` & `@fluentui/react-make-styles` #17354
  - [x] in all affected packages #17354
- introduce `makeStyles` (`makeOverrides`)
   - [x] pick changes from #16923
   - [x] create `makeStyles()` in `@fluentui/make-styles` & `@fluentui/react-make-styles`
   - [#] update `README.md` in `@fluentui/make-styles` #17726
   - [x] update `makeStyles` spec (#17609)
- update usages of `makeStylesCompat()` to `makeStyles()`
  - [x] react-accordion #17395 
  - [x] react-button #17415
  - [x] react-badge #17416, #17435, #17513
  - [x] react-cards #17437
  - [x] react-flex #17440
  - [x] react-image #17441
  - [x] react-link #17442
  - [x] react-text #17443
  - [x] react-menu #17439
  - [x] react-avatar #17514 
  - [x] react-examples #17522
  - [x] apps/perf-test #17523
  - [x] react-divider #17525
- remove `makeStylesCompat()` #17539
