### ISSUE TITLE
TypeScript 4 upgrade follow-ups

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#18025]
#17932 upgrading to TS 4.1 has been merged, but there are still some follow-ups needed.

- [x] Small unaddressed PR comments - PR #18027
- [ ] **Add a test** to ensure basic compatibility with TS 3.9. - #18440
- [x] **Update eslint-related deps** to compatible versions - PR #18024
- [x] **Update prettier** to compatible version (needed for `export type`) - tracked by #18008, PR #18041
- [ ] **Update ts-jest** to compatible version - #18442

### Possible future follow-ups

- **Full type downleveling/`typesVersions`** - #18441

### Questions

- What is our consumer TS min bar for converged?
- What is our consumer TS min bar for northstar? 4.1.5

**Comment by layershifter** [comment]
> * What is our consumer TS min bar for northstar?

"typescript": "4.1.5", so we don't need to integrate downleveling into Gulp scripts currently.

**Comment by ecraig12345** [comment]
Closing in favor of individual tracking issues (linked in updated issue description).
