### ISSUE TITLE
SplitButton Convergence

### ISSUE THREAD

**Issue by khmakoto** [microsoft/fluentui#18136]
# Preparation:

- [x] Started prep
- [ ] Open UI Research complete
  - [link to https://open-ui.org/]
- [ ] Comparison on v8 and v0 complete
- [ ] Gather open GitHub issues related to component
- [ ] react-\* package scaffolded
  - [link to package]
- [ ] Component Spec authored and reviewed
  - [link to spec in component package]
- [ ] **Deliverable:** Reviewed component spec

# Implementation

[link to react-* package folder]

- [x] Started impl
- [x] Implement component
- [x] Add storybook stories
- [x] Using hooks
- [x] Using makeStyles
- [x] Respects Figma tokens (and using provider)
- [x] Respects API principles, shorthands and slots handling
- [x] No dependency on v0/v8
- [ ] Add tests - Conformance, Unit, and VR
  - [ ] Conformance tests
  - [ ] Unit tests
  - [ ] VR tests
  - [ ] Accessibility behavior tests
- [ ] Write README.md covering basic usage
- [ ] Write initial MIGRATION.md guide (include v8 and v0)
- [x] Set component ownership in CODEOWNERS
- [ ] **Deliverable:** Experimental component ready for partner use, component re-exported in `react-components`

# Validation

- [ ] Started validating
- [ ] Add and validate in UI Builder
- [ ] Add and validate in docs site
- [ ] Validate with token pipeline
- [ ] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods
- [ ] **Deliverable:** Preview component ready for broader/3rd party use

**Comment by khmakoto** [comment]
To work in June:
- [ ] Adopt better contract with `Menu` in `@fluentui/react-menu`.
- [ ] Write spec and migration guide for `SplitButton` that follows the explorations we have been having.

**Comment by behowell** [comment]
8-9 status @khmakoto 
* no updates this week

**Comment by behowell** [comment]
8-17 status @khmakoto 
* No updates this week; on hold pending updates to MenuButton (#18135)

**Comment by khmakoto** [comment]
The component is stable now. Closing in favor of smaller issues if they arise in the future.
