### ISSUE TITLE
Input Convergence

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#18131]
## Outstanding work as of January 2022

[query for Input labeled issues](https://github.com/microsoft/fluentui/labels/Component%3A%20Input)

- [x] RC prep (mostly done) - #20936
- [x] a11y pass (mostly done) - #21174
  - [x] contrast issues with filled appearances - #21449
  - [x] accessible examples for contentBefore/after - #21450
- [x] minor outline styling issue - #21296
- [ ] minor open design questions - #21464

### Possible items for later

- Field (for attaching label) - #19627
- Implement additional features, related components, and/or component variants: tentative details/research in [Spec-variants.md](https://github.com/microsoft/fluentui/blob/master/packages/react-input/Spec-variants.md)
  - Bookends - #21462
  - Textarea (multiline)
  - Validation
  - Password
  - Masking

## Preparation:

- [x] Started prep
- [ ] Open UI Research complete
  - [link to https://open-ui.org/]
- [x] Comparison on v8 and v0 complete
- [ ] Gather open GitHub issues related to component
- [x] [react-\* package scaffolded](https://github.com/microsoft/fluentui/tree/master/packages/react-input)
- [x] [Component Spec authored and reviewed](https://github.com/microsoft/fluentui/blob/master/packages/react-input/Spec.md)
- [x] **Deliverable:** Reviewed component spec

## Implementation

https://github.com/microsoft/fluentui/tree/master/packages/react-input

- [x] Started impl - #18781
- [x] Implement component
- [x] Add storybook stories
- [x] Using hooks
- [x] Using makeStyles
- [x] Respects Figma tokens (and using provider)
  - [x] Basic styling: #19376
  - [x] ~~Bookend styling~~ deferred
  - [x] Focus styling #20648
  - [ ] Styling polish after design review
- [x] Respects API principles, shorthands and slots handling
- [x] No dependency on v0/v7
- [x] Add tests - Conformance, Unit, and VR
  - [x] Conformance tests
  - [x] Unit tests
  - [x] VR tests #20648
  - [x] ~~Accessibility behavior tests~~ probably not needed due to entirely using a native element
- [ ] Accessibility pass #21174 (almost done)
- [ ] Write README.md covering basic usage
- [ ] Write initial MIGRATION.md guide (include v8 and v0)
- [x] Set component ownership in CODEOWNERS
- [x] **Deliverable:** Experimental component ready for partner use, component re-exported in `react-components`

## Validation

- [ ] Started validating
- [x] ~~Validate with token pipeline~~
- [ ] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods
- [ ] **Deliverable:** Preview component ready for broader/3rd party use

**Comment by ecraig12345** [comment]
For June:
- Research/spec
- MVP implementation

**Comment by behowell** [comment]
8-2 update - @ecraig12345:
* Basic input implementation merged
* Ongoing work on RFCs for how to apply props to input slots, which will affect Input
* Getting started on styling

**Comment by paulgildea** [comment]
Adding Azure requirements here so that I don't lose them:
- Providing a mechanism for a copy/paste icon that will copy the textual content to the clipboard

**Comment by ecraig12345** [comment]
@paulgildea That should be easily doable with slots. We could have an example of how to do it, but we probably won't build it in to the component itself.

**Comment by behowell** [comment]
8-9 update @ecraig12345 
* No updates this week

**Comment by ecraig12345** [comment]
8/16
- Working on styling: almost done; main holdup is focus styling
- Trying to have native props RFC ready to discuss on Wednesday
