### ISSUE TITLE
Dropdown/Combobox/Picker Convergence

### ISSUE THREAD

**Issue by smhigley** [microsoft/fluentui#18133]
# Preparation:
- [x] Started prep
- [x] Open UI Research complete
  - TODO: link to open PR
- [x] Comparison on v8 and v0 complete
- [x] Gather open GitHub issues related to component
- [x] [react-combobox package](https://github.com/microsoft/fluentui/tree/master/packages/react-combobox) scaffolded
- [x] [react-select package](https://github.com/microsoft/fluentui/tree/master/packages/react-select) scaffolded
- [x] Component Specs authored and reviewed
  - [x] [react-combobox](https://github.com/microsoft/fluentui/blob/master/packages/react-combobox/Spec.md)
  - [x] [react-select](https://github.com/microsoft/fluentui/blob/master/packages/react-select/Spec.md)
- [ ] **Deliverable:** Reviewed component spec

# Implementation: react-combobox

[link to react-* package folder]
- [x] Started impl
- [x] Implement component
- [ ] Add storybook stories
- [x] Using hooks
- [x] Using makeStyles
- [ ] Respects Figma tokens (and using provider): #22461
- [x] Respects API principles, shorthands and slots handling
- [x] No dependency on v0/v7
- [ ] Add tests - Conformance, Unit, and VR
  - [ ] Conformance tests
  - [ ] Unit tests
  - [ ] VR tests
  - [ ] Accessibility behavior tests
- [x] Write README.md covering basic usage
- [ ] Write initial MIGRATION.md guide (include v8 and v0)
- [ ] Set component ownership in CODEOWNERS
- [ ] **Deliverable:** Experimental component ready for partner use, component re-exported in `react-components`

## Resolve open issues/questions before beta
- [ ] Naming of package and components #21989
- [ ] Split Dropdown vs. Combobox exports
- [ ] Investigate DOM-based activedescendant/option-ordering implementation #22055
- [ ] slot/children structure https://github.com/microsoft/fluentui/issues/22331

# Implementation: react-select

- [x] Started impl
- [x] Implement component
- [x] Add storybook stories
- [x] Using hooks
- [x] Using makeStyles
- [x] Respects Figma tokens PR: #21068
- [x] Respects API principles, shorthands and slots handling
- [x] No dependency on v0/v7
- [ ] Add tests - Conformance, Unit, and VR
  - [ ] Conformance tests
  - [ ] Unit tests
  - [ ] VR tests
  - [ ] Accessibility behavior tests
- [x] Write README.md covering basic usage
- [ ] Write initial MIGRATION.md guide (include v8 and v0)
- [ ] Set component ownership in CODEOWNERS
- [ ] **Deliverable:** Experimental component ready for partner use, component re-exported in `react-components`

# Validation
- [ ] Started validating
- [ ] Add and validate in UI Builder
- [ ] Add and validate in docs site
- [ ] Validate with token pipeline
- [ ] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods
- [ ] **Deliverable:** Preview component ready for broader/3rd party use

**Comment by gouttierre** [comment]
@JustSlone would this issue then solve for #16360?

**Comment by behowell** [comment]
Update 8-2 - @smhigley:
* Working on RFC for how to handle arrays of slots, e.g. for dropdown's options array

**Comment by paulgildea** [comment]
Adding some Azure requirements for Dropdown so that we don't lose them: 

- Having a way to "Select All" on all the `Dropdown` items
- Providing a way to filter the results

**Comment by smhigley** [comment]
RFC for slot arrays: https://github.com/microsoft/fluentui/pull/19266

**Comment by behowell** [comment]
8-16 update @smhigley 
* No update this week - on shield

**Comment by paulgildea** [comment]
I'm reopening this issue because to use this as our main Component Tracking Epic. This was soft closed do to inactivity. 

@smhigley can we get an update on all checklist items?
