### ISSUE TITLE
Update jest and ts-jest to 27

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#18442]
We're currently on Jest ~~24~~ 26 (current: 27) and ts-jest ~~24~~ 26. Now that we've upgraded to TS 4.1, we're unblocked from upgrading these deps. Unfortunately this is likely to require a significant amount of work.

~~[Jest 25 release notes](https://jestjs.io/blog/2020/01/21/jest-25)~~
~~[Jest 26 release notes](https://jestjs.io/blog/2020/05/05/jest-26)~~
[Jest 27 release notes](https://jestjs.io/blog/2021/05/25/jest-27)
[ts-jest changelog](https://github.com/kulshekhar/ts-jest/blob/master/CHANGELOG.md) (note that they don't use semver)

**More motivation:**
- ~~ts-jest 24 gives this warning in our build today...~~
> `Version 4.1.5 of typescript installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=2.7.0 <4.0.0). Please do not report issues in ts-jest if you are using unsupported versions.`
- using old JSDOM that doesn't support MutationObservers and other platform features
- wrong/insufficient jest typings

### Tasks
- [x] migrate to jest/ts-jest 25 | #20716
- [x] migrate to jest/ts-jest 26 | #20716
- [ ] migrate to jest/ts-jest 27

#### Optional Tasks:
- [ ] #20826

**Comment by Hotell** [comment]
Tried to update to jest v25 then v26,

react-examples and react (v8) are causing lot of issues ( tests passing - see PR for more details https://github.com/microsoft/fluentui/pull/20716 )
