### ISSUE TITLE
Checkbox Convergence

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#18454]
# Preparation:

- [x] Started prep
- [x] Open UI Research complete
  - Concepts: https://open-ui.org/components/checkbox.research.concepts
  - Findings: https://open-ui.org/components/checkbox.research.findings
  - Proposal: https://open-ui.org/components/checkbox
- [x] Comparison on v8 and v0 complete
- [x] Gather open GitHub issues related to component
- [x] react-\* package scaffolded
  - https://github.com/microsoft/fluentui/tree/master/packages/react-checkbox
- [x] Component Spec authored and reviewed
  - https://github.com/microsoft/fluentui/blob/master/packages/react-checkbox/Spec.md
- [x] **Deliverable:** Reviewed component spec

# Implementation

- [x] Started impl
- [x] Implement component
  - https://github.com/microsoft/fluentui/tree/master/packages/react-checkbox
- [x] Add storybook stories
- [x] Using hooks
- [x] Using makeStyles
- [x] Respects Figma tokens (and using provider)
- [x] Respects API principles, shorthands and slots handling
- [x] No dependency on v0/v7
- [x] Add tests - Conformance, Unit, and VR
  - [x] Conformance tests
  - [x] Unit tests
  - [x] VR tests
  - [x] Accessibility behavior tests
    - [x] Checklist #22276 
- [x] Implementation issues: #18804, #18983, and #18949
- [x] Write README.md covering basic usage
- [x] Write initial MIGRATION.md guide (include v8 and v0)
- [ ] Set component ownership in CODEOWNERS
- [ ] **Deliverable:** Experimental component ready for partner use, component re-exported in `react-components`

# Validation

- [ ] Started validating
- [ ] Add and validate in UI Builder
- [ ] Add and validate in docs site
- [ ] Validate with token pipeline
- [ ] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods
- [ ] **Deliverable:** Preview component ready for broader/3rd party use
- [x] #22276

**Comment by sopranopillow** [comment]
June goals:
- Cemplete spec (Preparation section)
- Start implementation

**Comment by sopranopillow** [comment]
July goals:

[] Finish implementation
[] Finish unit and VR tests
[] Agree on input pattern RFC

**Comment by behowell** [comment]
8-2 update- @sopranopillow 
* Getting PR ready to update checkbox to remove `mergePropsCompat`
* Refactoring styles for the `indicator` slot
* Updating unit tests

**Comment by sopranopillow** [comment]
Currently missing:
* e2e tests
* css animations
* some minor TODOs

**Comment by behowell** [comment]
8-10 update - @behowell
* PR out, needs to be finished and merged: #19225
* Need to find new owner for remaining work

**Comment by micahgodbolt** [comment]
safe to close this up?

**Comment by khmakoto** [comment]
@micahgodbolt let's just close it and focus on more individual tasks instead of larger epics.
