### ISSUE TITLE
migration: migrate converged packages to new DX (1st stage)

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#18579]
# Preparation:

- [x] nx migration generator implementation #18421 

# What is new DX (1st stage) ?
- **Tooling:** only source of truth for package resolution/mapping is `tsconfig.base.json`, that uses TSpath aliases
- **TypeScript:** go to definition goes to actual source instead to generated declaration files
- **Plug n play:** clone/update your local copy and start working without need to build anything (`jest-serializer-make-styles` and `babel-make-styles` needs still manual build https://github.com/microsoft/fluentui/issues/18357)
- **Task runner:** 
  - simplified package.json#scripts tasks
  - running storybook/start and test will invoke native `storybook` and `jest` binaries respectively
- **Storybook:** 
  - every package uses collocated stories with local setup that inherits from global `/.storybook` configuration. 
  - this makes running storybook much faster and also enables for experimentation on your local package level without affecting rest
- **Testing:** 
   - tests are setup via  locally scoped config that inherits from root `/jest.preset.js`. 
   - all projects are registered via jest projects in root `/jest.config.js` which enables also easy debugging from within your IDE.

# Packages that need migration

- [x] @fluentui/babel-make-styles #18758
- [x] @fluentui/jest-serializer-make-styles #18719
- [x] @fluentui/make-styles #18673
- [x] @fluentui/react-accordion #18553 
- [x] @fluentui/react-avatar #18866 
- [x] @fluentui/react-badge #18746
- [x] @fluentui/react-button #18607
- [x] @fluentui/react-checkbox #19063 
- [x] @fluentui/react-card #19036 
- [x] @fluentui/react-components https://github.com/microsoft/fluentui/pull/19040#issuecomment-884132449
- [x] @fluentui/react-context-selector #18772
- [x] @fluentui/react-divider #18625 
- [x] @fluentui/react-image #18606
- [x] @fluentui/react-input #18781
- [x] @fluentui/react-link #18614
- [x] @fluentui/react-make-styles #18695
- [x] @fluentui/react-menu #18581
- [x] @fluentui/react-portal #18482 
- [x] @fluentui/react-positioning #18586
- [x] @fluentui/react-provider #18745
- [x] @fluentui/react-shared-contexts #18998
- [x] @fluentui/react-storybook https://github.com/microsoft/fluentui/pull/19037
- [x] @fluentui/react-tabster #18699
- [x] @fluentui/react-theme #18655
- [x] @fluentui/react-theme-provider #18710
- [x] @fluentui/react-tooltip #18977 
- [x] @fluentui/react-utilities #18794
- [x] @fluentui/react-popover https://github.com/microsoft/fluentui/pull/18623
- [x] @fluentui/react-label #18656 
- [x] @fluentui/react-text / NEW PACKAGE #18571 
- [x] @fluentui/react-aria / NEW PACKAGE #18550 

# How to migrate

1. execute migration generator
   - from CLI `yarn nx workspace-generator migrate-converged-pkg --name='@fluentui/<package-name>'`
   - via [NX console](https://marketplace.visualstudio.com/items?itemName=nrwl.angular-console) VSCode plugin
2. Apply any manual adjustments that might be needed. Check [ documentation](https://github.com/microsoft/fluentui/blob/master/tools/generators/migrate-converged-pkg/README.md) 
3. Create PR and make sure to add @microsoft/fluentui-react-build as reviewer to double check your changes 

# FAQ

## Why should I migrate my own/teams packages instead of one person doing the whole migration for me?

As we are in process of introducing new Dev Experience for how to approach migrations in general within monorepo, that could be implemented also for customers in the future, we wanna:
- get early feedback within the internal team
- show you gradual approach with less efforts (small focused PRs)
- distribute the knowledge about the new underlying tooling (nx) that we use within internal team 

## I wanna create new package, how should I proceed ?

- bootstrap new package via plop for convergence
- follow steps mentioned above 🙌

If you'll run into any issues while running the migration generator please open github issue.

Thank you and Happy migrating!

**Comment by Hotell** [comment]
all vNext and react-components suite has been migrated 🎉 excellent collaboration team !

**Comment by Hotell** [comment]
all vNext and react-components suite has been migrated 🎉 excellent collaboration team !
