### ISSUE TITLE
Slider Convergence

### ISSUE THREAD

**Issue by khmakoto** [microsoft/fluentui#18886]
# Preparation:

- [x] Started prep
- [x] Open UI Research complete
  - [link to https://open-ui.org/](https://open-ui.org/components/slider.research)
- [x] Comparison on v8 and v0 complete
- [x] Gather open GitHub issues related to component
- [x] react-slider package scaffolded
  - [link to the package](https://github.com/microsoft/fluentui/tree/master/packages/react-slider)
- [x] Slider Spec authored and reviewed
  - [link to Slider spec](https://github.com/microsoft/fluentui/blob/master/specs/Slider.md)
- [ ] **Deliverable:** Reviewed component spec

# Implementation

[link to the package](https://github.com/microsoft/fluentui/tree/master/packages/react-slider)

- [x] Started impl
- [x] Implement component
- [x] Add storybook stories
- [x] Using hooks
- [x] Using makeStyles
- [x] Respects Figma tokens (and using provider)
- [x] Respects API principles, shorthands and slots handling
- [x] No dependency on v0/v7
- [x] Add tests - Conformance, Unit, and VR
  - [x] Conformance tests
  - [x] Unit tests
  - [x] VR tests
  - [x] Accessibility behavior tests
- [x] Write README.md covering basic usage
- [x] Write initial MIGRATION.md guide (include v8 and v0)
- [x] Move utils to `react-utilities` package
- [x] Set component ownership in CODEOWNERS
- [ ] Add `RangedSlider`
- [ ] Add `useEvent` and `useCapture` and replace `on`
- [ ] Set the hidden input element to the primary slot
- [ ] **Deliverable:** Experimental component ready for partner use, component re-exported in `react-components`

# Future Investigation
- [ ] Investigate `restrictedValues`/`customSteps` [Example from Material](https://codesandbox.io/s/tgsxy?file=/demo.js)
- [ ] Investigate adding `tooltipVisible: boolean` without bloating the bundle size. An implementation with the prop (with a large bundle size) can be found here #19572
- [ ] Replace enzyme dragging tests with testing library #19977 
- [ ] Add `consistent-callback-args` conformance test back to RangedSlider.test #19978

# Validation

- [ ] Started validating
- [ ] Add and validate in UI Builder
- [ ] Add and validate in docs site
- [ ] Validate with token pipeline
- [ ] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods
- [ ] **Deliverable:** Preview component ready for broader/3rd party use

**Comment by behowell** [comment]
8-2 update - @czearing:
* Basic implementation is out in PR
* Updating styling, useSlider API
* Working on implementing marks

**Comment by behowell** [comment]
8-9 update @czearing 
* Spec is merged!
* Basic implementation merged!
* PRs out for vertical prop and disabled prop
* Working on step and snap functionality
  * Open questions about rounding and animations

**Comment by behowell** [comment]
8-16 update @czearing 
* Merged PRs for vertical (#19326), disabled (#19327), origin (#19370) props.
* PR out for marks & labels: #19397
* PR out for removing imperative API: #19401

**Comment by ecraig12345** [comment]
@czearing Some issues I noticed belatedly with `onChange`, while reviewing another PR:
- `onChange` should have type `(ev: React.PointerEvent<HTMLDivElement>, data: { value: number }) => void` as discussed in one of the RFCs. (If the event is sometimes not present, you can add `| undefined` to the type.)
- In `useSliderState`, the `onChangeCallback` ref is never being updated. After the ref is defined, you should add a line `onChangeCallback.current = onChange` to update it every render.
- Once you start updating the ref, the `updateValue` implementation won't need to directly reference `onChange`; instead it can just use the ref. (Same in `useMount`.)
https://github.com/microsoft/fluentui/blob/028f284f366b4bb57c2b254326464ce2dd403839/packages/react-slider/src/components/Slider/useSliderState.tsx#L77-L83

**Comment by behowell** [comment]
Closed inadvertently when a PR was merged

**Comment by micahgodbolt** [comment]
Going to re-open to help get this into RC
