### ISSUE TITLE
makeStyles: implement Webpack loader

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#18936]
### What?

One of `makeStyles` goals is to have ahead of time compilation. Currently we have only Babel plugin ([`@fluentui/babel-make-styles`](https://github.com/microsoft/fluentui/tree/master/packages/babel-make-styles)), that works great for our build pipeline, but has issues with apps.

### Problem

_Originally discussed there: https://github.com/microsoft/fluentui/issues/18489#issuecomment-872300638_

Our Babel plugin relies on evaluation to resolve style rules (we can't rely only on static evaluation, https://github.com/atlassian-labs/compiled/issues/723), this requires to run code in Node environment:

https://github.com/microsoft/fluentui/blob/c939e67b1840a9eb5f7706afcda8c14df8f18d33/packages/babel-make-styles/src/utils/evaluatePathsInVM.ts#L33-L35

But the plugin does not know about Webpack aliases that could be uses in apps 💣 To solve this issue Linaria (we are using evaluation part from `@linaria/shaker` & `@linaria/babel-preset`) has Webpack loaders (one of their goals is too pass down aliases):

https://github.com/callstack/linaria/blob/e92bcd93ed51b847cab0c9e3fa7c578328c1ddaf/packages/webpack5-loader/src/index.ts#L87-L96

### Actions

- [x] create a package #18905
- [x] bump Webpack to latest to get typings for `LoaderContext` #18919
- [x] implement Webpack loader #18918
- [x] integrate into existing pipeline for `vr-tests` #19065
- [x] add docs (README.md) #19065

### Blockers

- [x] https://github.com/callstack/linaria/issues/800
- [x] https://github.com/callstack/linaria/issues/804
- [x] https://github.com/callstack/linaria/issues/808
- [x] callstack/linaria#816

### Out of scope

Loader is implemented to solve aliases issue (https://github.com/microsoft/fluentui/issues/18489), CSS extraction is out of scope as it's a separate project due its complexity. It's complicated as we are using Atomic CSS while we should also support chunk splitting (https://github.com/atlassian-labs/compiled/pull/724) as classes are inserted in a special order it will require additional strategy to handle it.
