### ISSUE TITLE
Beta packaging: ship only implementation files

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#19103]
## Epic 📦

Implementation of  https://github.com/microsoft/fluentui/pull/19066 -  **1. `.npmignore` cleanup**

### Pre-requirements:
- [x] update migration generator with npm config changes (https://github.com/microsoft/fluentui/pull/19097)
- [x] implement `--all` flag to migration generator (https://github.com/microsoft/fluentui/pull/19101)
- [x] https://github.com/microsoft/fluentui/issues/18706 (https://github.com/microsoft/fluentui/pull/19108)
- [x] https://github.com/microsoft/fluentui/issues/19110 (TODO)
- [x] #19459
- [x] setup babel config based on context https://github.com/microsoft/fluentui/issues/19109 / https://github.com/microsoft/fluentui/pull/19399
- [x] trigger prompts dynamically (only when no flags are provided) for migration generator (https://github.com/microsoft/fluentui/pull/19151)

### Tasks:
- [ ] run migration generator with `--all` flag -> `yarn nx workspace-generator migrate-converged-pkg --all` / https://github.com/microsoft/fluentui/pull/19441

### Related issues
- https://github.com/microsoft/fluentui/issues/19042
