### ISSUE TITLE
storybook: Implement custom fluentui storybook addon

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#19252]
# Epic 📦

Storybook officially deprecated `addon-knobs` with 6.3 release.

We need to migrate our custom knobs and decorators from `@fluentui/react-storybook` package to new package which will re-implement our desired behaviour via custom addon.

This addon would be shipped to npm in the future to provide extended functionality to Storybook users with fluentui react

## Tasks
- [x] setup boilerplate / https://github.com/microsoft/fluentui/pull/19247
- [x] implement addon / https://github.com/microsoft/fluentui/pull/19250
- [x] replace `react-storybook` usage with our custom addon / https://github.com/microsoft/fluentui/pull/25786
- [x] remove  `react-storybook` package / https://github.com/microsoft/fluentui/pull/25786
- [ ] add test coverage
