### ISSUE TITLE
Card Convergence

### ISSUE THREAD

**Issue by andrefcdias** [microsoft/fluentui#19336]
# Preparation:

- [x] Started prep
- [x] Open UI Research complete
  - https://github.com/openui/open-ui/pull/134
  - https://open-ui.org/components/card.research
- [x] Comparison on v8 and v0 complete
- [x] Gather open GitHub issues related to component
  - v8
    - https://github.com/microsoft/fluentui/issues/19131
    - https://github.com/microsoft/fluentui/pull/17806
    - https://github.com/microsoft/fluentui/issues/17718
    - https://github.com/microsoft/fluentui/issues/11635
    - https://github.com/microsoft/fluentui/issues/5315
  - v0
    - https://github.com/microsoft/fluentui/issues/17952
  - vNext
    - https://github.com/microsoft/fluentui/issues/21649
- [x] react-\* package scaffolded
  - https://github.com/microsoft/fluentui/pull/19340
  - https://github.com/microsoft/fluentui/pull/19338
  - https://github.com/microsoft/fluentui/tree/master/packages/react-card
- [x] Component Spec authored and reviewed
  - https://github.com/microsoft/fluentui/pull/19410
  - https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-card/Spec.md
- [x] **Deliverable:** Reviewed component spec

# Implementation

https://github.com/microsoft/fluentui/tree/master/packages/react-card

- [x] Started impl
- [x] Implement component
  - https://github.com/microsoft/fluentui/pull/19646
  - https://github.com/microsoft/fluentui/pull/20030
  - https://github.com/microsoft/fluentui/pull/20132
  - https://github.com/microsoft/fluentui/pull/21685
  - https://github.com/microsoft/fluentui/pull/21264
  - https://github.com/microsoft/fluentui/pull/22312
  - https://github.com/microsoft/fluentui/pull/22915
  - https://github.com/microsoft/fluentui/pull/23037
  - https://github.com/microsoft/fluentui/pull/24486
  - https://github.com/microsoft/fluentui/pull/23410
  - https://github.com/microsoft/fluentui/pull/23449
  - https://github.com/microsoft/fluentui/pull/23902
- [x] Add storybook stories
  - https://github.com/microsoft/fluentui/pull/20051
  - https://github.com/microsoft/fluentui/pull/22451
  - https://github.com/microsoft/fluentui/pull/23841
- [x] Using hooks
- [x] Using makeStyles
- [x] Respects Figma tokens (and using provider)
- [x] Respects API principles, shorthands and slots handling
- [x] No dependency on v0/v7
- [x] Add tests - Conformance, Unit, and VR
  - [x] Bundle size fixtures
    - https://github.com/microsoft/fluentui/pull/20029
  - [x] Conformance tests
  - [x] Unit tests
  - [x] VR tests
    - [x] Prop tests
    - [x] Design templates added
  - [x] Accessibility behavior tests
- [x] Pending resolution
  - [x] https://github.com/microsoft/fluentui/issues/21909
- [x] Write README.md covering basic usage
  - https://github.com/microsoft/fluentui/pull/23888
- [x] Write MIGRATION guide (include v8 and v0)
  - https://github.com/microsoft/fluentui/issues/23981
  - https://github.com/microsoft/fluentui/issues/24020
- [x] Set component ownership in CODEOWNERS
- [x] **Deliverable:** Experimental component ready for partner use, component re-exported in `react-components`

# Validation

- [x] Started validating
- [x] Add and validate in UI Builder
- [x] Add and validate in docs site
- [x] Validate with token pipeline
- [x] Validate in product
- [x] Finalize migration guide
  - [x] Author codemods
- [x] **Deliverable:** Preview component ready for broader/3rd party use

**Comment by andrefcdias** [comment]
Tracking: https://github.com/microsoft/fluentui/issues/21649
