### ISSUE TITLE
vNext: use ES2016 or even later standard in tsconfigs target/lib

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#19367]
# Story 🧚‍♀️:

As vNext will not support IE11 and thus we will support only evergreen browsers, we can start using latest ECMA lang features. For now we decided to use `target: ES2015`/`lib: ['ES2015']` https://github.com/microsoft/fluentui/pull/19039

#### Actual behavior:

We are using ECMA lang features beyond ES2015. 
- `Array.prototype.includes` (ES2016)
-  TBA

#### Expected behavior:

- bump to `target/lib: ES2020`

## Tasks
- [x] update migration generator / https://github.com/microsoft/fluentui/pull/19398
- [ ] update all vNext pacakges by runnin `yarn nx workspace-generator migrate-converged-pkg --all`
- [ ] update just-scripts ts
   - vNext packages should consume their tsconfig instead of overrides used in just-scripts ts task

**Comment by ecraig12345** [comment]
ES2016 should definitely be fine at this point. Based on https://kangax.github.io/compat-table/es2016plus/ it looks like ES2019 should definitely be fine, and ES2020 would be fine unless we care about older Safari versions (tied to older macOS or iOS versions; but they'd have the option of using a different browser).

**Comment by Hotell** [comment]
discussed with the team and we agreed with following:

Lets go with ES2020. If we run into situation that we would need to fallback back to es2015 the effort of "back-porting" shouldn't be that difficult

**Comment by ecraig12345** [comment]
For reference in case anyone needs it, here's the compat info for legacy Edge for 2017/2018 (ignore the "Current browser" column).
![image](https://user-images.githubusercontent.com/5864305/129233344-80d2851f-c521-40aa-a005-b12f569caa46.png)

**Comment by Hotell** [comment]
thx a ton @ecraig12345 🙌

**Comment by ling1726** [comment]
Resolved in #20405
