### ISSUE TITLE
Switch Convergence

### ISSUE THREAD

**Issue by czearing** [microsoft/fluentui#19409]
# Preparation:

- [X] Started prep
- [x] Open UI Research complete
  - [https://open-ui.org/components/switch]
- [x] Comparison on v8 and v0 complete
- [x] Gather open GitHub issues related to component
- [x] react-slider package scaffolded
[link to react-slider package](https://github.com/microsoft/fluentui/blob/master/packages/react-switch)
- [x] Component Spec authored and reviewed
  - [link to react-slider spec](https://github.com/microsoft/fluentui/blob/master/packages/react-switch/Spec.md)
- [x] **Deliverable:** Reviewed component spec

# Implementation

[link to react-slider package](https://github.com/microsoft/fluentui/blob/master/packages/react-switch)

- [x] Implement component
- [x] Add storybook stories
- [x] Using hooks
- [x] Using makeStyles
- [x] Respects Figma tokens (and using provider)
- [x] Respects API principles, shorthands and slots handling
- [x] No dependency on v0/v7
- [x] Add tests - Conformance, Unit, and VR
  - [x] Bundle size fixtures
  - [x] Conformance tests
  - [x] Unit tests
  - [x] VR tests
  - [x] Accessibility behavior tests
- [x] Write README.md covering basic usage
- [x] Write initial MIGRATION.md guide (include v8 and v0)
- [x] Set component ownership in CODEOWNERS
- [ ] **Deliverable:** Experimental component ready for partner use, component re-exported in `react-components`

# Validation

- [ ] Started validating
- [ ] Add and validate in UI Builder
- [ ] Add and validate in docs site
- [ ] Validate with token pipeline
- [ ] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods
- [ ] **Deliverable:** Preview component ready for broader/3rd party use

**Comment by khmakoto** [comment]
Component is stable now, closing for now in favor of smaller issues if they come up in the future.
