### ISSUE TITLE
Implement primary slot/native props RFC

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#19868]
Implement RFC from #18983

- [x] Main implementation - @behowell - #20617
- [x] Update react-input
- [x] Update react-checkbox - @behowell - #20617
- [x] Update react-slider
- [ ] Update react-switch - #20590
