### ISSUE TITLE
Implement solution-style tsconfigs

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#19866]
### 🧚‍♀️ Story
Implement proposal from #19044

This ended up becoming more urgent to avoid needing excessive ts-ignores in stories. https://github.com/microsoft/fluentui/pull/19583#discussion_r709587568

**Tasks**
- [x] make migrate-converged-pkg up to date
   - [x]  https://github.com/microsoft/fluentui/pull/20386
   - [x] https://github.com/microsoft/fluentui/pull/20561
- [x] implement solution configuration within migrate-converged-pkg | https://github.com/microsoft/fluentui/pull/20478
- [x] redo how we build packages | https://github.com/microsoft/fluentui/pull/20515
- [x] run generator on whole codebase / or gradually ( need to be determined if that's really needed ) | https://github.com/microsoft/fluentui/issues/20597

**Optional Tasks:**
- [x] https://github.com/microsoft/fluentui/issues/20560 
- [x] enable multiple package migration in one run via `--name` https://github.com/microsoft/fluentui/pull/20583
- [x] update `--stats` to reflect ts solution config migration progress https://github.com/microsoft/fluentui/pull/20584

**Comment by Hotell** [comment]
closed by https://github.com/microsoft/fluentui/issues/20597
