### ISSUE TITLE
Radio Convergence

### ISSUE THREAD

**Issue by tringakrasniqi** [microsoft/fluentui#19953]
# Preparation:

- [ ] Started prep
- [ ] Open UI Research complete
  - https://open-ui.org/components/radio-button.research
- [ ] Comparison on v8 and v0 complete
- [ ] Gather open GitHub issues related to component
- [ ] react-\* package scaffolded
  - [link to package]
- [ ] Component Spec authored and reviewed
  - [link to spec in component package]
- [ ] **Deliverable:** Reviewed component spec

# Implementation

[link to react-* package folder]

- [ ] Started impl
- [ ] Implement component
- [ ] Add storybook stories
- [ ] Using hooks
- [ ] Using makeStyles
- [ ] Respects Figma tokens (and using provider)
- [ ] Respects API principles, shorthands and slots handling
- [ ] No dependency on v0/v7
- [ ] Add tests - Conformance, Unit, and VR
  - [ ] Bundle size fixtures
  - [ ] Conformance tests
  - [ ] Unit tests
  - [ ] VR tests
  - [ ] Accessibility behavior tests
- [ ] Write README.md covering basic usage
- [ ] Write initial MIGRATION.md guide (include v8 and v0)
- [ ] Set component ownership in CODEOWNERS
- [ ] **Deliverable:** Experimental component ready for partner use, component re-exported in `react-components`

# Validation

- [ ] Started validating
- [ ] Add and validate in UI Builder
- [ ] Add and validate in docs site
- [ ] Validate with token pipeline
- [ ] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods
- [ ] **Deliverable:** Preview component ready for broader/3rd party use

**Comment by gouttierre** [comment]
@behowell - I moved this Radio convergence epic to your project board as your team has taken ownership.

**Comment by khmakoto** [comment]
@micahgodbolt let's just close it and focus on more individual tasks instead of larger epics.
