### ISSUE TITLE
Tabs/Pivot Convergence

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/fluentui#20338]
# Preparation:

- [x] Started prep
- [x] Open UI Research complete
  - [link to https://open-ui.org/]
- [x] Comparison on v8 and v0 complete
- [ ] Gather open GitHub issues related to component
- [x] react-\* package scaffolded
  - [link to package]
- [ ] Component Spec authored and reviewed
  - [link to spec in component package]
- [ ] **Deliverable:** Reviewed component spec

# Implementation

[link to react-* package folder]

- [x] Started impl
- [x] Implement component
- [x] Add storybook stories
- [x] Using hooks
- [x] Using makeStyles
- [ ] Respects Figma tokens (and using provider)
- [x] Respects API principles, shorthands and slots handling
- [x] No dependency on v0/v7
- [ ] Add tests - Conformance, Unit, and VR
  - [ ] Bundle size fixtures
  - [x] Conformance tests
  - [x] Unit tests
  - [x] VR tests
  - [ ] Accessibility behavior tests
- [ ] Write README.md covering basic usage
- [ ] Write initial MIGRATION.md guide (include v8 and v0)
- [x] Set component ownership in CODEOWNERS
- [ ] **Deliverable:** Experimental component ready for partner use, component re-exported in `react-components`

# Validation

- [ ] Started validating
- [ ] Add and validate in UI Builder
- [ ] Add and validate in docs site
- [ ] Validate with token pipeline
- [ ] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods
- [ ] **Deliverable:** Preview component ready for broader/3rd party use
