### ISSUE TITLE
Project: Select and Combobox specs, Select implementation

### ISSUE THREAD

**Issue by smhigley** [microsoft/fluentui#20517]
## Problem

We need a selection widget for v9. A Combobox POC has been created, but needs to be updated based on the latest array slots vs. children discussion.

## Appetite

Weeks: 3

## Solution

Since the Fluent v8 Combobox, Dropdown, and Pickers all have the same semantics and much of the same functionality under the hood, it makes sense to combine them into a single Combobox component. At the same time, we have an opportunity to provide partners the option to take a much smaller bundle size along with better cross-platform compatibility, accessibility, and performance with a native `<select>` component.

- [ ] write Select spec
- [ ] write Combobox spec
- [ ] implement Select
- [ ] Update Combobox POC

## Risks (Rabbit holes)

- Primary slot implementation agreement
- Agreement over children-based approach for Combobox, requiring all Combobox children to consume the Combobox context's API

## Out of scope (No-gos)

A full Combobox implementation is out of scope for November

**Comment by smhigley** [comment]
## End of month retrospective

### What was achieved?
- Select spec is written
- Select implementation, minus styles
- Open UI research PR for Combobox names
- Plan for hammering out Combobox children/context communication

### What did we miss?
- Full select implementation
- Combo spec (depends on figuring out more of Combo children and working implementation first)

### What went well?
- So far agreement on Select vs Combobox/dropdown/whatever name split
- Adobe Spectrum has some interesting implementations for handling child ids and component-agnostic selection

### What could have gone better?
- Not a ton of reviews on Select spec -- should solicit more

### What changed from initial expectations?
- Combobox is still taking longer to iron out architecture than expected, partly just based on not having much time this month devoted to it
- After the Select spec/initial implementation was done, I heard that Combobox was a priority over Select, so it is still unfinished. However, since the only thing left is styling, it might be good to finish it first even though it is lower priority. Next month I think it would be a good idea to devote a day or two to adding styles and polishing it, then create a full PR for the component.
