### ISSUE TITLE
Project: Review and update slider control

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#20562]
## Problem

The Slider and Range Slider controls lack the polish required to consider them complete

#18886

## Appetite

Weeks

## Solution
There are a few areas of obvious polish to apply, and room for a more full review of the rest of the component code. The primary areas of focus will be:

1. Reduce the complexity of the DOM structure
2. Implement snap to points mode (consider this mode as default)
3. Revise markers approach
4. Update spec with changes

## Risks (Rabbit holes)

With range slider out of scope, we'll need to decide how to proceed once slider is completely. We either need to hold off on release until range slider is also done, or remove ranged slider for now and focus on single slider. 

Spending too much time refactoring styles....

## Out of scope (No-gos)

Current focus is on single thumb slider. Range slider will be reviewed separately.

**Comment by behowell** [comment]
Moving checklist from #20159:
  - [ ] primary slot
  - [ ] decide whether to ship or punt in November
  - [ ] general code/patterns review
  - [ ] remove RangedSlider from exports until it's ready (will finish it later)
  - [ ] docs

**Comment by micahgodbolt** [comment]
## Retro
PR has been live for a few weeks. Initially for some PR feedback, but then working to make it pass tests. In the process of evaluating tests we determined that events should be fired from the input element if possible. This lead to a plan to refactor eventing, removing custom events from root, and leveraging native events already on the input. This simplified code greatly but currently at the cost of smooth sliding. Next steps are 1) making sure that this smooth sliding is actually required by design and 2) seeing if there's a hybrid approach where thumb follows mouse until release when it snaps to input value.
