### ISSUE TITLE
migration: migrate converged packages to TS Solution style config

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#20597]
- Follows https://github.com/microsoft/fluentui/issues/18579
- Closes: 
   - https://github.com/microsoft/fluentui/issues/19866
   - partially https://github.com/microsoft/fluentui/issues/17101 

# Preparation:

- [x] nx migration generator implementation updates for TS Solution configs #19866

# What is this migration doing?
- **TypeScript:** 
  - transforms package TS setup to use TS Solution config files which will give us proper environment scoping and mitigate leaking of globals
  - resolves global `types` properly. Replaces `custom-globals` with `static-types`
- **Storybook:** 
  -  automatically removes any `@ts-ignore` pragma in stories, that was necessary because of our current setup limitation. With that you'll get proper DX and type safety when authoring stories.
- **Build/CI:** 
  - adds `type-check` command  that will properly check all package files against proper TS environment on CI.
  - build will transpile only implementation related files and will follow proper `target` down-leveling during transform (before everything was transpiled to ES5)
- **Testing:** 
   - checks if testing-library/jest-dom is being used and adjust typing setup for that
   - properly resolves e2e setup if present

# Packages to migrate:

- [x] @fluentui/babel-make-styles #20744
- [x] @fluentui/jest-serializer-make-styles #20747
- [x] @fluentui/keyboard-keys #20754
- [x] @fluentui/make-styles #20742
- [x] @fluentui/make-styles-webpack-loader #20757
- [x] @fluentui/react-accordion #20692
- [x] @fluentui/react-aria #20753
- [x] @fluentui/react-avatar #20843 
- [x] @fluentui/react-badge #20739
- [x] @fluentui/react-button #20846 
- [x] @fluentui/react-card - https://github.com/microsoft/fluentui/pull/20599
- [x] @fluentui/react-checkbox #20849 
- [x] @fluentui/react-components #20749
- [x] @fluentui/react-conformance-make-styles #20758
- [x] @fluentui/react-context-selector #20741
- [x] @fluentui/react-divider #20854
- [x] @fluentui/react-image - https://github.com/microsoft/fluentui/pull/20673
- [x] @fluentui/react-input #20880
- [x] @fluentui/react-label - https://github.com/microsoft/fluentui/pull/20851
- [x] @fluentui/react-link - https://github.com/microsoft/fluentui/pull/20855
- [x] @fluentui/react-make-styles #20728
- [x] @fluentui/react-menu #20692
- [x] @fluentui/react-popover #20692
- [x] @fluentui/react-portal #20692
- [x] @fluentui/react-positioning #20751
- [x] @fluentui/react-provider #20726
- [x] @fluentui/react-radio - https://github.com/microsoft/fluentui/pull/20675
- [x] @fluentui/react-shared-contexts #20725
- [x] @fluentui/react-slider - https://github.com/microsoft/fluentui/pull/20856
- [x] @fluentui/react-storybook - https://github.com/microsoft/fluentui/pull/20787
- [x] @fluentui/react-storybook-addon - https://github.com/microsoft/fluentui/pull/20797
- [x] @fluentui/react-switch - https://github.com/microsoft/fluentui/pull/20857
- [x] @fluentui/react-tabs (@GeoffCoxMSFT) - https://github.com/GeoffCoxMSFT/fluentui/commit/dfb50648a9aa24381891809bc9652404429519fa
- [x] @fluentui/react-tabster #20756
- [x] @fluentui/react-text - https://github.com/microsoft/fluentui/pull/20653
- [x] @fluentui/react-theme #20755
- [x] @fluentui/react-tooltip - https://github.com/microsoft/fluentui/pull/20858
- [x] @fluentui/react-utilities #20751

# How to migrate

> Make sure to check [generator docs](https://github.com/microsoft/fluentui/blob/master/tools/generators/migrate-converged-pkg/README.md) 

1. execute migration generator
   - from CLI:
     -  one package at a time `yarn nx workspace-generator migrate-converged-pkg --name='@fluentui/<package-name>'`
     -  multiple packages `yarn nx workspace-generator migrate-converged-pkg --name='@fluentui/<package-name>,@fluentui/<package-name-two>,@fluentui/<package-name-three>'`
   - via [NX console](https://marketplace.visualstudio.com/items?itemName=nrwl.angular-console) VSCode plugin
2. Create PR and make sure to add @microsoft/fluentui-react-build as reviewer to double check your changes
3. Add link to your PR to this Epic's particular package in list above

# FAQ

## Why should I migrate my own/teams packages instead of one person doing the whole migration for me?

As we are in process of introducing new Dev Experience for how to approach migrations in general within monorepo, that could be implemented also for customers in the future, we wanna:
- get feedback within the internal team
- show you gradual approach with less efforts (small focused PRs)
- distribute the knowledge about the new underlying tooling (nx) that we use within internal team 

## I wanna create new package, how should I proceed ?

1. bootstrap new package via plop for convergence
1. nx migration generator will be invoked automatically after plop

## How can I check status progress in latest master ?

```sh
# run generator with --stats
yarn nx workspace-generator migrate-converged-pkg --stats
```

---

If you'll run into any issues while running the migration generator please open github issue.

Thank you and Happy migrating!

**Comment by Hotell** [comment]
blocked by https://github.com/microsoft/fluentui/issues/20602

**Comment by ling1726** [comment]
Currently blocked by #20720

**Comment by Hotell** [comment]
> Currently blocked by #20720

temporary "solution/workaround" provided

**Comment by ling1726** [comment]
> > Currently blocked by #20720
> 
> temporary "solution/workaround" provided - [#20720 (comment)](https://github.com/microsoft/fluentui/issues/20720#issuecomment-976797901)

Yeah that workaround is good, thx 💪

**Comment by layershifter** [comment]
Currently following PRs are blocked:
- #20742
- #20744 
- #20747

**Comment by Hotell** [comment]
all vNext packages has been migrated 🙌. thanks everyone involved in this. YOU ARE AWESOME !
