### ISSUE TITLE
Project: Finish getting Input ready for RC

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#20936]
## Problem

Input is not ready for beta/RC.

Follow-up of #20159, part of #18131

## Appetite

1 week

## Solution

- [x] Implement primary slot (currently part of #20863)
- [x] Add `onChange` with standard signature (currently part of #20863)
- [x] Add docs (text) and stories #21072
- [x] Run manual accessibility test pass -- tracked by #21174
- [x] Export Input from react-components (possibly under unstable) #21142
  - [x] Remove Input from PR deploy site
- [ ] Write initial migration guide

## Risks (Rabbit holes)

- Getting hung up on discussion on small remaining decisions
- Unable to get reviews due to OOF (mitigation: try to finish ASAP before people leave)
