### ISSUE TITLE
SpinButton Convergence

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#20930]
# Preparation:

- [x] Started prep
- [x] Open UI Research complete
  - [link to https://open-ui.org/ SpinButton PR](https://github.com/openui/open-ui/pull/431)
- [x] Comparison on v8 and v0 complete
- [x] Gather open GitHub issues related to component
- [x] react-spinbutton package scaffolded
  - [link to package](https://github.com/microsoft/fluentui/tree/master/packages/react-spinbutton)
- [x] Component Spec authored and reviewed
  - [link to spec in component package](https://github.com/microsoft/fluentui/blob/master/packages/react-spinbutton/Spec.md)
- [x] **Deliverable:** Reviewed component spec

# Implementation

[link to react-spinbutton package folder](https://github.com/microsoft/fluentui/tree/master/packages/react-spinbutton)

- [x] Started impl
- [x] #21815
- [x] Add storybook stories
- [x] Using hooks
- [x] Using Griffle
- [x] Respects Figma tokens (and using provider)
- [x] Respects API principles, shorthands and slots handling
- [x] No dependency on v0/v7
- [x] Add tests - Conformance, Unit, and VR
  - [x] Bundle size fixtures
  - [x] Conformance tests
  - [x] Unit tests
  - [x] VR tests
  - [x] Accessibility behavior tests
- [x] Write README.md covering basic usage
- [x] Write initial MIGRATION.md guide (include v8 and v0)
- [x] Set component ownership in CODEOWNERS
- [x] **Deliverable:** Experimental component ready for partner use, component re-exported in `react-components`

# Validation

- [ ] Started validating
- [ ] Add and validate in UI Builder
- [ ] Add and validate in docs site
- [ ] Validate with token pipeline
- [ ] Validate in product
- [x] Finalize migration guide
  - [ ] Author codemods
- [ ] **Deliverable:** Preview component ready for broader/3rd party use

**Comment by spmonahan** [comment]
## Backlog issues related to `SpinButton`.

### Open Issues

1. https://github.com/microsoft/fluentui/issues/21459 -- a11y relationship between increment and decrement buttons
2. https://github.com/microsoft/fluentui/issues/18405 -- Narrator issue with aria-valuetext

### Closed Issues

1. https://github.com/microsoft/fluentui/issues/19373 -- defaultValue edge cases
2. https://github.com/microsoft/fluentui/issues/18782 -- onChange event handling differences between v7 and v8.
3. https://github.com/microsoft/fluentui/issues/18153 -- onChange event handling
4. https://github.com/microsoft/fluentui/issues/13606 -- VoiceOver accessibility issues
5. https://github.com/microsoft/fluentui/issues/11358 -- min/max values
6. https://github.com/microsoft/fluentui/issues/5326 -- on adding an onChange handler
7. https://github.com/microsoft/fluentui/issues/3339 -- on adding the `precision` prop to handle rounding errors
8. https://github.com/microsoft/fluentui/issues/2503 -- on committing values in the SpinButton

**Comment by 1muen** [comment]
There is also no `required` or `errorMessage` property on the SpinButton :( This was already reported in # [SpinButton] Add errorMessage and onGetErrorMessage #11923 or https://github.com/microsoft/fluentui/issues/3620

**Comment by spmonahan** [comment]
The converged inputs like this SpinButton implementation support all the native `HTMLInputElement` attributes so there is a `required` property. Error messaging for inputs will be handled by a different control for this version of the library.
