### ISSUE TITLE
Dialog Convergence

### ISSUE THREAD

**Issue by varholak-peter** [microsoft/fluentui#20953]
# Preparation:

- [x] Started prep
- [x] Open UI Research complete
  - [Dialog OpenUI](https://open-ui.org/components/dialog.research)
- [x] Comparison on v8 and v0 complete
- [x] Gather open GitHub issues related to component
  v8:
#21859
#20988
#20285
#19766
#19610   
#19593
#19143
#12081
v7:
#19860
- [x] react-\* package scaffolded
  - [react-dialog](https://github.com/microsoft/fluentui/tree/master/packages/react-dialog)
- [x] Component Spec authored and reviewed
  - #21992 
- [x] **Deliverable:** Reviewed component spec

# Implementation

[link to react-* package folder]

- [x] Started impl https://github.com/microsoft/fluentui/pull/23933
- [x] Implement component https://github.com/microsoft/fluentui/pull/23933
- [x] Add storybook stories
- [x] Using hooks https://github.com/microsoft/fluentui/pull/23933
- [x] Using makeStyles https://github.com/microsoft/fluentui/pull/23933
- [x] Respects Figma tokens (and using provider)
- [x] Respects API principles, shorthands and slots handling https://github.com/microsoft/fluentui/pull/23933
- [x] No dependency on v0/v7
- [x] Add tests - Conformance, Unit, and VR
  - [x] Bundle size fixtures
  - [x] Conformance tests (TODO: https://github.com/microsoft/fluentui/issues/21670)
  - [x] Unit tests
  - [x] VR tests https://github.com/microsoft/fluentui/pull/24978
  - [x] Accessibility behavior tests
- [x] Write README.md covering basic usage
- [ ] Write initial MIGRATION.md guide (include v8 and v0)
- [x] Set component ownership in CODEOWNERS
- [x] **Deliverable:** Experimental component ready for partner use, component re-exported in `react-components`

# Validation

- [x] Started validating
- [ ] Add and validate in UI Builder
- [ ] Add and validate in docs site
- [ ] Validate with token pipeline
- [ ] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods
- [ ] **Deliverable:** Preview component ready for broader/3rd party use

**Comment by layershifter** [comment]
@bsunderhus is there an issue to implement scroll lock in `Dialog`? (something like https://github.com/theKashey/react-remove-scroll)

**Comment by bsunderhus** [comment]
There isn't at the moment, we could track this possibility! @jurokapsiar , would that be a desirable behaviour for our partners to include in `Dialog`

**Comment by layershifter** [comment]
> > @bsunderhus is there an issue to implement scroll lock in `Dialog`? (something like https://github.com/theKashey/react-remove-scroll)
> 
> There isn't at the moment, we could track this possibility! @jurokapsiar

FYI: We have it in v0 (https://fluentsite.z22.web.core.windows.net/0.63.0/components/dialog/definition) so it's about feature parity.

**Comment by bsunderhus** [comment]
> > > @bsunderhus is there an issue to implement scroll lock in `Dialog`? (something like https://github.com/theKashey/react-remove-scroll)
> > 
> > 
> > There isn't at the moment, we could track this possibility! @jurokapsiar
> 
> FYI: We have it in v0 (https://fluentsite.z22.web.core.windows.net/0.63.0/components/dialog/definition) so it's about feature parity.

https://github.com/microsoft/fluentui/issues/24355
