### ISSUE TITLE
chore: adopt single version policy for monorepo dependencies

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#21395]
# Story 🧚‍♀️

#### Actual behavior:

Currently every packages includes exact same list of devDependencies/

```json
"devDependencies": {
    "@fluentui/babel-make-styles": "9.0.0-beta.4",
    "@fluentui/eslint-plugin": "*",
    "@fluentui/jest-serializer-make-styles": "9.0.0-beta.4",
    "@fluentui/react-conformance": "*",
    "@fluentui/react-conformance-make-styles": "9.0.0-beta.4",
    "@fluentui/scripts": "^1.0.0",
    "@types/enzyme": "3.10.3",
    "@types/enzyme-adapter-react-16": "1.0.3",
     "@types/react-test-renderer": "^16.3.0",
    "@types/react": "16.9.42",
    "@types/react-dom": "16.9.10",
    "enzyme": "~3.10.0",
    "enzyme-adapter-react-16": "^1.15.0",
    "react": "16.8.6",
    "react-dom": "16.8.6",
    "react-test-renderer": "^16.3.0"
  },
```

#### Expected behavior:

All devDependencies should adhere to "single version policy in monorepo". [Why ?](https://opensource.google/documentation/reference/thirdparty/oneversion) 
- every devDependency is defined in root `package.json`
  - TBD: use pinned version to align with yarn.lock ( this might be detrimental in terms of modules de-dupe though)  
- if package really needs to opt out, it will specify different version of devDependency within its package.json to prevent hoisting. (this should be only last resort and for temporary time period )

#### Tasks
- [ ] write migration  https://github.com/microsoft/fluentui/pull/26437
- [ ] migrate to lastest syncpack
- [ ] update existing plol generator
- [ ] execute migration in batch
- [ ] add lint checks to prevent violations

#### Related issues
- https://github.com/microsoft/fluentui/issues/20799
- https://github.com/microsoft/fluentui/pull/19799

**Comment by Hotell** [comment]
## Exceptions:

### stylis

`react-northstar` is using v3 while `@fluentui/react-northstar-emotion-renderer` is on v4. Because[ performance downgrade in v4](https://github.com/microsoft/fluentui/pull/13310) there are no plans to migrate `react-northstar` to v4


### react

whole monorepo is using react v17 ATM. to be able to verify fluent compatibility on newer version we also have React 18 within 2 apps as dependency, thus those can't/won't be normalized to SVP.

### ~tslib~

web-components are on old tslib v1. The reasoning behind was that some OSS folks on FAST were using Typescript v3.9. we can bump to v2 and unify tslib version ✅
