### ISSUE TITLE
Toolbar convergence

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#21533]
# Preparation:

- [ ] Started prep
- [x] Open UI Research complete
  - https://github.com/openui/open-ui/pull/452
- [ ] Comparison on v8 and v0 complete
- [ ] Gather open GitHub issues related to component
- [ ] react-\* package scaffolded
  - [link to package]
- [ ] Component Spec authored and reviewed
  - [link to spec in component package]
- [ ] **Deliverable:** Reviewed component spec

# Implementation

[link to react-* package folder]

- [ ] Started impl
- [ ] Implement component
- [ ] Add storybook stories
- [ ] Using hooks
- [ ] Using makeStyles
- [ ] Respects Figma tokens (and using provider)
- [ ] Respects API principles, shorthands and slots handling
- [ ] No dependency on v0/v7
- [ ] Add tests - Conformance, Unit, and VR
  - [ ] Bundle size fixtures
  - [ ] Conformance tests
  - [ ] Unit tests
  - [ ] VR tests
  - [ ] Accessibility behavior tests
- [ ] Write README.md covering basic usage
- [ ] Write initial MIGRATION.md guide (include v8 and v0)
- [ ] Set component ownership in CODEOWNERS
- [ ] **Deliverable:** Experimental component ready for partner use, component re-exported in `react-components`

# Validation

- [ ] Started validating
- [ ] Add and validate in UI Builder
- [ ] Add and validate in docs site
- [ ] Validate with token pipeline
- [ ] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods
- [ ] **Deliverable:** Preview component ready for broader/3rd party use

**Comment by paulgildea** [comment]
I'm assuming this one is done?
