### ISSUE TITLE
fluentui-react-upgrade: Feb sprint work tracking

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/fluentui#21593]
Because the upgrade work is on a separate board, this helps track the work for @microsoft/cxe-coastal

Feb 2022 planned:
- [x] [Create v9 theme that looks like v8 #10](https://github.com/microsoft/fluentui-react-upgrade/issues/10)
- [x] [Document how to write shims #12](https://github.com/microsoft/fluentui-react-upgrade/issues/10)
- [x] [Create Button shim(s) #7](https://github.com/microsoft/fluentui-react-upgrade/issues/7)
- [x] [Create v8 theme that looks like v9 #9](https://github.com/microsoft/fluentui-react-upgrade/issues/9)
