### ISSUE TITLE
Rewrite react-conformance API to be more extensible/modular

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#21665]
The API of `@fluentui/react-conformance` was designed with the intent of being extensible, but it's not a very good design. Also, it has the issue today of including tests in the core package that are actually specific to v8/v9/v0 (which can cause dependency graph issues and is generally unhelpful) and introducing enzyme+node types into the global namespace anywhere it's imported.

The new API will probably look something like this, inspired by babel:
```js
isConformant({
  componentPath: '',
  presets: [
    // these will probably support a standard 'exclude' argument to disable rules
    basePreset({ /* strictly typed config options */ }),
    griffelPreset(),
  ],
  // possibly also 'plugins'/'rules' but this could maybe be combined with presets
})
```

This will be a **breaking change** to the conformance package. ~~To help stage it, we may temporarily stop publishing the package (allowing all the breaking changes to be released together when ready).~~ react-conformance is still 0.x, meaning we can break things in minors. We might release 1.0 once the refactor is done.

Conversion from enzyme to testing-library (#21663) will probably be done at the same time since it affects the public API.

## Work items

- [x] #21700 - reducing amount of complex old logic that needs to be ported
- [x] #22009 - could have been done either before or after refactoring, but nice to get it out of the way (also to get rid of global leakage from enzyme)
- [ ] simplify error message handling?
- [ ] figure out new API and implement types
- [ ] port all tests to new API
- [ ] release 1.0
- [ ] other/sub items...? TBD

## Related items
- #19697
