### ISSUE TITLE
Improve Perf-Test Pipeline Speed

### ISSUE THREAD

**Issue by TristanWatanabe** [microsoft/fluentui#21697]
## ISSUE: 
The perf-test pipeline currently builds and runs perf tests for both `@fluentui/react` (via `app/perf-test`) and `@fluentui/react-northstar` (via `packages/fluentui/perf-test-northstar`) regardless if their respective packages were affected by a change or not. To improve pipeline speeds, the perf-test of the affected package should be the only one that builds and runs: i.e. if a PR only makes changes that affect the `@fluentui/react` package, only its `perf-test` should run and vice versa. Changes that affect the entire repo such as tooling should still run both. 

Furthermore, `app/perf-test` currently has both v8 and vNext tests which unnecessarily extends the pipeline duration as both packages have to be built. This should be untangled and vNext perf tests should live in its own package (i.e: app/perf-test-react-components).

## SOLUTION STEPS:
- [x] Modify pipeline to only build and run the specific perf test package depending on which library is affected by a PR : #21770
- [x] Extract vNext perf tests from `app/perf-test` and move to its own package (`app/perf-test-react-components`). Also remove all vNext dependencies from `app/perf-test`: #21873
- [x] Incorporate new vNext perf-test package to the pipeline: #21873
