### ISSUE TITLE
Input Convergence Coherence

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#21809]
As part of the RC process for input components we want to review the APIs for all the converged input controls to ensure we present a consistent API across these controls so users can learn how to use one input control and apply those learnings to all other input controls.

Review the APIs for all converged input controls (i.e., v9 controls) and document where the APIs diverge in naming or approach to problem solving. Some examples of divergence:

1. One control has a prop called `inputValue` while another has `value`.
2. One control takes a `formatter` function prop to format values internally while another takes a string `formattedValue` prop and simply displays the formatted value.
3. The component name diverges from ARIA names: `Radio` and `RadioItem` instead of the ARIA `RadioGroup` and `Radio`.

If you're unsure if something counts, include it so it is discussed.

## List of Controls to Review

- [x] [react-button](https://github.com/microsoft/fluentui/tree/master/packages/react-button)
- [x] [react-checkbox](https://github.com/microsoft/fluentui/tree/master/packages/react-checkbox)
- [x] [react-combobox](https://github.com/microsoft/fluentui/tree/master/packages/react-combobox)
- [x] [react-dropdown](https://github.com/microsoft/fluentui/tree/master/packages/react-dropdown)
- [x] [react-input](https://github.com/microsoft/fluentui/tree/master/packages/react-input)
- [x] [react-radio](https://github.com/microsoft/fluentui/tree/master/packages/react-radio)
- [x] [react-select](https://github.com/microsoft/fluentui/tree/master/packages/react-select)
- [x] [react-slider](https://github.com/microsoft/fluentui/tree/master/packages/react-slide)
- [x] [react-spinbutton](https://github.com/microsoft/fluentui/tree/master/packages/react-spinbutton)
- [x] [react-switch](https://github.com/microsoft/fluentui/tree/master/packages/react-switch)

## Acceptance Criteria

1. [x] Review all input components and note differences in comments on this issue
2. [x] Based on the review, propose a coherent API to be used by all input components
    1. [x] Review with the team and get buy in
3. [x] Create one issue per component that details the necessary changes for the component API and assign the issue to the component CODEOWNER

**Comment by spmonahan** [comment]
Notable differences between controls:

1. Not all controls make the `root` slot `NonNullable`
2. Not all controls apply `className` to all slots per #21206 
3. `Checkbox` and `Radio` include labels in contrast to all other input controls that explicitly exclude them.
    1. This is an intentional exception
4. The `onChange` event handler function does not have a consistent signature.
    1. Sometimes the event type is `React.ChangeEvent`, other times `React.FormEvent`
    2. Sometimes it takes a second arguement, `<ControlName>OnChangeData`, somtimes not.
5. Some controls set a default `id` value via `useId()` others do not.
6. Some controls expose an API to control whether they are a `block` item or an `inline` one.
    1. In some cases this prop is called `inline` in other cases it is called `block`.
    2. Some controls default to `inline` while others default to `block`
    3. Others provide no direct API for this (though it can be achieved by customizing styles)
7. Some controls style via CSS pseudo-classes which cuts down on React renders.
    1.  See: [Refactor Checkbox styles to use CSS pseudo-classes by behowell · Pull Request #21837 · microsoft/fluentui (github.com)](https://github.com/microsoft/fluentui/pull/21837)
8. Some controls have wrapper elements (i.e., a wrapper `<div>` for layout purposes) in their render functions. These elements are not exposed via the Slots API. Most do not have this.
9. `SpinButton` and `Slider` both expose "imperative" APIs meaning they take in functions via props to do some work. In the case of `Slider` this is `getAriaValueText` which is a function to format values for accessibility purposes. `SpinButton` has a similar API via `parser` and `formatter` which are complementary functions displaying values in `SpinButton`s.
    1. One line of thought here is that this is preferable as it allows these components to offer parity between controlled and uncontrolled variants for basic use cases.
    2. A different thought is that we should strive for our APIs to be declarative -- users tell the components what to display via props.

**Comment by spmonahan** [comment]
## Proposed API Changes

1. Root slots of all controls are `NonNullable`
2. All slots must have `fui-*` `className` applied per #21206
3. Drop all `inline` and `block` props.
    1. The default styling for native input controls is `inline-block`. To be consistent with this make all controls `inline-block` elements (either `display: inline-block` or `display: inline-flex`). 
    2. Input controls can be laid out via the parent containers with Flexbox or CSS Grid so the controls themselves should not offer APIs to alter their layout properties.
    3. If a user needs this feature it can be achieved by customizing the controls' styles
4. Prefer string union props over boolean props.
    1. While more verbose to write string union props are more extensible and (subjectively) are more readable in JSX.
5. Make the signature of the `onChange` event handler consistent.
    1. Signature should be `onChange(ev: React.ChangeEvent<HTMLInputElement>, data: ControlOnChangeData)`
    2. `ControlOnChangeData` is a type defined per-control (e.g., `CheckboxOnChangeData` for `Checkbox`) that contains relevant data for the change event.
    3. **Possible Exception:** Changes to `SpinButton` can be triggered through mouse clicks and keyboard events so it may require a different type. Need some discussion here.
6. Update wrapper elements in `render*` functions
    1. Ideally remove these elements entirely
    2. Promote them to slots if they are required

**Comment by spmonahan** [comment]
## Proposed Internal Implementation Changes

1. Use CSS pseudo-classes for styling when available. See #21837 .

**Comment by spmonahan** [comment]
## Proposed Documentation Changes

1. Refer to components as proper nouns (so write about them like you would people). Ex: "The root element of Switch" not "The root element of the Switch"

**Comment by ecraig12345** [comment]
For onChange handlers we agreed they should all have a second argument `____OnChangeData`
https://github.com/microsoft/fluentui/blob/master/rfcs/react-components/convergence/event-handlers-arguments.md#addendum-all-inputs-should-expose-a-customized-onchange-handler

**Comment by spmonahan** [comment]
Issues created!

- #21926 
- #21927 
- #21928 
- #21929 
- #21930
