### ISSUE TITLE
Textarea Convergence 

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#21845]
# Preparation:

- [x] Started prep
- [x] Open UI Research complete
  - [link to https://open-ui.org/]
- [x] Comparison on v8 and v0 complete
- [x] Gather open GitHub issues related to component
- [x] react-\* package scaffolded
  - https://github.com/microsoft/fluentui/tree/master/packages/react-textarea
- [x] Component Spec authored and reviewed
  - https://github.com/microsoft/fluentui/blob/master/packages/react-textarea/Spec.md
  - https://github.com/microsoft/fluentui/pull/21898
- [x] **Deliverable:** Reviewed component spec

# Implementation

[react-textarea package](https://github.com/microsoft/fluentui/tree/master/packages/react-textarea)

- [x] Started impl
- [x] Implement component
  - #22096 
- [x] Add storybook stories
- [x] Using hooks
- [x] Using makeStyles
- [x] Respects Figma tokens (and using provider)
- [x] Respects API principles, shorthands and slots handling
- [x] No dependency on v0/v7
- [x] Add tests - Conformance, Unit, and VR
  - [x] Bundle size fixtures #22272
  - [x] Conformance tests
  - [x] Unit tests
  - [x] VR tests #22296
  - [x] Accessibility behavior tests #22345
- [x] Write README.md covering basic usage
- [x] Write initial MIGRATION.md guide (include v8 and v0)
- [x] Set component ownership in CODEOWNERS
- [x] **Deliverable:** Experimental component ready for partner use, component re-exported in `react-components`

# Validation

- [ ] Started validating
- [ ] Add and validate in UI Builder
- [ ] Add and validate in docs site
- [ ] Validate with token pipeline
- [ ] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods
- [ ] **Deliverable:** Preview component ready for broader/3rd party use

**Comment by sopranopillow** [comment]
### Backlog of things to fix in the future (not all will be addressed)

- [ ] Use a css selector (`:has()` probably once it's supported) to style the wrapper with mostly css selectors.
  - Reference: [comment.](https://github.com/microsoft/fluentui/pull/22096#discussion_r827316570)
