### ISSUE TITLE
AvatarGroup/AvatarGroupItem convergence

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#22240]
# Preparation:

- [x] Started prep
- [x] Open UI Research complete
- [x] Comparison on v8 and v0 complete
- [x] Gather open GitHub issues related to component
- [x] react-\* package scaffolded
  - [react-avatar](https://github.com/microsoft/fluentui/tree/master/packages/react-components/react-avatar)
- [x] Component Spec authored and reviewed
  - #22523
- [x] **Deliverable:** Reviewed component spec

# Implementation

[link to react-* package folder]

- [x] Started implementation
- [x] Implement component:
  - #22736
  - #23310
- [x] Add storybook stories #23493
- [x] Using hooks
- [x] Using makeStyles
- [x] Respects Figma tokens (and using provider)
- [x] Respects API principles, shorthands and slots handling
- [x] No dependency on v0/v7
- [x] Add tests - Conformance, Unit, and VR
  - [x] Bundle size fixtures
  - [x] Conformance tests
  - [x] Unit tests
  - [x] VR tests
  - [x] Accessibility behavior tests
    - #23773   
- [x] Write README.md covering basic usage
- [x] Write initial MIGRATION.md guide (include v8 and v0)
- [x] Set component ownership in CODEOWNERS
- [x] **Deliverable:** Experimental component ready for partner use, component re-exported in `react-components`
  - #23573 

# Validation

- [x] Started validating
- [ ] Add and validate in UI Builder
- [x] Add and validate in docs site
- [ ] Validate with token pipeline
- [x] Validate in product
- [x] Finalize migration guide
  - [x] Update README for Avatar and AvatarGroup to a single file: see [issue](https://github.com/microsoft/fluentui/pull/23758#pullrequestreview-1022553382)
  - [ ] Author codemods
- [x] **Deliverable:** Preview component ready for broader/3rd party use
  - #25005

**Comment by sopranopillow** [comment]
Closing as this component has moved to stable
