### ISSUE TITLE
group vNext to common folder (as people will start check vNext)

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#22427]
## Story 🧚‍♀️:

prior to v9 stable we need to reshuffle our monorepo so it's more accessible to contributors

### Tasks:
- [x] RFC proposal with that will describe new repo structure: #22460 
- [x] create migration generator to move project ( there is already @nrwl/workspace:move generator that should be used as a foundation): #22506
- [x] move projects to new common folder gradually/in batch
  - [x] react-components: #22557 
  - [x] react-avatar, react-button, react-checkbox: #22644 
  - [x] react-select, react-slider, react-tabs: #22647
  - [x] react-menu, react-popover, react-portal: #22655
  - [x] react-card, react-dialog, react-image: #22692 
  - [x] react-text, react-storybook, react-storybook-addon: #22693 
  - [x] react-input, react-label, react-link: #22694
  - [x] react-provider, react-list, react-toolbar: #22695 
  - [x] react-positioning, react-utilities, react-theme: #22709
  - [x] react-aria, react-alert, react-tabster: #22710 
  - [x] react-spinbutton, react-spinner, react-tooltip: #22756
  - [x] keyboard-keys, priority-overflow, react-overflow: #22790 
  - [x] react-portal-compat-context, react-context-selector, react-conformance-griffel: #22792
  - [x] react-radio, react-switch, react-textarea: #22802
  - [x]  react-portal-compat: #22829 
  - [x] react-accordion, react-divider: #22827 
  - [x] react-combobox: #22830 
  - [x] react-badge: #22890
  - [x] react-shared-contexts https://github.com/microsoft/fluentui/pull/22896
- [x] Update the `create-package` script and `migrate-converged-pkg` generator: #22654
