### ISSUE TITLE
ship rolluped  declaration files only

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#22429]
## Story 🧚‍♀️

Follows https://github.com/microsoft/fluentui/issues/20287#issuecomment-1084557082

#### Actual behavior:

We currently ship all declaration files for packages which create following following issues:
- we allow consumers to access private API's with ease by providing intellisense 
- we leak private typings/TS type constructs from 3rd party and internal libraries that might contain TS features not supported in our particular minbar for TS support

#### Expected behavior:

- types are shipped only as a rolluped type definition

## Tasks
- [x] RFC / https://github.com/microsoft/fluentui/pull/22469
- [x] Update Generator and tooling / https://github.com/microsoft/fluentui/pull/22663
- [x] migrate v9 packages / gradual migration started on 29th of April
  - [x] @fluentui/react-components | https://github.com/microsoft/fluentui/pull/22746
  - [x] @fluentui/react-accordion | https://github.com/microsoft/fluentui/pull/23061
  - [x] @fluentui/react-badge | https://github.com/microsoft/fluentui/pull/23053
  - [x] @fluentui/react-combobox | https://github.com/microsoft/fluentui/pull/23061
  - [x] @fluentui/react-divider | https://github.com/microsoft/fluentui/pull/23061
  - [x] @fluentui/react-shared-contexts | https://github.com/microsoft/fluentui/pull/22965
  - [x] @fluentui/keyboard-keys | https://github.com/microsoft/fluentui/pull/22823
  - [x] @fluentui/priority-overflow | https://github.com/microsoft/fluentui/pull/22823  
  - [x] @fluentui/react-alert | https://github.com/microsoft/fluentui/pull/22823
  - [x] @fluentui/react-aria | https://github.com/microsoft/fluentui/pull/22823
  - [x] @fluentui/react-avatar | https://github.com/microsoft/fluentui/pull/22823
  - [x] @fluentui/react-button | https://github.com/microsoft/fluentui/pull/22823
  - [x] @fluentui/react-conformance-griffel | https://github.com/microsoft/fluentui/pull/22823
  - [x] @fluentui/react-context-selector | https://github.com/microsoft/fluentui/pull/22823
  - [x] @fluentui/react-card | https://github.com/microsoft/fluentui/pull/22708
  - [x] @fluentui/react-dialog | https://github.com/microsoft/fluentui/pull/22708
  - [x] @fluentui/react-image | https://github.com/microsoft/fluentui/pull/22708
  - [x] @fluentui/react-text | https://github.com/microsoft/fluentui/pull/22708
  - [x] @fluentui/react-input | https://github.com/microsoft/fluentui/pull/22793
  - [x] @fluentui/react-checkbox | https://github.com/microsoft/fluentui/pull/22793
  - [x] @fluentui/react-label | https://github.com/microsoft/fluentui/pull/22793
  - [x] @fluentui/react-link | https://github.com/microsoft/fluentui/pull/22793
  - [x] @fluentui/react-select | https://github.com/microsoft/fluentui/pull/22793
  - [x] @fluentui/react-list | https://github.com/microsoft/fluentui/pull/22791
  - [x] @fluentui/react-menu | https://github.com/microsoft/fluentui/pull/22791
  - [x] @fluentui/react-popover | https://github.com/microsoft/fluentui/pull/22791
  - [x] @fluentui/react-portal | https://github.com/microsoft/fluentui/pull/22791
  - [x] @fluentui/react-provider | https://github.com/microsoft/fluentui/pull/22791
  - [x] @fluentui/react-toolbar | https://github.com/microsoft/fluentui/pull/22791
  - [x] @fluentui/react-portal-compat-context | https://github.com/microsoft/fluentui/pull/22828
  - [x] @fluentui/react-positioning | https://github.com/microsoft/fluentui/pull/22828
  - [x] @fluentui/react-overflow | https://github.com/microsoft/fluentui/pull/22828
  - [x] @fluentui/react-portal-compat | https://github.com/microsoft/fluentui/pull/22874
  - [x] @fluentui/react-radio | https://github.com/microsoft/fluentui/pull/22874
  - [x] @fluentui/react-switch | https://github.com/microsoft/fluentui/pull/22874
  - [x] @fluentui/react-textarea | https://github.com/microsoft/fluentui/pull/22874
  - [x] @fluentui/react-slider | https://github.com/microsoft/fluentui/pull/22828
  - [x] @fluentui/react-spinbutton | https://github.com/microsoft/fluentui/pull/22828
  - [x] @fluentui/react-spinner | https://github.com/microsoft/fluentui/pull/22828
  - [x] @fluentui/react-storybook | https://github.com/microsoft/fluentui/pull/22828
  - [x] @fluentui/react-storybook-addon | https://github.com/microsoft/fluentui/pull/22828
  - [x] @fluentui/react-tabs | https://github.com/microsoft/fluentui/pull/22828
  - [x] @fluentui/react-tabster | https://github.com/microsoft/fluentui/pull/22828
  - [x] @fluentui/react-theme | https://github.com/microsoft/fluentui/pull/22828
  - [x] @fluentui/react-tooltip | https://github.com/microsoft/fluentui/pull/22828
  - [x] @fluentui/react-utilities | https://github.com/microsoft/fluentui/pull/22828

### Pre-requisite 

You can execute the migration only if your package has been migrated to `react-components` folder:

- [x] https://github.com/microsoft/fluentui/issues/22427

1. one at a time
`yarn workspace-generator migrate-converged-pkg --name @fluentui/react-menu`

2. multiple at a time
`yarn workspace-generator migrate-converged-pkg --name @fluentui/react-menu,@fluentui/react-text,@fluentui/react-button`

**Comment by TristanWatanabe** [comment]
Closing as all v9 packages have been migrated!
