### ISSUE TITLE
MessageBar

### ISSUE THREAD

**Issue by rohitpagariya** [microsoft/fluentui#22579]
# Preparation:

- [x] Started prep
- [ ] Open UI Research complete
  - [link to https://open-ui.org/]
- [x] Comparison on v8 and v0 complete
- [x] Gather open GitHub issues related to component
- [x] react-\* package scaffolded
  - [link to package]
- [ ] Component Spec authored and reviewed
  - [link to spec in component package]
- [ ] **Deliverable:** Reviewed component spec

# Implementation

[link to react-* package folder]

- [x] Started impl
- [x] Implement component
- [x] Add storybook stories
- [x] Using hooks
- [x] Using makeStyles
- [x] Respects Figma tokens (and using provider)
- [x] Respects API principles, shorthands and slots handling
- [x] No dependency on v0/v7
- [x] Add tests - Conformance, Unit, and VR
  - [x] Bundle size fixtures
  - [x] Conformance tests
  - [x] Unit tests
  - [x] VR tests
  - [x] Accessibility behavior tests
- [x] Write README.md covering basic usage
- [ ] Write initial MIGRATION.md guide (include v8 and v0)
- [x] Set component ownership in CODEOWNERS
- [x] **Deliverable:** Experimental component ready for partner use, component re-exported in `react-components`

# Validation

- [x] Started validating
- [ ] Add and validate in UI Builder
- [x] Add and validate in docs site
- [x] Validate with token pipeline
- [ ] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods
- [x] **Deliverable:** Preview component ready for broader/3rd party use

**Comment by gouttierre** [comment]
Shipped! Check it out [here ](https://react.fluentui.dev/?path=/docs/components-messagebar--default)
