### ISSUE TITLE
React 18 Consumption Epic

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#22592]
This epic will start tracking the work involved for
- Consumption in React 18 projects

## Consumption issues found

Fluent UI 9

- [x] #23872
- [x] https://github.com/microsoft/fluentui/issues/23625
- [x] Ensure that useInsertionEffect works properly in CRA and Emotion
- [ ] #24085 
- [ ] #24973 [Blocked]
- [x] #24971

Fluent UI 8
- [x] [Create testing enviroment for Fluent UI v8 and React 18](https://github.com/microsoft/fluentui/issues/24451)
- [x] https://github.com/microsoft/fluentui/issues/24041
- [x] Dialog and DialogFooter. Property 'children' does not exist on type 'IntrinsicAttributes & IDialogProps'
- [x] Teaching bubble missing children prop
- [x] #24975

**Comment by yume-chan** [comment]
Will FluentUI v8 get React 18 support or only FluentUI v9?

**Comment by micahgodbolt** [comment]
> Will FluentUI v8 get React 18 support or only FluentUI v9?

We don't know yet. This is what we need to figure out.

**Comment by micahgodbolt** [comment]
> Will FluentUI v8 get React 18 support or only FluentUI v9?

Yes, v8 and v9 will support React 18 as soon as we are confident that the controls will work in the new React version.

**Comment by joaomoreno** [comment]
@micahgodbolt Looking forward to this, any updates?

**Comment by micahgodbolt** [comment]
@joaomoreno PRs were just merged to update our peer deps. We're as confident as we're able to be about React 18 consumption, so test away and please give us any feedback.

**Comment by micahgodbolt** [comment]
Going to close this epic down as the focus was to enable consumption in React 18.

**Comment by JamesBurnside** [comment]
> PRs were just merged to update our peer deps

@micahgodbolt thanks for making this change! When do you expect to do your next stable npm release with the update?

**Comment by micahgodbolt** [comment]
React hooks was updated in https://github.com/microsoft/fluentui/pull/25278
