### ISSUE TITLE
public-docsite-v9 Epic

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#22600]
- [x] Investigate [removal of addon docs options](https://github.com/microsoft/fluentui/pull/22599/files#r855656625)
- [x] Look into example "show code"
- [ ] Update pipeline to publish to chromatic on release
- [ ] Remove from yarn workspace
- [ ] permanent URL?
- [ ] Upgrade to CSF v3
- [ ] Change root imports to 'index.stories.tsx' and change glob
- [ ] #22580 
- [x] https://github.com/microsoft/fluentui/pull/22599
