### ISSUE TITLE
Input: Move to RC

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#22674]
- [x] Resolve `contentBefore/After` Storybook stories - #21450
- [x] Resolve filledDarker, filledLighter contrast issue - #21449
- [x] Finish a11y testing - #21174
- [x] Write migration guide - #22769
