### ISSUE TITLE
Epic: Move off usage of flex gap in v9 components

### ISSUE THREAD

**Issue by TristanWatanabe** [microsoft/fluentui#22704]
## Context
After much discussions with one of our partners ([breakdown here](https://microsoft.sharepoint-df.com/teams/FluentUIInternal/_layouts/15/Doc.aspx?sourcedoc=%7B66e5f1ff-23d0-49ab-9a7d-acf3b47344f3%7D&action=edit&wd=target(Build%20system.one%7C13440648-7e78-4299-bc71-661d59756ff2%2FV9%20Browser%20Minbar%20Conclusion%7Cfe9116b5-693e-4559-aaf2-27ca7725abd2%2F)&share=IgH_8eVm0COrSZp9rPO0c0TzAZ1rnQYDmLb_8iCSF8BicSQ)), we have landed on a decision to make our minimum required browser for v9 to be based of the [browser matrix](https://caniuse.com/resizeobserver) that support `ResizeObserver`. This means that any **ECMAScript** (ES), **browser** and **CSS** features that supersede the `ResizeObserver` browser matrix will each have to be handled via transpilation and polyfills. Fortunately, we don't have to concern ourselves with ES syntax since that can be handled by transpiling code down along the usage of the standard ES polyfill library ([core-js](https://www.npmjs.com/package/core-js)). Browser API features can also be polyfilled, however, we intentionally chose `ResizeObserver` as our minbar because it was the latest browser API feature that we use within our v9 components. The problem lies with CSS features as they are currently difficult and generally not recommended to be polyfilled due to the convoluted implementations (due to dev restrictions in the current ecosystem today) that result in poor performance. Unfortunately, v9 components currently use a CSS feature that exceed our current browser minbar that being **`flex gap`**. Since polyfilling is not option, we are left with no choice but to move off using `flex gap` in v9 components (and if you're wondering why we didnt just set the browser minbar at `flex gap`, make sure to read the first linked document above).

## Work items
- [ ] Decide on a new pattern to replace `flex gap`
	- current proposal is to use `grid` layout instead of `flex` wherever applicable and other scenarios will be handled in a case by case basis and refactor will be up to component owners.
- [ ] Remove usage of `flex gap` in the following components 
	- [x] react-badge: #23379
	- [x] react-button
		- [x] Button: #23091
		- [x] CompoundButton: #23091
	- [ ] react-card
		 - [ ] CardFooter
		 - [ ] CardHeader
	- [x] react-checkbox: #22974
	- [ ] react-combobox
		- ~[ ] ComboButton~
		- [ ] Option
		- [ ] OptionGroup
		- [ ] Listbox
	- [ ] react-input
	- [ ] react-menu
		 - [ ] MenuItem
		 - [ ] MenuList
	- [x] react-radio: #22975
	- [ ] react-spinner
	- [x] react-switch: #22976
	- [x] react-tabs: #22920
	- [ ] react-toolbar
- [ ] Remove usage of `flex gap` in stories of following components
   - [ ] Avatar
   - [ ] Badge
   - [ ] Button
   - [ ] Card
   - [ ] CompoundButton
   - [ ] CounterBadge
   - [ ] Divider
   - [ ] FluentProvider
   - [ ] Image
   - [ ] Input
   - [ ] Menu
   - [ ] MenuButton
   - [ ] Overflow
   - [ ] Popover
   - [ ] Portal
   - [ ] Positioning
   - [ ] PrescenceBadge
   - [ ] RadioGroup: #22981
   - [x] SpinButton #23261
   - [ ] SplitButton
   - [ ] Switch
   - [ ] TabList
   - [ ] Text
   - [ ] Textarea
   - [ ] Theme
   - [ ] ToggleButton
   - [ ] Tooltip
- [ ] Remove usage of flex gap from upgrade guides below
   - [ ] From v8
      - [ ] RadioGroup
      - [ ] SpinButton

**Comment by andrefcdias** [comment]
IMO removing `flex gap` support is detrimental for the following reasons:
- `flex` is the main web layout used as it's the easiest
- `flex` does not allow for collapsible margins, so if we can't use `gap`, we can't not have doubled paddings in between elements, therefore we can't use `flex`
- Not having `flex gap` for `Card` will improve component complexity and require more bloat to make it work. Emphasis on "make it work" as it won't be an ideal approach.
- Said implementation will be very difficult to extend style wise, hindering all other users of our product

Given the scope of this requirement and that we have the tools that allow users to customize our components and overwrite styles, why not coordinate with the affected users to suggest `margin` based alternatives?

**Comment by Hotell** [comment]
Thanks for great progress on this topic @TristanWatanabe 🙌

Based on the ResizeObserver browser support, the proposal is saying to support those very old browsers ?

![image](https://user-images.githubusercontent.com/1223799/166910904-d9378590-1f0c-40c2-9968-e769a7238389.png)

- Edge 69
- Chrome 64
- Firefox 69
- Safari 13.1

If that's **a yes** I don't feel comfortable about that as that will force us to ship code "almost on IE 11" support which is something that we as modern library shouldn't do even worse we should 


Regarding **Flex gap**:

I'd suggest different approach instead. We should not penalise users/customers in a way everything or nothing. Instead we should leverage Progressive enhancement patterns and opt-in fallback way. 

We can check if user browser supports Flex, or particular consumers can statically declare it because they know they users best.


### Options

1. provide written guidance to v9 users that cannot support flex-gap natively, what they should do ( preferred way )
2. provide some form of compat library extension that provides flex-gap fallbacks 

**Check for `flex-gap` support** 

```
function checkFlexGap() {
  // create flex container with row-gap set
  var flex = document.createElement("div");
  flex.style.display = "flex";
  flex.style.flexDirection = "column";
  flex.style.rowGap = "1px";

  // create two, elements inside it
  flex.appendChild(document.createElement("div"));
  flex.appendChild(document.createElement("div"));

  // append to the DOM (needed to obtain scrollHeight)
  document.body.appendChild(flex);
  var isSupported = flex.scrollHeight === 1; // flex container should be 1px high from the row-gap
  flex.parentNode.removeChild(flex);

  return isSupported;
}
```

**Fallback CSS example:**

![image](https://user-images.githubusercontent.com/1223799/166912441-211e3ed0-2bed-4c1c-9655-dc382e8098cf.png)


Fallback and check support can be combined to define proper CSS overrides or to create some kind of compat encapsulation with griffel (mixin?) etc

**Comment by Hotell** [comment]
> Since this fallback would be applied only to older browsers this could be a significant performance degradation

v9 does not support ie 11 , so that should not happen. without proper metrics we can only speculate. Based on world browser data usage, we talk about approx 11% of users that will use this fallback. 
![image](https://user-images.githubusercontent.com/1223799/167100297-eaf0d9ba-15aa-4617-b32a-1d2aa1aa08aa.png)

> Maybe we could mitigate this by replacing the * with a CSS class like .fui-flex-gap but then we need to ensure the class is applied to all flex children.

This approach would increase complexity and probably also performance more than using `*` , as that would need to be done on every render on JS side of things and make our composition more brittle for these users on old browsers. Any kind of javascript is always slower by definition especially on older engines than CSS from my experience.

**Comment by spmonahan** [comment]
I certainly agree that using the `*` selector is ideal from a fallback perspective in that it maps pretty cleanly to `flex-gap` I'm just concerned that it will introduce measurable performance degradation. I'm working on getting some actual performance data to help inform our decision.

**Comment by Hotell** [comment]
Today we had a session with @andrefcdias  to try out this approach on Card which requires a non trivial layouting/spacing approach that was created by design folks. 


In short, **it turns out that fallback CSS declaration won't work for more complicated scenarios** as this one (Card), leaving us with IMO a hard to maintain css definitions in our codebase (lots of `calc` operations needed for spacing etc ).  

Andre will provide a draft PR this week to showcase the cost of not using `flex-gap` for Card.

**Comment by spmonahan** [comment]
After reviewing some performance numbers taken from a partner app my general recommendation is to avoid the universal selector if at all possible. It wasn't actually the worst performer, that honor generally belongs to [CSS attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors) in the app that was tested, but it was reliably one of the slowest selectors.

Interested to see the issues with `Card` layout.

**Comment by TristanWatanabe** [comment]
From internal discussions to add on to @spmonahan's [comment](https://github.com/microsoft/fluentui/issues/22704#issuecomment-1122808045) regarding the avoiding the universal selector: 

We were trying to find a systematic approach to replace flex gap with something like lobotomized owl, grid, etc but we've come to the conclusion that there wont be a good 1 to 1 replacement and that it should be handled on a case by case basis by component owners. Ideally using `grid` suffices for most cases but if it doesn't, that judgment will be left up to the component owners (maybe use the old approaches before flex gap was a thing such as margins).

**Comment by TristanWatanabe** [comment]
> From internal discussions to add on to @spmonahan Sean Monahan FTE's [comment](https://github.com/microsoft/fluentui/issues/22704#issuecomment-1122808045) regarding the avoiding the universal selector:
> 
> We were trying to find a systematic approach to replace flex gap with something like lobotomized owl, grid, etc but we've come to the conclusion that there wont be a good 1 to 1 replacement and that it should be handled on a case by case basis by component owners. Ideally using `grid` suffices for most cases but if it doesn't, that judgment will be left up to the component owners (maybe use the old approaches before flex gap was a thing such as margins).

Should have updated this sooner but work on moving off flexbox is paused as partner conversations are ongoing. Component owners who are able to refactor usage of `flexbox gap` to something else and achieve the same styling are still free to do so.

**Comment by TristanWatanabe** [comment]
Closing as we've decided to continue using `flex gap` moving forward whenever necessary since some existing components would require massive refactoring and suffer perf degradations. Also, the effect of a browser not supporting `flex gap` ultimately does not result in an application crash which means the impact isn't as drastic. We've introduced a partial support matrix (PR [here](https://github.com/microsoft/fluentui/pull/24283)) that will inform consumers what features would be missing if they are unable to support the Full Browser matrix along with expectations they can expect from the fluent library going forward.
