### ISSUE TITLE
Label: Move to RC

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#22777]
## TODOs
- [x] Manual accessibility checklist. #22778
- [x] Accessibility tests.
- [x] Update migration guide. #22843
- [x] Add codeowner. #22857
- [x] Update spec. #22833
- [x] Update stories. #22833
- [x] Address #22661
  - [x] Update spec to mention that the contrast error is acceptable.
  - [x] Add note on docs about this?
- [x] Remove commons type. #22881
- [x] Move to RC! #22865
