### ISSUE TITLE
Convert react-component stories to use index.stories.tsx

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#23393]
PR #23354 started work to move all of our component stories from this format.
We should also convert from relative to package imports to avoid imports breaking when moved, and in preparation for possibility of publishing stories in their own package. 

```
.storybook/main.js
  - stories: [.../src/**/*.stories.@(ts|tsx)]
 
src/stories/
   Component.stories.tsx
   ComponentDefault.stories.tsx

src/stories/Component.stories.tsx
   import { Component } from '../../index';
```

to 

```
.storybook/main.js
  - stories: [.../src/**/index.stories.@(ts|tsx)]

src/stories/
   Component/ 
      index.stories.tsx
      ComponentDefault.stories.tsx

src/stories/Component.stories.tsx
   import { Component } from '@fluentui/react-component';
```

This issue is tracking the work needed to convert all of the packages whose stories are currently imported into react-components
- [x] #23564
- [x] Update `migrate-converged` generator: #23538 
- [x] Convert @fluentui/react-accordion stories to index.stories.tsx approach #23354
- [x] #23566
- [x] Convert @fluentui/react-avatar stories to index.stories.tsx approach #23354
- [x] #23511
- [x] #23513
- [x] #23515
- [x] #23519
- [x] #23520
- [x] #23521
- [x] #23539
- [x] #23540
- [x] #23541
- [x] #23568
- [x] #23673
- [x] #23674
- [x] #23675
- [x] #23676
- [x] #23581
- [x] #23583
- [x] #23646
- [x] #23649
- [x] #23651
- [x] #23653
- [x] #23656
- [x] #23661
- [x] #23664
- [x] #23669
- [x] #23671
- [x] #23694
- [x] #23695
- [x] ~#23696~
- [x] #23692
- [x] #23720
- [x] #23702
- [x] #23703
- [x] #23704
- [x] #23722
- [x] #23723

**Comment by Hotell** [comment]
Im missing tweaks to our automation. can this be added ?

- [create-component](https://github.com/microsoft/fluentui/tree/master/scripts/create-component)
- [migrate-converged-pkg ](https://github.com/microsoft/fluentui/tree/master/tools/generators/migrate-converged-pkg)

**Comment by micahgodbolt** [comment]
> Im missing tweaks to our automation. can this be added ?
> 
> * [create-component](https://github.com/microsoft/fluentui/tree/master/scripts/create-component)
> * [migrate-converged-pkg ](https://github.com/microsoft/fluentui/tree/master/tools/generators/migrate-converged-pkg)

I added a story to update create-component to have package based imports. File naming/folder conventions are already in place.

**Comment by Hotell** [comment]
bit confused here, would you mind updating this issue to provide context?
 
- this PR uses relative paths https://github.com/microsoft/fluentui/pull/23527/files
- another PR use absolute paths  https://github.com/microsoft/fluentui/pull/23516/files

Also would be great if folks can hit re-review on approved PR's if they introduce any significant change like was done in https://github.com/microsoft/fluentui/pull/23516/files ( changing relative to absolute )

**Comment by micahgodbolt** [comment]
There were a few PRs that went through with relative paths before we decided to enforce package paths

**Comment by micahgodbolt** [comment]
This work is done
