### ISSUE TITLE
June project proposal

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#23417]
## Problem

Related: #22240 

- [x] Finish merging initial implementation of AvatarGroup. #22736 
- [x] Add styling to AvatarGroup. #23437
- [x] Add styling to AvatarGroupItem. #23468
- [x] Add tests for AvatarGroup. #23549
- [x] Add tests for AvatarGroupItem. #23561
- [x] Add stories for AvatarGroup. #23493
- [x] Remove stories for AvatarGroupItem. #23497

## Appetite

2-3 weeks
