### ISSUE TITLE
Ensure that component stories are importing from react-components suite

### ISSUE THREAD

**Issue by TristanWatanabe** [microsoft/fluentui#23846]
### Describe the issue:
We want to prevent cross package imports in story files and to only allow imports from the `@fluentui/react-components` suite. These stories are being exported to codesandbox therefore we want to demonstrate best practices that we recommend to users which is that they should only import from `@fluentui/react-components`

- [x] Add eslint-rule: #21907
- [x] Turn on rule and set to `warn` initially: #23845
- [x] Update component stories that are violating rule:
	- [x] @fluentui/react-accordion #23870
	- [x] ~@fluentui/react-alert~
	- [x] @fluentui/react-aria #24003
	- [x] @fluentui/react-avatar #24108
	- [x] @fluentui/react-badge #23855
	- [x] @fluentui/react-button #23854
	- [x] ~@fluentui/react-card~
	- [x] @fluentui/react-checkbox #23857
	- [x] @fluentui/react-combobox #24004
	- [x] @fluentui/react-components #24112
	- [x] ~@fluentui/react-dialog~ 
	- [x] @fluentui/react-divider #23862
	- [x] @fluentui/react-image #23863
	- [x] @fluentui/react-input #23871
	- [x] @fluentui/react-label #23907
	- [x] @fluentui/react-link #23908
	- [x] @fluentui/react-menu #23873
	- [x] @fluentui/react-overflow #24094
	- [x] @fluentui/react-popover #23877
	- [x] @fluentui/react-portal #24005
	- [x] @fluentui/react-provider #23880
	- [x] @fluentui/react-radio #23911
	- [x] @fluentui/react-select #24034
	- [x] @fluentui/react-slider #23912
	- [x] @fluentui/react-spinbutton #23971
	- [x] @fluentui/react-spinner #23935
	- [x] @fluentui/react-storybook-addon #24095
	- [x] @fluentui/react-switch #23936
	- [x] @fluentui/react-tabs #23938
	- [x] @fluentui/react-textarea #23939
	- [x] @fluentui/react-theme #23940
	- [x] @fluentui/react-toolbar #24006
	- [x] @fluentui/react-tooltip #23941
	- [x] @fluentui/react-text #23942
- [x] Update rule error level to `error` #24002

**Comment by TristanWatanabe** [comment]
Done
