### ISSUE TITLE
[Feature]: Enable screener checks to run from the screener proxy

### ISSUE THREAD

**Issue by ralucapelin** [microsoft/fluentui#23903]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Make screener checks runs to be triggered by the screener proxy instead of ADO using the GitHub API.

- [x] Convert the Azure DevOps job that runs the screener checks to a GitHub Action;  | https://github.com/microsoft/fluentui/pull/24106
- [x] Remove ADO jobs regarding screener checks; |  https://github.com/microsoft/fluentui/pull/24178
- [ ] Trigger screener checks using the GitHub REST API.

### Have you discussed this feature with our team

@ling1726 

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ralucapelin** [comment]
-forks don't have access to the repo's secrets, so the workflow wouldn't work if triggered by forks
-solution: use two workflows -> one creates necessary artifacts that do not require access to secrets and is run from the fork
                                               -> one uses information from the two artifacts and is run from the repo

**Comment by ling1726** [comment]
In order to keep more of the logic in the monorepo, it was decided to split the screener logic into two separate workflows (to encapsulate secretes) to avoid more logic in the 'hidden' internal proxy repo
