### ISSUE TITLE
feat(build): revamp `build` task to be more open and configurable

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#23930]
#### Actual behavior:

Every package uses `just build` for compiling TS source to various formats. 

There is non trivial logic happening behind the scenes that introduces couple of problems, to name few:
- lack of configurability from call site
- hard to extend functionality
- others

#### Expected behavior:

We need to be able to better control build outputs from call site instead relying on magic like `isConvergerd()` etc

**Examples of new functionality:**

```sh
just build --format esm,cjs,amd

# or

just build --output esm,cjs
```

This will make the system more open to any potential configurability on call site

## Tasks
- [x] implement new `build` API as described | https://github.com/microsoft/fluentui/pull/23934
- [ ] update migration generator/package generator to properly setup build with new flags 
   - should have logic to determine if a package with no AMD output is a dependency of package that ships AMD, thus revamp:
     - build task
     - lint task https://github.com/microsoft/fluentui/pull/24052/files#r928728431
- [x] revert https://github.com/microsoft/fluentui/pull/23923 and use new API | https://github.com/microsoft/fluentui/pull/24030

## Related issues

- https://github.com/microsoft/fluentui/issues/23919
- https://github.com/microsoft/fluentui/pull/23923#issuecomment-1185416429
