### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#23983]
## Preparation:

- [x] Open UI Research
  - https://open-ui.org/components/table.research
- [x] Open GitHub issues related to component
  - #24223
  - #24224
  - #24225
  - #24805
  - #24226
  - #24227
  - #24228
  - #24229
  - #24381
  - #24382
  - #24420
  - #24421
- [x] react-\* package scaffolded with the right ownership in CODEOWNERS
  - #23876
- [x] Component Spec authored and reviewed
  - #23984

## Implementation

[link to react-* package folder]

- [x] Component implementation
  - https://github.com/microsoft/fluentui/tree/master/packages/react-components/react-table
- [x] Storybook stories
  - [link(s) to stories PRs]
- [x] Add tests: Conformance, Unit, and VR -- add PRs to all
  - [x] Bundle size fixtures
  - [x] Conformance tests
  - [x] Unit tests
  - [x] VR tests
  - [x] Accessibility behavior tests
  - [x] Create an issue and run [manual accessibility tests](https://github.com/microsoft/fluentui/wiki/Manual-Accessibility-Review-Checklist): (issue link)
  - [ ] Performance test scenario
- [x] README.md covering basic usage
- [ ] MIGRATION.md guide (include v8 and v0)

## Validation

- [ ] Add and validate in UI Builder
- [x] Add and validate in docs site
- [x] Validate with token pipeline
- [x] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods
