### ISSUE TITLE
Defined standard for v9 package file organization

### ISSUE THREAD

**Issue by TristanWatanabe** [microsoft/fluentui#24129]
## Steps:
- [x] Create RFC to document new package structure: #24332, #24543
- [x] Update `migrate-converged-pkg` generator to reflect new structure: #24458
- [x] Run generator on existing v9 packages to reflect new structure - will complete part of #23343
	- [x] @fluentui/babel-preset-global-context #25340
	- [x] @fluentui/global-context #25341
	- [x] @fluentui/keyboard-keys #25362
	- [x] @fluentui/priority-overflow #25362
	- [x] @fluentui/react-accordion #25196
	- [x] @fluentui/react-alert #25197
	- [x] @fluentui/react-aria #25199
	- [x] @fluentui/react-avatar #25473
	- [x] @fluentui/react-avatar-context #25473
	- [x] @fluentui/react-badge #25335
	- [x] @fluentui/react-button #25336
	- [x] @fluentui/react-card #25229
	- [x] @fluentui/react-checkbox #25337
	- [x] @fluentui/react-combobox #26037
	- [x] @fluentui/react-components #26051
	- [x] @fluentui/react-conformance-griffel #25362
	- [x] @fluentui/react-context-selector #25362
	- [x] @fluentui/react-dialog #25523
	- [x] @fluentui/react-divider #25360
	- [x] @fluentui/react-field #25817
	- [x] @fluentui/react-image #25230
	- [x] @fluentui/react-input #25469
	- [x] @fluentui/react-infobutton #26111
	- [x] @fluentui/react-label #25470
	- [x] @fluentui/react-link #25471
	- [x] @fluentui/react-menu: #25015
	- [x] @fluentui/react-overflow #25524
	- [x] @fluentui/react-persona #25737
	- [x] @fluentui/react-popover #25735
	- [x] @fluentui/react-portal #25481
	- [x] @fluentui/react-portal-compat #25481
	- [x] @fluentui/react-portal-compat-context #25481
	- [x] @fluentui/react-positioning #25736
	- [x] @fluentui/react-progress #25744
	- [x] @fluentui/react-provider #25809
	- [x] @fluentui/react-radio #25810
	- [x] @fluentui/react-select #25359
	- [x] @fluentui/react-shared-contexts #25810
	- [x] @fluentui/react-slider
	- [x] @fluentui/react-spinbutton #25813
	- [x] @fluentui/react-spinner #25814
	- [x] @fluentui/react-storybook #25482
	- [x] @fluentui/react-storybook-addon #25482
	- [x] @fluentui/react-switch #25819
	- [x] @fluentui/react-table #25377
	- [x] @fluentui/react-tabs #25241
	- [x] @fluentui/react-tabster #25833
	- [x] @fluentui/react-text #25231
	- [x] @fluentui/react-textarea #25820
	- [x] @fluentui/react-theme #25812
	- [x] @fluentui/react-theme-sass #25736
	- [x] @fluentui/react-toolbar #25920
	- [x] @fluentui/react-tooltip #25818
	- [x] @fluentui/react-utilities #25736
- [x] Update `create-package` and `create-component` scripts to reflect changes so any new created components follow new pattern #26067
- [x] Follow up on TODO item in getStories function of v9 public docsite (#25221, #25388, #25540) and delete functions no longer needed from `migrate-converged-pkg` generator. #26112

## Related Issues:
#22289, #23976
