### ISSUE TITLE
Improve performance of focus selectors in v9

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#24183]
The current `data-keyboard-nav` selector that is applied to the FluentProvider causes too much style recalclation each time the user's navigation mode changes (mouse/keyboard). 

Below are results of the `SelectorStats` trace from `edge://tracing` which measures the time spent per-selector during the matching phase. The comparison was done by comparing selector stats for `.fui-focus-visible` (polyfill) vs the current `[data-keyboard-nav]` selector.

 (Lower numbers are better)

### `[data-keyboard-nav]` on provider root
| time elapsed | fast reject count | match attempts |match count |
| - | - | - | - |
| 2098 | 1120 | 23511 | 416 |

## Tasks

- [x] Create more localized focus selectors #24154
- [x] microsoft/griffel#178 needs to be resolved so the `.fui-FluentProvider` does not need to be in the selector at all
- [x] Use `CSS.supports("selector(:focus-visible)")` to check platform support and default to `:focus-visible` #24195

**Comment by ling1726** [comment]
Blocked by: microsoft/keyborg#19
