### ISSUE TITLE
Persona

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#24213]
## Preparation:

- [x] Open UI Research
- [x] Open GitHub issues related to component
  - #23386
- [x] react-\* package scaffolded with the right ownership in CODEOWNERS
  - #24214
- [x] Component Spec authored and reviewed
  - #24436

## Implementation

[@fluentui/react-persona](https://github.com/microsoft/fluentui/tree/master/packages/react-components/react-persona)

- [x] Component implementation
  - #24749
- [x] Storybook stories
  - #24749
  - #25626
- [ ] Add tests: Conformance, Unit, and VR -- add PRs to all
  - [x] Bundle size fixtures
    - #24214 
  - [x] Conformance tests
    - #25007  
  - [x] Unit tests
    - #25007  
  - [x] VR tests
    - #25007  
    - #25626
  - [ ] Accessibility behavior tests
  - [x] Create an issue and run [manual accessibility tests](https://github.com/microsoft/fluentui/wiki/Manual-Accessibility-Review-Checklist): 
    - #25698
    - #25880
  - [x] Performance test scenario
    - #25863
- [x] README.md covering basic usage
  - #25008 
- [x] MIGRATION.md guide (include v8 and v0)
  - #25022  

## Validation

- [ ] Add and validate in UI Builder
- [ ] Add and validate in docs site
- [ ] Validate with token pipeline
- [x] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods

**Comment by sopranopillow** [comment]
Closing this issue since Persona is in stable.
