### ISSUE TITLE
Table/DataGrid: Composable logic

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#24226]
Explore ways of composing interactive behaviour to the `Table` primitives. Preparation for future `DataGrid` component
- [x] support selection (single + multiple) #24329
- [x] support sorting #24329
- [x] support autocontrol #24688
- [x] rows -> getRows
- [x] support pagination/data virtualization -> difference between rows and displayed rows
- [x] composable behaviour (e.g. sort code should not be there if sorting is not needed)
- [ ] support aria props and keyboard navigation - #24964
  - runtime validation for attributes (?)
- [ ] support component props #24964
- [ ] unstable callbacks
- [ ] column ordering (?) `columns.map`
- [ ] colspan + resizable columns [react-table](https://tanstack.com/table/v8/docs/examples/react/column-sizing) #24226
- [ ] Grouping/collapsible rows #24966
- [ ] figure out better name than `useTable`

**Comment by ling1726** [comment]
Prototypes for
* pagination
* column sizing
* virtualization

in #24226
