### ISSUE TITLE
feat: make backbone of our tooling compliant with package standards (packaging `/scripts`)

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#24349]
## Problem

Starting with installation of dependencies  ending with releasing our product to partners... we rely heavily on contents within `scripts/` folder. 

Historically functionality was added here adhoc without being compliant to any style-guide, tests coverage, type checking, out-dated files, which made `scripts/` a kind of a black box.

This approach won't scale as we are going forward. Instead of continuing adding technical depth and making it hard to maintain we need to apply similar quality and structure to `scripts/` as we apply for our component packages.

## Solution

- enable strict type checking
- establish package boundaries within `scripts/`
- move "packaged" scripts sub-folders to separate packages to establish explicit public API's contracts

**Example (simplified):**

_Now:_

```
|- scripts/
|- |- api-extractor/
|- |- beachball/
|- |- cypress/
|- |- screener/
```

`import { someFn } from '@fluentui/scripts/cypress/one/two`

_After:_

```
|- packages/
|- |- tools/
|- |- |- api-extractor/
|- |- |- beachball/
|- |- |- cypress/
|- |- |- screener/
```

`import { someFn } from '@fluentui/cypress`

Outlined steps will enable us to ship components with high confidence and also as a performance side-effect will improve our PR CI pipelines times as there wont be one monolithic `scrips` packages which affects whole monorepo.

## Tasks
 - [x] https://github.com/microsoft/fluentui/pull/24264
 - [x] https://github.com/microsoft/fluentui/pull/24345
 - [x] https://github.com/microsoft/fluentui/pull/24526
 - [x] https://github.com/microsoft/fluentui/pull/25074
 - [x] enable checks for create-* folders / https://github.com/microsoft/fluentui/pull/25710
 - [x] move root files to proper domain/sub-folder / https://github.com/microsoft/fluentui/pull/25710
 - [ ] enable checks for all root files
 - [ ] prepare sub-folders for packaging (domain boundaries)
    - [x] https://github.com/microsoft/fluentui/pull/25738 
    - [x] https://github.com/microsoft/fluentui/pull/26099
    - [x] https://github.com/microsoft/fluentui/pull/26100
    - [ ] https://github.com/microsoft/fluentui/pull/26125
    - [x] https://github.com/microsoft/fluentui/pull/26139
    - [x] https://github.com/microsoft/fluentui/pull/26109
    - [x] https://github.com/microsoft/fluentui/pull/26072
    - [x] https://github.com/microsoft/fluentui/pull/25851
 - [ ] migrate [sub-folder] to [package] (this will contain multiple sub-tasks)
    - [ ] TBA
    - [ ] TBA
