### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by tomi-msft** [microsoft/fluentui#24980]
## Preparation:

- [x] Open UI Research
  - [link to https://open-ui.org/](https://open-ui.org/research/component-matrix)
- [x] react-\* package scaffolded with the right ownership in CODEOWNERS
  - [link to package](https://github.com/microsoft/fluentui/tree/master/packages/react-components/react-progress)
- [x] Component Spec authored and reviewed
  - [link to PR](https://github.com/microsoft/fluentui/pull/24418)
  - [link to SPEC](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-progress/Spec.md)

## Implementation

[link to react-* package folder](https://github.com/microsoft/fluentui/tree/master/packages/react-components/react-progress)

- [x] Component implementation
  - [link(s) to component implementation related PRs](https://github.com/microsoft/fluentui/pull/24023)
  - [refactoring PR](https://github.com/microsoft/fluentui/pull/25067)
  - [ProgressField PR](https://github.com/microsoft/fluentui/pull/25103)
- [x] Storybook stories
  - [link(s) to stories PRs](https://github.com/microsoft/fluentui/pull/24023)
- [x] Add tests: Conformance, Unit, and VR -- add PRs to all
  - [x] Bundle size fixtures
    - [Bundle size fixtures](https://github.com/microsoft/fluentui/pull/25105)
  - [x] Conformance tests
    - [Conformance tests](https://github.com/microsoft/fluentui/pull/25105) 
  - [x] Unit tests
    - [Unit tests](https://github.com/microsoft/fluentui/pull/25105) 
  - [x] VR tests
    - [VR tests](https://github.com/microsoft/fluentui/pull/25105) 
  - [x] Accessibility behavior tests
  - [x] Create an issue and run [manual accessibility tests](https://github.com/microsoft/fluentui/wiki/Manual-Accessibility-Review-Checklist): [issue link](https://github.com/microsoft/fluentui/issues/25174)
  - [x] Performance test scenario
- [x] README.md covering basic usage
   - [link](https://github.com/microsoft/fluentui/pull/25194)
- [x] MIGRATION.md guide (include v8 and v0)
   - [link](https://github.com/microsoft/fluentui/pull/25194)
 
## Validation

- [x] Add and validate in UI Builder
- [x] Add and validate in docs site
- [x] Validate with token pipeline
- [x] Validate in product
- [x] Finalize migration guide
  - [x] Author codemods
