### ISSUE TITLE
InfoLabel

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#25062]
## Preparation:

- [x] Open UI Research
  - N/A
- [x] Open GitHub issues related to component
  - N/A
- [x] react-\* package scaffolded with the right ownership in CODEOWNERS
  - #25083 
- [x] Component Spec authored and reviewed
  - #25251 

## Implementation

- [x] Component implementation
  - #25247  
- [x] Initial conformance and unit tests (validate basic functionality)
- [x] Initial documentation
  - [x] README.md covering basic usage
    - #25686 
  - [x] MIGRATION.md guide (include v8 and v0)
    - N/A 
  - [x] Storybook stories
    - #25247 
- [x] Component released as preview
  - #29562

## Validation

- [x] Add tests
  - [x] Bundle size fixtures
    - #25083 
  - [x] Unit tests
    - #25247 
  - [x] Conformance tests
    - #25247 
    - #25682
  - [x] VR tests
    - #26305
  - [x] Performance test scenario
    - #26271 
  - [ ] Accessibility behavior tests
  - [x] Create an issue and run [manual accessibility tests](https://github.com/microsoft/fluentui/wiki/Manual-Accessibility-Review-Checklist): 
    - #26427 
- [x] Validate with partners
- [x] Run a bug bash with other FUI crews
- [x] Finalize documentation
  - [x] Review and add any missing storybook
  - [x] Finzalize migration guide (N/A)
- [x] Component released as stable
  - [x] Run the `prepare-initial-release` script to remove the `-preview` suffix from the package name  #29585
  - [ ] Deprecate the `-preview` package in NPM
  - [x] Export the component from `@fluentui/react-components`  #29585
  - [x] In package.json: Remove the alpha/beta tag from the version number in package.json  #29585
  - [x] In package.json: Change beachball's disallowedChangeTypes to "major", "prerelease" #29585

**Comment by sopranopillow** [comment]
Released to stable in #29585
