### ISSUE TITLE
[Epic]: Visual Regression Tool Migration

### ISSUE THREAD

**Issue by TristanWatanabe** [microsoft/fluentui#25078]
## Problem

We are looking to move off using **Screener** as our Visual Regression testing solution for the entire monorepo by the end of the year.

## Solution
**Near Term**
- Near term plan is to integrate and use an internal **1JS VR** tool to replace screener for **v0, v7, v8, and v9**. The intent is for v0, v7 and v8 to stay with this solution going forward since they are legacy libraries.
	- [x] Integrate pipeline jobs to run 1JS VR tool (v9) #25606
		- [x] Only run VR test when package is affected #25676
	- [x] Integrate pipeline jobs to run 1JS VR tool (v8) #25643
		- [x] Only run VR test when package is affected #25676
	- [x] Add v0 stories to be used by 1JS VR tool #25663
	- [x] Integrate pipeline jobs to run 1JS VR tool (v0) #25922
	- [x] Intergrate pipeline jobs to run 1JS VR tool (v7) #25946
	- [x] Remove Screener workflow files (master branch) #25977
	- [x] Remove Screener pipeline job (v7 branch) #25990
	- [x] Replace any `Screener` imports with `StoryWright` for v8 #25979
	- [x] Replace any `Screener` imports with `StoryWright` for v9 #25980
	- [x] Replace any `Screener` imports with `StoryWright` for v7 #26049
	- [x] Remove any `Screener` related files from v0 #26053
	- [x] Remove `Screener` dependencies from package.json #26070
	- [x] Cleanup new 1JS VR tool yaml files (remove convert scripts,etc) #26070
	- [ ] Update any VR tool related docs in repo
	- [x] Delete `Screener` related github secrets #26086

**Long Term**
- Long term plan is to migrate **v9** VR tests to use **Chromatic** (Internal [Doc](https://microsoft-my.sharepoint-df.com/:w:/p/twatanabe/ETJng-7UQw9ClI4NDzfKFrcBO6miFceu_fxKhQx_Hy_6hw?e=ffgJ4o) writeup). This will have to be done in multiple steps: 
   - [x] Make `react-storybook-addon` configurable to be used by vr stories: #25162 
   - [ ] Refactor all v9 VR tests to use storybook Component Story Format (CSF)
   		- [x] Accordion #25525
   		- [x] Button #25108
   		- [x] Card #25526
   		- [x] Dialog #25527
   		- [x] Image #25527
   - [ ] Integrate Chromatic project for v9 into repo and make available for use
   - [ ] Slowly migrate each v9 component VR test to chromatic and refactor Screener interaction and hover tests to appropriate CSF equivalent. 
   - [ ] Colocate VR stories to their respective packages (i.e. move Menu VR tests to the `react-menu` package etc.)

**Comment by ling1726** [comment]
> I'm not sure what you meant by "other stories in the docsite" @ling1726 ?

@Hotell all our docsite stories sare colocated. i.e `Menu` docs stories are in the react-menu package

**Comment by Hotell** [comment]
> > I'm not sure what you meant by "other stories in the docsite" @ling1726 ?
> 
> @Hotell all our docsite stories are colocated. i.e `Menu` docs stories are in the react-menu package

gotcha, so we are on same page -> "about is to co-locate those vr stories/tests within package"

**Comment by TristanWatanabe** [comment]
Added vr stories colocation to the "todo" steps in the issue
