### ISSUE TITLE
Tree

### ISSUE THREAD

**Issue by bsunderhus** [microsoft/fluentui#25266]
## Preparation:

- [x] Open GitHub issues related to component
  - >  No issues were found
- [x] react-tree package scaffolded with the right ownership in CODEOWNERS
  - https://github.com/microsoft/fluentui/pull/25267
- [ ] Component Spec authored and reviewed
  - [link to spec in component package / PR]

## Implementation

[link to react-* package folder]

- [x] Component implementation
  - https://github.com/microsoft/fluentui/pull/25781
  - https://github.com/microsoft/fluentui/pull/26113
  - https://github.com/microsoft/fluentui/pull/26292
  - https://github.com/microsoft/fluentui/pull/26302
  - https://github.com/microsoft/fluentui/pull/26446
  - https://github.com/microsoft/fluentui/pull/26446
  - https://github.com/microsoft/fluentui/pull/26495
  - https://github.com/microsoft/fluentui/pull/26550
  - https://github.com/microsoft/fluentui/pull/26856
  - https://github.com/microsoft/fluentui/pull/26978
  - https://github.com/microsoft/fluentui/pull/26999
  - https://github.com/microsoft/fluentui/pull/27047
  - https://github.com/microsoft/fluentui/pull/27126
- [x] Storybook stories
  - https://github.com/microsoft/fluentui/pull/27270
- [ ] Add tests: Conformance, Unit, and VR -- add PRs to all
  - [x] Bundle size fixtures
  - [x] Conformance tests
  - [x] Unit tests
  - [x] E2E tests https://github.com/microsoft/fluentui/pull/27266, https://github.com/microsoft/fluentui/pull/27318
  - [x] VR tests
  - [x] Accessibility behavior tests
  - [x] Create an issue and run [manual accessibility tests](https://github.com/microsoft/fluentui/wiki/Manual-Accessibility-Review-Checklist): https://github.com/microsoft/fluentui/issues/28785
  - [x] Performance test scenario
- [ ] README.md covering basic usage
- [ ] MIGRATION.md guide (include v8 and v0)

## Validation

- [ ] Add and validate in UI Builder
- [ ] Add and validate in docs site
- [ ] Validate with token pipeline
- [ ] Validate in product
- [ ] Finalize migration guide
  - [ ] Author codemods

## Partner Deps / Asks

- PowerApps [[ref](https://powerbi.visualstudio.com/Trident/_workitems/edit/902480)]
- Other partner [data warehouse team] and [lakehouse team]

**Comment by sjwilczynski** [comment]
@bsunderhus do you know when the stable release of Tree component is planned? We would want to use it for a control we are currently developing for Teams

cc @dragoshomner

**Comment by bsunderhus** [comment]
Hey there @sjwilczynski , sorry the delay. We're still currently under development! Our latest forecast for stable release is August!

**Comment by sjwilczynski** [comment]
Awesome, can't wait for it!

**Comment by zuza-hofman** [comment]
Hi @bsunderhus, any updates? :) Your estimation is important for us since we are going through accessibility review. Any info will be appreciated

**Comment by bsunderhus** [comment]
Hey @sjwilczynski & @zuza-hofman , as with https://github.com/microsoft/fluentui/pull/28845 the `@fluentui/react-tree` stable release is merged, I'll be officially releasing the first stable first anytime soon!
