### ISSUE TITLE
Epic: Theme Designer

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#25424]
Problem: Designers want to be able to generate pleasing, accessible light and dark themes for Fluent UI controls.

Current prototype: https://aka.ms/themedesigner-v9

Work to do:
- [ ] Improve palette generation
- [ ] Improve documentation and usage guidance
- [ ] Do a11y pass and improve a11y
- [ ] Make individual palette colors customizable

**Comment by ahmed-adly-khalil** [comment]
a designer would be super helpful

**Comment by AkiraVoid** [comment]
@micahgodbolt Please re-open this, we are still waiting for a theme designer (not just a prototype).
