### ISSUE TITLE
Roadmap: v-build 22/23 

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#25488]
This document outlines our focused initiatives for Build/CI/DX for FY 22/23.

## Remarks:
- Main purpose of this roadmap is to set visibility what is planned in terms of work. 
- Priority is reflected by milesonte period  (if something is in Q2 it has higher priority than things in Q3 etc)
- ETA's/time-table of outlined initiatives might change

### Customer facing

  - [x] Internal API stripping v1 / https://github.com/microsoft/fluentui/issues/23343
  - [ ]  Internal API stripping v2 / https://github.com/microsoft/fluentui/issues/25694 ( ⏸ on hold )
  - [x] Release automation / https://github.com/microsoft/fluentui/issues/23914
  - [x] Browser support matrix / https://github.com/microsoft/fluentui/pull/22889
  - [x] React 17 support / v9,8 works with v17 + repo migration https://github.com/microsoft/fluentui/pull/24356
  - [x] React 18 support / v9,8 works with v18
  - [ ] TS downleveling / https://github.com/microsoft/fluentui/issues/18441
  - [ ] Issues triaging automation / https://github.com/microsoft/fluentui/issues/25697 ( ⏸ on hold )

### VR tests

- [x] migration screener to github actions / https://github.com/microsoft/fluentui/issues/23903
- [x] replacing screener / https://github.com/microsoft/fluentui/issues/25078

### CDA (Common Dependency Alignment)

- [x] Migrate to Node 16 / https://github.com/microsoft/fluentui/issues/27660
- [x] Migrate to jest 27 / https://github.com/microsoft/fluentui/issues/18442
- [x] Migrate to jest 28 (FY 23/24) / https://github.com/microsoft/fluentui/pull/26958
- [x]  Migrate to jest 29 (FY 23/24) / https://github.com/microsoft/fluentui/pull/27935
- [x] Migrate to prettier 2.8 / https://github.com/microsoft/fluentui/pull/26959
- [x] Migrate to typescript 4.7 / https://github.com/microsoft/fluentui/pull/28067

### Misc/Internal/DX

- [x] Scripts packaging / https://github.com/microsoft/fluentui/issues/24349
- [ ] Migration to nx / TBA
- [x] Migration to webpack 5 / https://github.com/microsoft/fluentui/pull/24542
- [x] Perf-tests overhaul 
     - [x] https://github.com/microsoft/fluentui/pull/26920
     - [x] https://github.com/microsoft/fluentui/pull/26893
     - [x] https://github.com/microsoft/fluentui/pull/26965
- [ ] Transpilation change / https://github.com/microsoft/fluentui/issues/22426 
  - [ ] replacing babel for transpilation (v9)
  - [ ] replacing ts-jest with swc (all projects)
- [ ] Single version policy / https://github.com/microsoft/fluentui/issues/21395
- [ ] Faster pipelines/tooling Epic / https://github.com/microsoft/fluentui/issues/27359

## Roadmap

```mermaid
gantt
    title v-build roadmap FY 22/23
    dateFormat  YY-MM
    axisFormat %y %b 
    %% todayMarker off
    %% excludes    weekends
    FY Start : milestone, q1, 22-07, 0d
    Q1 Start : milestone, q1, 22-07, 0d
    Q2 Start : milestone, q2, 22-10, 0d
    Q3 Start : milestone, q3, 23-01, 0d
    Q4 Start : milestone, q4, 23-04, 0d
    FY End : milestone, q1, 23-06, 0d
    

section Customer facing        
    Internal API stripping v1                : done, 22-07,22-12
    Release automation                    : done, crit, 22-08,22-11
    Browser support matrix                : done, 22-07,22-11
    React 17 support                      : done, 22-07,22-09  
    React 18 support                      : done, 22-09,22-12  
    TS downleveling                       : 23-05,23-07  
    
section VR tests
    migration screener to github actions      : done, 22-07,22-11
    replacing screener         : done, crit, 22-10,23-01

section CDA
    Migrate to Node 16                     : done, 23-04,23-06
    Migrate to jest 27                     : done, j27, 23-04,23-05
    Migrate to jest 28                     : done, j28, 23-05,23-06
    Migrate to jest 29                     :  done, j29, 23-06,23-07
    Migrate to typescript 4.7              : done, 23-05,23-07
    Migrate to prettier 2.8              : done, 23-03,23-04

section Misc/Internal/DX
    Scripts packaging                     : done, 22-08,23-02
    Transpilation change                : done, 23-01,23-04
    Migration to webpack 5            : done, 22-09,22-10
    Perf-tests overhaul                    :done, 23-02,23-04
    Migration to nx                          : 23-05,23-07
    Single version policy                 : 23-05,23-07
    Faster pipelines Epic                 : 23-04,23-09
    
```

**Comment by mshoho** [comment]
I suppose «Migrate to Node 16» should already be changed to «Migrate to Node 18». And why do we need to limit it from the top in the first place?
