### ISSUE TITLE
[Review] - Component usage guidance (Website) 

### ISSUE THREAD

**Issue by gouttierre** [microsoft/fluentui#25617]
**Component usage guides needing a review**

The following Figma guides have been created by the design team that require the right components owners to review, and confirm the usage guidelines is correct. Once reviewed and approved, these Figma pages will be built out by Tudor for the new website.

The Tech leads (@Hotell, @miroslavstastny,  @micahgodbolt, @behowell) to distribute the following to the right component owners for review:

- [ ] [Accordion usage guidance](https://www.figma.com/file/7X3Tgd3fTurii3FACrfhzo/Accordion?node-id=5671%3A129082)
- [ ] [Avatar usage guidance](https://www.figma.com/file/3SlxyaJA3tpLs5rVZ4oTVj/Avatar?node-id=5140%3A2606)
- [ ] [AvatarGroup usage guidance](https://www.figma.com/file/3SlxyaJA3tpLs5rVZ4oTVj/Avatar?node-id=5140%3A2606)
- [ ] [Badge usage guidance](https://www.figma.com/file/e0zRO2jOws26kqpJKvOgQS/Badge?node-id=4858%3A16603)
- [ ] [Button usage guidance](https://www.figma.com/file/Nj9EBBvOZmS11zKNJfilVR/Button?node-id=15583%3A21561)
- [ ] [Card usage guidance](https://www.figma.com/file/berhUBA6mJV9sCPpjgfKRj/Card?node-id=1520%3A5036)
- [ ] [Checkbox usage guidance](https://www.figma.com/file/1a1hBVizk7aLH76IvrnPFs/Checkbox?node-id=3690%3A8578)
- [ ] [Combobox usage  guidance](https://www.figma.com/file/pI5m9e9hsNkl1odWzxCxNd/Dropdown?node-id=7371%3A121612)
- [ ] [CompoundButton usage guidance](https://www.figma.com/file/Nj9EBBvOZmS11zKNJfilVR/Button?node-id=15583%3A21561)
- [ ] [Dialog usage guidance](https://www.figma.com/file/jtF47yOXDxkI00ZkydE999/Dialog?node-id=5180%3A36028)
- [ ] [Divider usage guideance](https://www.figma.com/file/TQO8qAOcrwU3ig2CTcan0e/Divider?node-id=1539%3A1644)
- [ ] [Dropdown usage guidance](https://www.figma.com/file/D3Rk6OfNCauW3py6liMwar/Combobox?node-id=7371%3A121651)
- [ ] [Input usage guidance](https://www.figma.com/file/TvHmWjZYxwtI9Tz6v5BT7E/Input?node-id=6771%3A37928)
- [ ] [Label usage guidance](https://www.figma.com/file/jpWO2FMBefirTyThf5Rg2P/Label?node-id=1657%3A783)
- [ ] [Link usage guidance](https://www.figma.com/file/ZhYpaByCXhprTWpF2097yE/Link?node-id=2295%3A2828)
- [ ] [MenuButton usage guidance](https://www.figma.com/file/Nj9EBBvOZmS11zKNJfilVR/Button?node-id=15583%3A21561)
- [ ] [Popover usage guidance](https://www.figma.com/file/j3IVtJidhjbqUzKulEeA5o/Popover?node-id=2006%3A10480)
- [ ] [Radio group usage guidance](https://www.figma.com/file/4XWsJrlpEcuEpUnZbtoIBU/Radio?node-id=2722%3A8111)
- [ ] [Select usage guidance](https://www.figma.com/file/0vOH481cv1VQyfQIX9JALn/Select?node-id=6803%3A2683)
- [ ] [Slider usage guidance](https://www.figma.com/file/IBCBJxEbPKS7CvLHG55Wn9/Slider?node-id=2957%3A7465)
- [ ] [SpiltButton usage guidance](https://www.figma.com/file/Nj9EBBvOZmS11zKNJfilVR/Button?node-id=15583%3A21561)
- [ ] [Spinner usage  guidance](https://www.figma.com/file/6kXOvdH8mTflgW2lGFYaEq/Spinner?node-id=3607%3A2495)
- [ ] [Switch usage guidance](https://www.figma.com/file/TPQVDN5cxYBqkP9urETsCp/Switch?node-id=2944%3A2995)
- [ ] [Text usage guidance](https://www.figma.com/file/IkBEp9pnO4Ep7HH4Bq5xrW/Text?node-id=2%3A1660)
- [ ] [Textarea usage guidance](https://www.figma.com/file/UVQP1vcIzaqavjxbDMXSA4/Textarea?node-id=2972%3A1521)
- [ ] [ToggleButton usage guidance](https://www.figma.com/file/Nj9EBBvOZmS11zKNJfilVR/Button?node-id=15583%3A21561)
- [ ] [Tooltip usage guidance](https://www.figma.com/file/oWREK4WSewfj6WfzBp0I4N/Tooltip?node-id=2656%3A1809)

For any open questions, or queries regarding the Figma specs, please cc @Lydia Mitchelson (Kforce) within the Figma's designs with your questions.

**Comment by Hotell** [comment]
we're missing figma files/specs

- text
- image
- card

**Comment by marcosmoura** [comment]
Added link for the card and text components

**Comment by gouttierre** [comment]
> Added links for the card and text components

@Hotell , @marcosmoura - I will confirm the below components `usage` Figma's with the design team. 

1. text
2. image
3. card

@tudorpopams - please, hold off on the impl of these 3 for now until I have confirmed the above. 
Gracias!
