### ISSUE TITLE
[Bug]: Table visual bug bash

### ISSUE THREAD

**Issue by yvonne-chien-ms** [microsoft/fluentui#25706]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
https://master--628d031b55e942004ac95df1.chromatic.com/?path=/docs/preview-components-table--default
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://master--628d031b55e942004ac95df1.chromatic.com/?path=/docs/preview-components-table--default

## Column header
- [x] Height should be 32px instead of 44px #25717
- [x] Sort arrow should use a 12px icon instead of 16px #25712
- [x] Sort arrow should have XXS (2px) padding-top (slight update to design to center align icon with the text) #25712
- [x] Gap between column header text and sort arrow icon should be XS (4px) instead of S (8px) #25712
<img width="457" alt="image" src="https://user-images.githubusercontent.com/91216814/202619959-6fd42876-e3b4-4a09-817a-0641aceab625.png">

## Row
- [x] Sizing names should be `extra-small`, `small`, and `medium` to match naming of other components #25713

## Row elements
- [x] Cell action buttons should use [Transparent appearance](https://www.figma.com/file/Nj9EBBvOZmS11zKNJfilVR/Button?node-id=4637%3A21130&viewport=77%2C811%2C0.23&t=AUEsOLeWHyMwzJIR-11) as default (shouldn't have a backplate on hover/pressed) #25628
- [x] Cell action buttons should be filled on hover/pressed #25715
- [x] Subtitle text in primary cell should be Caption 1 (currently Body 1) #25715
- [x] Icons in primary cells should be 24px (currently 28px)
- [x] Icons in extra-small rows should be 16px (currently 12px) #25764 
- [x] Icons in small and medium rows should be 20px (currently 14px) #25764

## Selection
- [x] Checkbox/radio cell should not have gray hover state when row is selected #25715
- [x] Circle inside selected radio should match sizing in `Radio` component – currently looks a few pixels larger #25715

## Keyboarding
- [x] Focus state should match `createFocusOutlineStyle` (black border instead of blue) #25715

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.
