### ISSUE TITLE
Combobox/Dropdown: updates from usability study

### ISSUE THREAD

**Issue by smhigley** [microsoft/fluentui#25724]
## Bug fixes
- [x] Fix dismiss after blur when opened via arrow click #25771
- [x] Always open the popup when typing #25769
- [x] Test virtual cursor interaction within listbox, particularly selection & dismissal

## Docs/examples
- [x] ~Use `preventSelectOnSpace` prop ONLY when most or all options will have a space, and typing the space is required and expected~ decision: hold off on `preventSelectOnSpace` unless/until someone requests it as a feature
- [x] For custom options, recommend string to be something like `Search “typed string”`
- [x] Use Select if mobile experience or macOS experience is most important
- [x] Recommend filtering as you type for Combobox, especially freeform
- [x] Update freeform example to filter as you type
- [x] Multiselect combobox should have docs discouraging using the text input value to display selection

## Minor updates
- [ ] Add “# Selected” string to multiselect - update: will make this an example. Adding an extra slot + making the strings internal does not seem like the best pattern
- [x] ~Space should always select, add prop with docs warning for `preventSelectOnSpace` #25914~ decision: hold off on `preventSelectOnSpace` unless/until someone requests it as a feature
- [x] Use `menuitemcheckbox` semantics for multiselect: #25905
- [x] Freeform should insert the typed option at the top of the children, and keep it there. Default to `"typed string"` (with quotation marks), with prop or slot to customize it. #26023
- [x] ~Resolve clear button placement with design~ Decision: keeping it in the header next to "X selected"

## Major updates
- [x] Multiselect combobox should keep a clear input value: #25898
- [ ] Open options in a panel/dialog on small screens
