### ISSUE TITLE
Updates to Fabric Core [Epic]

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#25868]
With an update adding the new m365 icons, this is a good time to do a full update on Fabric Core

- [x] Add new m365 icons to the Core icon set (leave the old office ones in there as deprecated)
- [x] Update **all** CDN references to use new cdn url (https://res-1.cdn.office.net/files/fabric-cdn-prod_20221201.001/assets/)
- [ ] update v8 website to use new version of core (and anywhere else using office.com logo) to show new m365 icons instead
