### ISSUE TITLE
setup v9 transpilation to be based on browser support minbar

### ISSUE THREAD

**Issue by TristanWatanabe** [microsoft/fluentui#26170]
## ISSUE 
Migrate v9 transpilation tooling to be based on browser support matrix. Use either `swc` or `babel` to replace `ts` transpilation to esm and commonjs.

## Steps: 
- [x] Update `migrate-converged-pkg` generator to add an `.swcrc` file to each v9 package which will contain `browserlist` data based on the full browser support matrix of v9. #26527
- [x] Adds `build:react-components` just-task to be used by v9 packages. The key difference here and the normal `build` task is that this now splits up transpilation and api-generation as two separate tasks. The transpilation portion uses SWC to transpile code down and then makes use of `babel` to transform griffel related code. Transpiling to `cjs` or `amd` will now use the already transpiled `esm` code output from SWC as a workaround to the issue where our `griffel` babel-preset is unable to directly parse `cjs` code transpiled by SWC (tracking [PR ](https://github.com/microsoft/griffel/pull/309)of ongoing work for this). This method allows for `@griffel/babel-preset` to still parse code as expected since it has no trouble transforming `esm` transpiled code from SWC. #26527
- [x] Run migration generator on all v9 library packages to migrate to using `swc` transpilation. #27250
- [x] ~Export `withFluentProvider` from `@fluentui/react-storybook-addon` package and explicitly declare it in the `@fluentui/vr-tests-react-components` storybook `preview.js` file so that the decorator is applied when storybook compiles via `build-storybook` script ([comment ](https://github.com/microsoft/fluentui/pull/26504#issuecomment-1405366675) where this workaround was discovered in test)~.  Fix issue causing `@fluentui/storybook-addon` to not be properly applied during `build-storybook` script #27006
- [x] Pin `puppeteer` to v19 to mitigate unresponsive perf-tests: #26965
- [x] Update `create-package` templates. #27286

## Long term: 
- [ ] Update migrate-converged-pkg workspace generator to use browser matrix target instead of `es2019`
- [ ] Run migration generator to update `.swcrc` files to use browser matrix target. #27036

**Comment by Hotell** [comment]
we have a workaround for https://github.com/microsoft/fluentui/issues/26251, but based on partner browser compliance we cannot use browserlist yet. should be revisited by the end of year

**Comment by Hotell** [comment]
keep open
