### ISSUE TITLE
DatePickerCompat

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#26244]
```[tasklist]
- [x] https://github.com/microsoft/fluentui/issues/26229
- [x] https://github.com/microsoft/fluentui/issues/26505
- [x] https://github.com/microsoft/fluentui/issues/26228
- [x] https://github.com/microsoft/fluentui/issues/26233
- [ ] https://github.com/microsoft/fluentui/issues/26237
- [ ] https://github.com/microsoft/fluentui/issues/27011
- [ ] https://github.com/microsoft/fluentui/issues/26235
- [ ] https://github.com/microsoft/fluentui/issues/26236
- [ ] https://github.com/microsoft/fluentui/issues/26232
- [ ] https://github.com/microsoft/fluentui/issues/26238
- [ ] https://github.com/microsoft/fluentui/issues/26239
- [x] https://github.com/microsoft/fluentui/issues/26227
- [x] https://github.com/microsoft/fluentui/issues/26225
- [x] https://github.com/microsoft/fluentui/issues/26226
- [ ] https://github.com/microsoft/fluentui/issues/26231
- [ ] https://github.com/microsoft/fluentui/issues/27207
- [ ] https://github.com/microsoft/fluentui/issues/26234
- [ ] https://github.com/microsoft/fluentui/issues/26230
- [ ] https://github.com/microsoft/fluentui/issues/26240
- [ ] https://github.com/microsoft/fluentui/issues/26241
- [ ] https://github.com/microsoft/fluentui/issues/26242
```

**Comment by JustSlone** [comment]
Closing since this is released
