### ISSUE TITLE
task: Implement standalone Field component

### ISSUE THREAD

**Issue by behowell** [microsoft/fluentui#26423]
Implement the changes described in:
* #26338

The work will be split into several stages:

```[tasklist]
### Tasks
- [x] https://github.com/microsoft/fluentui/issues/26424
- [x] https://github.com/microsoft/fluentui/issues/26425
- [ ] https://github.com/microsoft/fluentui/issues/26426
- [ ] #26599
- [ ] https://github.com/microsoft/fluentui/issues/26548
- [x] https://github.com/microsoft/fluentui/issues/26511
- [x] https://github.com/microsoft/fluentui/issues/26538
- [ ] https://github.com/microsoft/fluentui/issues/26728
```

**Comment by behowell** [comment]
The remaining work to clean up the deprecated Field shims is tracked by:
* #26728
