### ISSUE TITLE
Drawer

### ISSUE THREAD

**Issue by marcosmoura** [microsoft/fluentui#26420]
## Preparation

- [x] [Open UI Research](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#open-ui-research)
  - #26479
- [x] Issues related to component:
	- [x] #27328 (needed to add transition support for the Drawer) 
- [x] [Component Spec authored](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#component-spec) and [reviewed](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#spec-review)
    - [x] #27433

## Implementation

- [x] [Component implementation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#implementation)
	- [x] #27431
	- [x] #26554
	- [x] #27581
	- [x] #27582
	- [x] #27583
	- [x] #27830
- [x] Initial conformance and unit tests (validate basic functionality)
- [x] [Initial documentation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#documentation)
  - [x] [Storybook stories](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#storybook-stories)
  - [x] README.md covering basic usage
  - [x] MIGRATION.md guide (include v8 and v0)
- [x] [Component released as unstable](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#unstable-release) from `@fluentui/react-components/unstable`

## Validation

- [x] [Add tests](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#tests)
  - [x] Unit and conformance tests
  - [x] E2E tests
	  - [x] #29029
  - [x] VR tests
  - [x] Bundle size fixtures
  - [x] Performance test scenario
  - [x] Accessibility behavior tests
  - [x] Run [manual accessibility tests](https://github.com/microsoft/fluentui/wiki/Manual-Accessibility-Review-Checklist)
- [x] [Validate with partners](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#validation)
- [x] [Run a bug bash with other FUI crews](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#bug-bash)
	- [x] https://github.com/microsoft/fluentui/issues/29205
	- [x] https://github.com/microsoft/fluentui/issues/29207
	- [x] https://github.com/microsoft/fluentui/issues/29206
	- [x] https://github.com/microsoft/fluentui/issues/29241
	- [x] https://github.com/microsoft/fluentui/issues/29245
	- [x] https://github.com/microsoft/fluentui/issues/29243
	- [x] https://github.com/microsoft/fluentui/issues/29244
	- [x] https://github.com/microsoft/fluentui/issues/29208
	- [x] https://github.com/microsoft/fluentui/issues/29238
	- [x] https://github.com/microsoft/fluentui/issues/29206
- [x] [Finalize documentation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#finalize-documentation)
  - [x] Review and add any missing storybook stories
  - [x] Finalize migration guide
- [x] [Component released as stable](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#stable-release) from `@fluentui/react-components`
  - [x] Ensure exports are removed from from `@fluentui/react-components/unstable`
  - [x] In package.json: Remove the alpha/beta tag from the version number in package.json
  - [x] In package.json: Change beachball's `disallowedChangeTypes` to `"major", "prerelease"`

**Comment by ahmed-adly-khalil** [comment]
@marcosmoura we are desperate for a drawer, any luck that it's available in alpha / beta branch that we can use? 🙏

**Comment by marcosmoura** [comment]
@ahmed-adly-khalil 
The drawer will be soon as unstable. The next version of Fluent V9 will include all preview components for Drawer. Let me know if you have any questions about it.

**Comment by liuyulvv** [comment]
How to add opening and closing animation for Drawer?

**Comment by briandrouin** [comment]
test

**Comment by briandrouin** [comment]
test

**Comment by gouttierre** [comment]
Shipped to [Stable](https://react.fluentui.dev/?path=/docs/components-drawer--default)
