### ISSUE TITLE
Breadcrumb

### ISSUE THREAD

**Issue by ValentinaKozlova** [microsoft/fluentui#26480]
## Preparation

- [X] [Open UI Research](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#open-ui-research)
  - #26481 
- [X] [Open GitHub issues related to component](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#find-open-issues-on-github)
  - V8 Breadcrumb #24938
- [X] [Create react-breadcrumb and component from template]
  - [link to package: https://github.com/microsoft/fluentui/tree/master/packages/react-components/react-breadcrumb](https://github.com/microsoft/fluentui/tree/master/packages/react-components/react-breadcrumb)
- [X] (Optional) [Draft implementation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#draft-implementation)
  - #26608
- [X] [Component Spec authored](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#component-spec) and [reviewed](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#spec-review)
	- #26742

## Implementation

- [X] [Component implementation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#implementation)
	- #26529
	- #26693
	- #27199
	- #27428
	- #27471
	- #27520
	- #27649
	- #27699
	- #27742
	- #27859
	- #27918
	- #27969
	- #28046
	- #28267
	- #28295
- [X] Initial conformance and unit tests (validate basic functionality)
- [X] [Initial documentation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#documentation)
  - [X] [Storybook stories](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#storybook-stories)
         #27887 
  - [X] README.md covering basic usage
  - [X] MIGRATION.md guide (include v8 and v0)
          #27846
- [X] #28011 - we can't go unstable without this fix
- [X] [Component released as preview](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#unstable-release) from `@fluentui/react-components/unstable`
- #28402
Fixes:
- #28727
- #28720
- #28728
- #28767
- #28846
## Validation
- [X] [Add tests](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#tests)
  - [X] Unit and conformance tests
  - [X] VR tests
      - #28653
  - [X] Bundle size fixtures
  - [X] Performance test scenario
  - [X] Accessibility behavior tests
  - [X] Run [manual accessibility tests](https://github.com/microsoft/fluentui/wiki/Manual-Accessibility-Review-Checklist)
- [X] [Validate with partners](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#validation)
- [X] [Run a bug bash with other FUI crews](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#bug-bash)
- [X] [Finalize documentation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#finalize-documentation)
  - [X] Review and add any missing storybook stories
  - [X] Finalize migration guide
- [ ] [Component released as stable](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#stable-release) from `@fluentui/react-components`
  - [ ] In package.json: Remove the alpha/beta tag from the version number in package.json
  - [X] In package.json: Change beachball's `disallowedChangeTypes` to `"major", "prerelease"`

**Comment by gouttierre** [comment]
Shipped to [Stable](https://react.fluentui.dev/?path=/docs/components-breadcrumb--default)
