### ISSUE TITLE
Rating

### ISSUE THREAD

**Issue by TristanWatanabe** [microsoft/fluentui#26535]
💡 When you create a PR for any of the checklist items, add a link to this Epic under the PR's **Related Issues** section.

## Preparation

- [x] [Open UI Research](https://open-ui.org/research/component-matrix/)
- [x] [Open GitHub issues related to component](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#find-open-issues-on-github)
- [x] [Create react-\* package and component from template](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#component-package)
  - [link to package](https://github.com/microsoft/fluentui/tree/master/packages/react-components/react-rating-preview)
- [x] [Draft implementation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#draft-implementation)
  - [link to draft implementation](https://github.com/microsoft/fluentui/pull/29490)
- [x] [Component Spec authored](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#component-spec) and [reviewed](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#spec-review)

## Implementation

- [x] [Component implementation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#implementation)
- [x] Initial conformance and unit tests (validate basic functionality)
- [x] [Initial documentation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#documentation)
  - [x] [Storybook stories](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#storybook-stories)
  - [x] README.md covering basic usage
  - [x] MIGRATION.md guide (include v8 and v0)
- [x] [Component released as unstable](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#unstable-release) from `@fluentui/react-components/unstable`
  - [x] [Release Rating as Preview](https://github.com/microsoft/fluentui/pull/30153) 

## Validation

- [x] [Add tests](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#tests)
  - [x] Unit and conformance tests: #30414 
  - [x] VR tests: #30414 
  - [x] Bundle size fixtures
  - [x] Performance test scenario
  - [x] Accessibility behavior tests
  - [x] Create an issue and run [manual accessibility tests](https://github.com/microsoft/fluentui/wiki/Manual-Accessibility-Review-Checklist): #30471 
- [ ] [Validate with partners](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#validation)
- [ ] [Run a bug bash with other FUI crews](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#bug-bash)
- [ ] [Finalize documentation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#finalize-documentation)
  - [ ] Review and add any missing storybook stories
  - [ ] Finalize migration guide
- [ ] [Component released as stable](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#stable-release) from `@fluentui/react-components`
  - [ ] Ensure exports are removed from from `@fluentui/react-components/unstable`
  - [ ] In package.json: Remove the alpha/beta tag from the version number in package.json
  - [ ] In package.json: Change beachball's `disallowedChangeTypes` to `"major", "prerelease"`

**Comment by gouttierre** [comment]
📢"Tomi has a v1 ready to demo. He will put a meeting on our calendars to review it and go from there!"

**Comment by gouttierre** [comment]
📢 " @tomi-msft will share version one soon to share a demo prototype with `Olga`, `Toshie`, and the rest of the attendees."

**Comment by briandrouin** [comment]
Toshie to view Tomi's recording of demo and will connect async. Will need to do a spec review as well.

**Comment by gouttierre** [comment]
📢 "Most of the implementation is completed. Tomi has shared the demo. Toshie and folks are reviewing the demo to share feedback; followed with a spec review meeting which should be scheduled this or next week."

**Comment by gouttierre** [comment]
📢 
- In [preview](https://react.fluentui.dev/?path=/docs/preview-components-rating--default)
- Tomi made changes to the Rating Api based convos.  `Rating` and `RatingDisplay`. To split the component into two: One interactive component and another read only component, so that there is a clearer distinction on roles and stylings. RatingDisplay would be the read-only version, and Rating would be the interactive version. cc @tomi-msft , @behowell

**Comment by gouttierre** [comment]
📢
- Tomi is ready for the next steps to work with partner's on validation for `Rating`. There is a need to confirm the teams that are willing to help with that the validation process.. PM to check with designers (Toshie) and loop in engineering. cc @tomi-msft , @behowell

**Comment by gouttierre** [comment]
📢 
 - Teams will evaluate the Rating component with their adaptive card experiences.  cc @tomi-msft

**Comment by gouttierre** [comment]
📢 - Released to stable [Rating](https://react.fluentui.dev/?path=/docs/components-rating--default)
