### ISSUE TITLE
Toast

### ISSUE THREAD

**Issue by paulgildea** [microsoft/fluentui#26638]
💡 When you create a PR for any of the checklist items, add a link to this Epic under the PR's **Related Issues** section.

## Preparation

- [ ] [Open UI Research](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#open-ui-research)
  - [link to https://open-ui.org/]
- [x] [Open GitHub issues related to component](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#find-open-issues-on-github)
  - [link to each issue]
- [x] [Create react-\* package and component from template](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#component-package)
  - [link to package: https://github.com/microsoft/fluentui/tree/master/packages/react-components/react-(your-component)]
- [x] (Optional) [Draft implementation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#draft-implementation)
  - [link to draft implementation, if applicable]
- [ ] [Component Spec authored](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#component-spec) and [reviewed](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#spec-review)

## Implementation

- [x] [Component implementation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#implementation)
- [x] Initial conformance and unit tests (validate basic functionality)
- [x] [Initial documentation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#documentation)
  - [x] [Storybook stories](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#storybook-stories)
  - [ ] README.md covering basic usage
  - [ ] MIGRATION.md guide (include v8 and v0)
- [x] [Component released as unstable](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#unstable-release) from `@fluentui/react-components/unstable`
- [x] #27776
- [x] #27771
- [x] #27772
- [x] #27773
- [x] #27774
- [x] #27775
- [x] #27828

## Validation

- [x] [Add tests](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#tests)
  - [x] Unit and conformance tests
  - [x] VR tests
  - [x] Bundle size fixtures
  - [ ] Performance test scenario
  - [x] Accessibility behavior tests
  - [x] Create an issue and run [manual accessibility tests](https://github.com/microsoft/fluentui/wiki/Manual-Accessibility-Review-Checklist): #28417
- [ ] [Validate with partners](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#validation)
- [x] [Run a bug bash with other FUI crews](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#bug-bash)
- [x] [Finalize documentation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#finalize-documentation)
  - [x] Review and add any missing storybook stories
  - [x] Finalize migration guide (no equivalent component in v0/v8)
- [x] [Component released as stable](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#stable-release) from `@fluentui/react-components`
  - [x] Ensure exports are removed from from `@fluentui/react-components/unstable`
  - [x] In package.json: Remove the alpha/beta tag from the version number in package.json
  - [x] In package.json: Change beachball's `disallowedChangeTypes` to `"major", "prerelease"`
