### ISSUE TITLE
TeachingPopover

### ISSUE THREAD

**Issue by paulgildea** [microsoft/fluentui#26639]
💡 When you create a PR for any of the checklist items, add a link to this Epic under the PR's **Related Issues** section.

## Preparation

- [x] [Open UI Research](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#open-ui-research)
  - [link to https://open-ui.org/]
- [x] [Open GitHub issues related to component](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#find-open-issues-on-github)
  - [link to each issue]
- [x] [Create react-\* package and component from template](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#component-package)
  - [link to package: https://github.com/microsoft/fluentui/tree/master/packages/react-components/react-(your-component)]
- [x] (Optional) [Draft implementation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#draft-implementation)
  - [link to draft implementation, if applicable]
- [x] [Component Spec authored](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#component-spec) and [reviewed](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#spec-review)

## Implementation

- [x] [Component implementation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#implementation)
- [x] Initial conformance and unit tests (validate basic functionality)
- [x] [Initial documentation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#documentation)
  - [x] [Storybook stories](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#storybook-stories)
  - [x] README.md covering basic usage
  - [x] MIGRATION.md guide (include v8 and v0)
- [x] [Component released as unstable](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#unstable-release) from `@fluentui/react-components/unstable`

## Validation

- [x] [Add tests](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#tests)
  - [x] Unit and conformance tests
  - [x] VR tests
  - [x] Bundle size fixtures
  - [x] Performance test scenario
  - [x] Accessibility behavior tests
  - [x] Create an issue and run [manual accessibility tests](https://github.com/microsoft/fluentui/wiki/Manual-Accessibility-Review-Checklist): #30804
- [x] [Validate with partners](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#validation)
- [x] [Run a bug bash with other FUI crews](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#bug-bash)
- [x] [Finalize documentation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#finalize-documentation)
  - [x] Review and add any missing storybook stories
  - [x] Finalize migration guide
- [x] [Component released as stable](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#stable-release) from `@fluentui/react-components`
  - [x] Ensure exports are removed from from `@fluentui/react-components/unstable`
  - [x] In package.json: Remove the alpha/beta tag from the version number in package.json
  - [x] In package.json: Change beachball's `disallowedChangeTypes` to `"major", "prerelease"`

```[tasklist]
### Tasks
- [x] Improve carousel children pagination algorithm
- [x] Investigate alternative options to altStepText
- [x] Investigate TeachingPopoverPageCountChildRenderFunction  alternative options
- [x] Move page count icons to their own class for slot rendering multiple items
```

**Comment by briandrouin** [comment]
Testing

**Comment by briandrouin** [comment]
test

**Comment by briandrouin** [comment]
Karina is design contact for this work item.

ADO task

**Comment by Mitch-At-Work** [comment]
TeachingBubble draft/initial component implementation can be found here: https://github.com/microsoft/fluentui/pull/29739

**Comment by gouttierre** [comment]
📢" `Karina` met up with Mitch to talk about the integration of `motion`. Mitch's ETA for completion is still being determined, but it should be a short time. @Mitch-At-Work to confirm the possible ETA."

**Comment by briandrouin** [comment]
We should be having a spec review on this soon.

**Comment by Mitch-At-Work** [comment]
Teaching bubble functional implementation (V0) available for review: https://github.com/microsoft/fluentui/pull/29894

**Comment by gouttierre** [comment]
📢 
"Mitch has shared the PR that is in progress for review. Teaching bubble functional implementation (V0) available for review: https://github.com/microsoft/fluentui/pull/29894. The Design spec review will be happening soon; this week or next."

**Comment by gouttierre** [comment]
In [preview](https://react.fluentui.dev/?path=/docs/preview-components-teachingpopover--default)

**Comment by gouttierre** [comment]
📢 
- TeachingPopover release as stable with this week or next. PR will be submitted this week for team sign-off. (Mitch)

**Comment by gouttierre** [comment]
📢 
- Dev is hoping to land TeachingPopover this this week. 
- There is here is the stablization PR for TeachingPopover - [TeachingPopover: Stable Release by Mitch-At-Work · Pull Request #30884 · microsoft/fluentui (github.com)](https://github.com/microsoft/fluentui/pull/30884)
cc @Mitch-At-Work

**Comment by Mitch-At-Work** [comment]
TeachingPopover stable has now been merged: https://github.com/microsoft/fluentui/pull/31112

**Comment by gouttierre** [comment]
📢
- [TeachingPopover](https://react.fluentui.dev/?path=/docs/components-teachingpopover--default) is stable 🥳

cc @Mitch-At-Work , @brandonthomas , @tudorpopams
