### ISSUE TITLE
Nav

### ISSUE THREAD

**Issue by paulgildea** [microsoft/fluentui#26649]
💡 When you create a PR for any of the checklist items, add a link to this Epic under the PR's **Related Issues** section.

## Preparation

- [ ] [Open GitHub issues related to component](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#find-open-issues-on-github)
  - #29786
  - #29788
  - #29789
  - Create L2NavSectionHeader component
  - Create L2NavDrawer

- [x] [Create react-\* package and component from template](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#component-package)
  - [link to package](https://github.com/microsoft/fluentui/tree/master/packages/react-components/react-nav-preview)
- [ ] [Component Spec authored](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#component-spec) // using Figma for this.

## Implementation

- [ ] [Component implementation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#implementation)
- [ ] Initial conformance and unit tests (validate basic functionality)
- [ ] [Initial documentation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#documentation)
  - [ ] [Storybook stories](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#storybook-stories)
  - [ ] README.md covering basic usage
  - [ ] MIGRATION.md guide (include v8 and v0)
- [ ] [Component released as preview](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#preview-release)

## Validation

- [ ] [Add tests](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#tests)
  - [ ] Unit and conformance tests
  - [ ] VR tests
  - [ ] Bundle size fixtures
  - [ ] Performance test scenario
  - [ ] Accessibility behavior tests
  - [ ] Create an issue and run [manual accessibility tests](https://github.com/microsoft/fluentui/wiki/Manual-Accessibility-Review-Checklist): [link to issue]
- [ ] [Validate with partners](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#validation)
- [ ] [Run a bug bash with other FUI crews](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#bug-bash)
- [ ] [Finalize documentation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#finalize-documentation)
  - [ ] Review and add any missing storybook stories
  - [ ] Finalize migration guide
- [ ] [Component released as stable](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#stable-release)
  - [ ] Run the `prepare-initial-release` script to remove the `-preview` suffix from the package name
  - [ ] Deprecate the `-preview` package in NPM

**Comment by briandrouin** [comment]
Design contact: Leslie

[ADO task](https://uifabric.visualstudio.com/iss/_workitems/edit/8843)

**Comment by gouttierre** [comment]
📢"Still in progress with Mason and Leslie "

**Comment by brandonthomas** [comment]
Updating to target Q4 FY24. Leslie to be design spec complete by end of calendar year 2023.

**Comment by gouttierre** [comment]
📢"`Leslie` will inform `Mason` when the specification is ready, which will most likely completed by the end of the calendar year `2023`. `Leslie` is receiving more reviews on the spec as things develop." 
"Cc @JustSlone, this ETA was shifted to the new year, so we should communicate with the partners expecting the Nav control for this quarter."

**Comment by briandrouin** [comment]
@briandrouin  to follow up w/Leslie.

**Comment by gouttierre** [comment]
📢 "Leslie is still working on the design which is pretty much locked in. Leslie created a UX mechanical that she will be reviewing with Mason this week."

**Comment by Narvalex** [comment]
Hey guys, thanks for the great work.  Do we have any ETA on this? @mltejera

**Comment by gouttierre** [comment]
> Hey guys, thanks for the great work. Do we have any ETA on this? [@mltejera](https://github.com/mltejera)

Greetings, `Nav` is set to be in stable status by 30 April.

**Comment by gouttierre** [comment]
📢 
-  Leslie is still working on the design and shared the progress with Mason. Mason will focus on building out the accordion functionality; to handle the Nav opening and closing. cc @mltejera

**Comment by gouttierre** [comment]
📢 Not much change, Leslie been talking with Mason and Lydia about component part naming and weighing how changes might affect review PR review rounds. Design wise, Leslie building out the spec.

**Comment by gouttierre** [comment]
📢
 - Nav: Spec currently ongoing. Leslie's goal is to finish this week so she can get it out for review with partner teams next week. Behaviors have been pretty locked in for a while but things like names are still in flux.

**Comment by gouttierre** [comment]
📢 
- Spec behaviors are 95% done. Leslie will pick up the appearance columns (currently 30% done).

**Comment by gouttierre** [comment]
📢 
- Nav release as unstable within the week or next. Getting styling soon, Tabster functionality went in last week. (Mason)

**Comment by gouttierre** [comment]
📢 
- The design spec should be near competition. Check-in with Design on status (Leslie)
- Nav might be used for GPT and teams, need design alignment and reviews
- (Stephanie and Brandon) Check in with Yvonne and Chris Holt on the design and code alignment for the GPT work.

cc @mltejera , @stapple3, @brandonthomas

**Comment by gouttierre** [comment]
📢

- In ⁠[preview](https://react.fluentui.dev/?path=/docs/preview-components-nav--nav-drawer-default) 🎬
- Mason and Leslie met up with BizChat. Shan mentioned a September launch for copilot updates.
- Mason and Leslie will include all items discussed in the GitHub issue for organization and to estimate the effort required. This GitHub issue should be added to the Roadmap and connected to the Nav Epic, should there be any differences with this particular GitHub epic.
- Leslie and Mason to create a plan for each discussed item, categorizing them into actionable buckets.
- Mason will investigate and fix the bug related to setting custom width in the Nav preview component.
- Fluent team must determine which items will be implemented by the Fluent team, contributed by the Copilot team, or implemented locally by the Copilot team. Loop in Fluent AI team going forward.

cc @mltejera , @brandonthomas, @JustSlone , @paulgildea , @micahgodbolt, @tudorpopams

**Comment by gustaferiksson** [comment]
Hi @gouttierre, Is there an ETA for the nav component? 

It seems to have been pushed further and further into the future for some time now. :)

**Comment by gustaferiksson** [comment]
@ivi-hamiti Unfortunately we don't allow the usage of non-production ready packages. Thanks for the suggestion though!

**Comment by Skagevang** [comment]
Hi. Is there an update on ETA for this component? [33557](https://github.com/microsoft/fluentui/issues/33557) is holding me back from using this even in preview

**Comment by sydsutton** [comment]
@gouttierre @mltejera Hey guys, are there any updates for the Nav component? There are a lot of people very excited to use this in production, but we haven't heard anything for almost 7 months now. Plus, it's been over a year since it was first set to be released as `stable`-- we're starting to get light-headed from the breath-holding 😮‍💨

**Comment by gouttierre** [comment]
📢 `Nav` is now [stable](https://react.fluentui.dev/?path=/docs/components-nav--docs)
