### ISSUE TITLE
TagPicker

### ISSUE THREAD

**Issue by paulgildea** [microsoft/fluentui#26652]
💡 When you create a PR for any of the checklist items, add a link to this Epic under the PR's **Related Issues** section.

## Preparation

- [ ] [Open UI Research](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#open-ui-research)
  - [link to https://open-ui.org/]
- [x] [Create react-\* package and component from template](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#component-package)
  - https://github.com/microsoft/fluentui/tree/master/packages/react-components/react-tag-picker-preview
- [x] [Component Spec authored](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#component-spec) and [reviewed](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#spec-review) https://github.com/microsoft/fluentui/pull/31000

## Implementation

- [x] [Component implementation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#implementation)
- [x] Initial conformance and unit tests (validate basic functionality) https://github.com/microsoft/fluentui/pull/31004
- [ ] [Initial documentation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#documentation)
  - [x] [Storybook stories](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#storybook-stories)
  - [x] README.md covering basic usage https://github.com/microsoft/fluentui/pull/31016
  - [ ] MIGRATION.md guide (include v8 and v0)

## Validation

- [ ] [Add tests](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#tests)
  - [x] Unit and conformance tests https://github.com/microsoft/fluentui/pull/31004
  - [x] VR tests (https://github.com/microsoft/fluentui/pull/31219)
  - [x] Bundle size fixtures https://github.com/microsoft/fluentui/pull/31023
  - [ ] Performance test scenario
  - [x] Accessibility behavior tests https://github.com/microsoft/fluentui/pull/31004
  - [x] Create an issue and run [manual accessibility tests](https://github.com/microsoft/fluentui/wiki/Manual-Accessibility-Review-Checklist): https://github.com/microsoft/fluentui/issues/31037
- [x] [Validate with partners](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#validation)
- [x] [Run a bug bash with other FUI crews](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#bug-bash)
- [x] [Finalize documentation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#finalize-documentation)
  - [x] Review and add any missing storybook stories
  - [ ] Finalize migration guide
- [ ] [Component released as stable](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#stable-release) from `@fluentui/react-components`
  - [ ] Ensure exports are removed from from `@fluentui/react-components/unstable`
  - [ ] In package.json: Remove the alpha/beta tag from the version number in package.json
  - [ ] In package.json: Change beachball's `disallowedChangeTypes` to `"major", "prerelease"`

## Dev TODOs
- [x] Make combobox active descendant implementation not reliant on react state
- [x] Remove usages of `ComboboxContext` that overlaps with `ListboxContext`
- [x] Encapsulate slot logic for combobox and extract
- [x] Recompose listbox so it's used as a standalone component in the picker
- [x] Recompose TagGroup so that it works with the combobox selection state
- [x] Different input types should be possible through composition instead of entirely different control (input/button)
- [x] Recompose option to include desired entity layout
- [x] Override combobox behaviour that keeps multiselect variants open
- [x] Extract styles from react-combobox and reuse + override
- [x] #30831
- [x] Figure out how to use the picker with [useComboboxFilter](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-combobox/src/hooks/useComboboxFilter.tsx)
- [x] Position expand icon correctly when scrollbar appears
- [x] Implement option grouping (https://github.com/microsoft/fluentui/pull/30934)
- [x] Implement size prop - most likely need to update react-tags package to add size customization (https://github.com/microsoft/fluentui/pull/30742)
- [x] Decide on API or code sameple to align popver to editable area only
- [x] Recompose `Tag` component to include defaults (i.e. always dismissble) (https://github.com/microsoft/fluentui/pull/30800)
- [x] Address TODOs in code
- [x] Design polish
- [x] Implement secondary action as unstable feature (https://github.com/microsoft/fluentui/pull/30829)
- [x] Ensures `disabled` state works properly between all controllers (https://github.com/microsoft/fluentui/pull/30822)
- [x] add `freeform` support https://github.com/microsoft/fluentui/pull/30947

**Comment by pradeept95** [comment]
Can we have implementation of this component accelerated in V9 please. This is the one major component, and because of it we are not able to completely move to V9. We have both V8 and V9 dependencies on our projects and PeoplePicler is the one major component which is stopping us to get rid of V8 dependencies in our projects.

**Comment by briandrouin** [comment]
Design Contact: Toshie

[ADO task](https://uifabric.visualstudio.com/iss/_workitems/edit/8364)

**Comment by gouttierre** [comment]
📢"A meeting to align with Teams team and the designers will be scheduled. In the interim, Toshie has aligned with Ling to share implementation thoughts."

**Comment by miroslavstastny** [comment]
Moving the ETA from Dec 2023 to Feb 2024. We are currently in a prototyping phase, missing design spec.
cc @gouttierre

**Comment by gouttierre** [comment]
📢
- "A meeting was held with the design and engineering teams, and Toshie met with the Outlook team to discuss their needs. 
- "Additionally, `Toshie` synced with `Bret` and `Kay` to discuss `accessibility`. 
- "Teams have updated the ETA from `Dec 2023` to `Feb 2024` as they are currently in the prototyping phase." 
- "`Toshie` to confirm the `possible ETA` for the `design spec completion`." 
"cc @JustSlone here is another component that has shifted, and we should let partners know the new ETA."

**Comment by briandrouin** [comment]
Ling is prototyping, Toshie is working on spec.

**Comment by gouttierre** [comment]
📢"Ling is doing the implementation and prototyping. Toshie is moving forward with the design spec and addressing the accessibility concerns with Kay."

**Comment by gouttierre** [comment]
📢 
- `Ling` is working on PeoplePicker this quarter, starting with some perf improvements to the combobox w/ changes so that more of that component can be reusable. `Toshie` / `Emily` has a design review to update ethe spec and Ling will review the changes in the spec.

**Comment by gouttierre** [comment]
📢 
- Viva Goals is asking for the component. Toshie will connect with Rahul. Viva Goals is also looking for Trees in a Table component, i.e. like a detailed list point of view; trees in a DataGrid and pickers.

**Comment by gouttierre** [comment]
📢 
- Ling is working to get the component shipped this quarter in preview but the risk of it being delayed. cc @tudorpopams , @JustSlone

**Comment by gouttierre** [comment]
📢
- Ling has been advancing his code branch well, which Bernardo will take over when he is back from his time off next week. . cc @tudorpopams , @JustSlone, @ling1726

**Comment by gouttierre** [comment]
📢
- PeoplePicker now became TagPicker. [TBD]. We're mainly missing: (`option grouping`, `size/appearance, `align popover to text editor`). 
- Bernardo thinks it's possible to release preview without (1) and (3) by next 2 weeks. 
- Ling mentioned that only size/appearance (2) is needed for Teams. 
- Gouttierre checked with folks at Viva
- Updated ETA April.

**Comment by bsunderhus** [comment]
First preview release officially available https://www.npmjs.com/package/@fluentui/react-tag-picker-preview

**Comment by pradeept95** [comment]
Hi @bsunderhus ,
I exported example to `Stackblitz` and I got following error. It is same for local project as well!

✘ [ERROR] Could not resolve "../../../react-combobox/src/utils/useOptionCollection"

    node_modules/@fluentui/react-tag-picker-preview/lib/utils/useComboboxBaseState.js:2:36:
      2 │ ...ion } from '../../../react-combobox/src/utils/useOptionCollection';
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../../../react-combobox/src/utils/useSelection"

    node_modules/@fluentui/react-tag-picker-preview/lib/utils/useComboboxBaseState.js:3:29:
      3 │ ...eSelection } from '../../../react-combobox/src/utils/useSelection';
        ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error: Build failed with 2 errors:
node_modules/@fluentui/react-tag-picker-preview/lib/utils/useComboboxBaseState.js:2:36: ERROR: Could not resolve "../../../react-combobox/src/utils/useOptionCollection"
node_modules/@fluentui/react-tag-picker-preview/lib/utils/useComboboxBaseState.js:3:29: ERROR: Could not resolve "../../../react-combobox/src/utils/useSelection"
    at failureErrorWithLog (/home/projects/iz2jvs--run/node_modules/esbuild/lib/main.js:1641:15)
    at eval (/home/projects/iz2jvs--run/node_modules/esbuild/lib/main.js:1049:25)
    at eval (/home/projects/iz2jvs--run/node_modules/esbuild/lib/main.js:1517:9) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]

Link : https://stackblitz.com/run?file=src%2Fexample.tsx

![image](https://github.com/microsoft/fluentui/assets/28040299/2cc95d54-c561-44a1-9abd-d0c43a2cfb47)

**Comment by bsunderhus** [comment]
> Hi @bsunderhus , I exported example to `Stackblitz` and I got following error. It is same for local project as well!
> 
> ✘ [ERROR] Could not resolve "../../../react-combobox/src/utils/useOptionCollection"
> 
> ```
> node_modules/@fluentui/react-tag-picker-preview/lib/utils/useComboboxBaseState.js:2:36:
>   2 │ ...ion } from '../../../react-combobox/src/utils/useOptionCollection';
>     ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```
> 
> ✘ [ERROR] Could not resolve "../../../react-combobox/src/utils/useSelection"
> 
> ```
> node_modules/@fluentui/react-tag-picker-preview/lib/utils/useComboboxBaseState.js:3:29:
>   3 │ ...eSelection } from '../../../react-combobox/src/utils/useSelection';
>     ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```
> 
> Error: Build failed with 2 errors: node_modules/@fluentui/react-tag-picker-preview/lib/utils/useComboboxBaseState.js:2:36: ERROR: Could not resolve "../../../react-combobox/src/utils/useOptionCollection" node_modules/@fluentui/react-tag-picker-preview/lib/utils/useComboboxBaseState.js:3:29: ERROR: Could not resolve "../../../react-combobox/src/utils/useSelection" at failureErrorWithLog (/home/projects/iz2jvs--run/node_modules/esbuild/lib/main.js:1641:15) at eval (/home/projects/iz2jvs--run/node_modules/esbuild/lib/main.js:1049:25) at eval (/home/projects/iz2jvs--run/node_modules/esbuild/lib/main.js:1517:9) { errors: [Getter/Setter], warnings: [Getter/Setter]
> 
> Link : https://stackblitz.com/run?file=src%2Fexample.tsx
> 
> ![image](https://private-user-images.githubusercontent.com/28040299/318411260-2cc95d54-c561-44a1-9abd-d0c43a2cfb47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDQ5MDAsIm5iZiI6MTcxMjA0NDYwMCwicGF0aCI6Ii8yODA0MDI5OS8zMTg0MTEyNjAtMmNjOTVkNTQtYzU2MS00NGExLTlhYmQtZDBjNDNhMmNmYjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA3NTY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNjViNWEzOWUzZDBkMzViODZkNzNiODQ2ZTgzOTEzNmU4MDM0YTU3ODA0N2U4YjYyMTgzNzI4OTk3Y2EzZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7eC6cclqNtbq9Movj1MmSlhyHxCsYQVb42j1qWso1Lg)

Thanks for the catch @pradeept95, I'll investigate it immediately!

**Comment by pradeept95** [comment]
Thank you so much it is working now!

Hi @bsunderhus ,
Quick question: I am using filtering option in TagPicker but when I type space in keyboard it select the first highlighted option, is there any way I can prevent that, Because I am using async denounced call to backend API while user typing name in the TagPickerInput field and api might have return intermediate multiple options  but user still typing to filter out more which might contains space as well.

**Comment by bsunderhus** [comment]
> Thank you so much it is working now!
> 
> Hi @bsunderhus , Quick question: I am using filtering option in TagPicker but when I type space in keyboard it select the first highlighted option, is there any way I can prevent that, Because I am using async denounced call to backend API while user typing name in the TagPickerInput field and api might have return intermediate multiple options but user still typing to filter out more which might contains space as well.

This seems like the request to support `freeform` https://react.fluentui.dev/?path=/docs/components-combobox--default#freeform

I'll take a look into it! 💪🏼

**Comment by bsunderhus** [comment]
> Thank you so much!

Newest version is available with `freeform` support

**Comment by pradeept95** [comment]
Thank you so much. Indeed, solved my use case!

**Comment by pradeept95** [comment]
I have created two new issues related to this component:
1. #30984 
2. #30978

Please let me know if you have any questions!

**Comment by bsunderhus** [comment]
> I have created two new issues related to this component:
> 
> 1. [[Bug]: TagPicker (react-tag-picker-preview) - Keyborg instance k* is being disposed incorrectly #30984](https://github.com/microsoft/fluentui/issues/30984)
> 2. [[Bug]: TagPicker (react-tag-picker-preview) - not working with Field #30978](https://github.com/microsoft/fluentui/issues/30978)
> 
> Please let me know if you have any questions!

Thanks @pradeept95 , I'll follow them up. The keyborg related I believe it has nothing to do with TagPicker itself, we were having a similar issue with other Tabster related components

**Comment by pradeept95** [comment]
Awesome, Thank you so much @bsunderhus!

**Comment by gouttierre** [comment]
📢 
- The team has got two big tasks to complete for the stable release: 
  1. A bug-bash (it's ongoing from 29th April)
  2. To compile a manual accessibility checklist. Dev is almost done, but needs some assistance in testing on all screen readers [#31037]
- Due to the renaming task and the upcoming bank holidays in the next two weeks, we have to postpone the stable release by a week.
- PM to communicate to partners about the week delay.

cc @bsunderhus , @ling1726, @tudorpopams , @JustSlone

**Comment by pradeept95** [comment]
Hi @bsunderhus I have reported this issue, but what do you think about this? It seems bug to me!

https://github.com/microsoft/fluentui/issues/31259

**Comment by bsunderhus** [comment]
> Hi @bsunderhus I have reported this issue, but what do you think about this? It seems bug to me!
> 
> #31259

It is not a bug @pradeept95, after some discussions and investigations from our a11y champions, we've decided to go with this behaviour. Both `Space` and `Enter` click when selecting an option will close the dropdown

**Comment by ravindersharma** [comment]
Hi @bsunderhus ,

I recently switched from PeoplePicker to TagPicker for the Fluent UI V8 version.   However, there's an issue, which is related TagPickerOption, which is dependent on the Text (String) Property only and does not allow us to add other components as children. The Persona control loaded into TagPickerOption without any issues, but the Filter function started behaving weirdly when I tried to utilize it. I attached screenshot for both. 

![image](https://github.com/microsoft/fluentui/assets/10610076/f26f4ff5-f397-4c27-ba62-0c16e9a35efb)

![image](https://github.com/microsoft/fluentui/assets/10610076/0f1747f6-8a4b-4a38-bf68-b950d5ad9858)

**Comment by bsunderhus** [comment]
> Hi @bsunderhus ,
> 
> I recently switched from PeoplePicker to TagPicker for the Fluent UI V8 version. However, there's an issue, which is related TagPickerOption, which is dependent on the Text (String) Property only and does not allow us to add other components as children. The Persona control loaded into TagPickerOption without any issues, but the Filter function started behaving weirdly when I tried to utilize it. This is because, the filter feature works on Text instead of any other component. If we could successfully add a text property to TagPickeroption and use it for the filter, that would be ideal. Or do we have an other option for it. I attached screenshot for both.
> 
> Here is a reference to the post that I followed to use it: #29941
> 
> ![image](https://private-user-images.githubusercontent.com/10610076/331580610-a1c40ff4-4aff-44b9-be01-1d7bb3970e19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTY4MTUsIm5iZiI6MTcxNjIxNjUxNSwicGF0aCI6Ii8xMDYxMDA3Ni8zMzE1ODA2MTAtYTFjNDBmZjQtNGFmZi00NGI5LWJlMDEtMWQ3YmIzOTcwZTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE0NDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MjVkYmMxNWVlNDc5M2I3OGUwNGY2YTA4NmE5ZTVmYTNlNTljZjdhYmJlYzkzMTM1NTNjNDAzZjQwN2QzMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bil4eBQQnOADXAfXL3r-7UcXo449Zh_OyPTdPWQSgPo)
> 
> ![image](https://private-user-images.githubusercontent.com/10610076/331548696-0f1747f6-8a4b-4a38-bf68-b950d5ad9858.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTY4MTUsIm5iZiI6MTcxNjIxNjUxNSwicGF0aCI6Ii8xMDYxMDA3Ni8zMzE1NDg2OTYtMGYxNzQ3ZjYtOGE0Yi00YTM4LWJmNjgtYjk1MGQ1YWQ5ODU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE0NDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxOGViZWZiYWFmM2M5ZTY4OGI0NWU2Y2ZkNWZhMDdiYTE4ZTgyZDA3N2ExYWFkZDliYmZkMmJlODBjMmUzNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IR53Fp0Y4Gd-Dt6hCx9POQSa6RuYJUwZ7Q-3krUZmps)

Hey there @ravindersharma, would you mind following up with a Feature request with an implementation detail and also some reproduction on why is this not working today?  https://github.com/microsoft/fluentui/issues/new?assignees=&labels=Type%3A+Feature%2CNeeds%3A+Triage+%F0%9F%94%8D&projects=&template=feature-request.yml&title=%5BFeature%5D%3A+

**Comment by ravindersharma** [comment]
> > Hi @bsunderhus ,
> > I recently switched from PeoplePicker to TagPicker for the Fluent UI V8 version. However, there's an issue, which is related TagPickerOption, which is dependent on the Text (String) Property only and does not allow us to add other components as children. The Persona control loaded into TagPickerOption without any issues, but the Filter function started behaving weirdly when I tried to utilize it. This is because, the filter feature works on Text instead of any other component. If we could successfully add a text property to TagPickeroption and use it for the filter, that would be ideal. Or do we have an other option for it. I attached screenshot for both.
> > Here is a reference to the post that I followed to use it: #29941
> > ![image](https://private-user-images.githubusercontent.com/10610076/331580610-a1c40ff4-4aff-44b9-be01-1d7bb3970e19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTY4MTUsIm5iZiI6MTcxNjIxNjUxNSwicGF0aCI6Ii8xMDYxMDA3Ni8zMzE1ODA2MTAtYTFjNDBmZjQtNGFmZi00NGI5LWJlMDEtMWQ3YmIzOTcwZTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE0NDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MjVkYmMxNWVlNDc5M2I3OGUwNGY2YTA4NmE5ZTVmYTNlNTljZjdhYmJlYzkzMTM1NTNjNDAzZjQwN2QzMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bil4eBQQnOADXAfXL3r-7UcXo449Zh_OyPTdPWQSgPo)
> > ![image](https://private-user-images.githubusercontent.com/10610076/331548696-0f1747f6-8a4b-4a38-bf68-b950d5ad9858.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTY4MTUsIm5iZiI6MTcxNjIxNjUxNSwicGF0aCI6Ii8xMDYxMDA3Ni8zMzE1NDg2OTYtMGYxNzQ3ZjYtOGE0Yi00YTM4LWJmNjgtYjk1MGQ1YWQ5ODU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE0NDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxOGViZWZiYWFmM2M5ZTY4OGI0NWU2Y2ZkNWZhMDdiYTE4ZTgyZDA3N2ExYWFkZDliYmZkMmJlODBjMmUzNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IR53Fp0Y4Gd-Dt6hCx9POQSa6RuYJUwZ7Q-3krUZmps)
> 
> Hey there @ravindersharma, would you mind following up in a [Feature request](https://github.com/microsoft/fluentui/issues/new?assignees=&labels=Type%3A+Feature%2CNeeds%3A+Triage+%F0%9F%94%8D&projects=&template=feature-request.yml&title=%5BFeature%5D%3A+) with an implementation detail and also some reproduction on why is this not working today?

Hi @bsunderhus , As You have suggested,  I have added it, here it is: [https://github.com/microsoft/fluentui/issues/31431](url)
