### ISSUE TITLE
[Epic]: 1JS Visual Regression Tool feature suggestions 

### ISSUE THREAD

**Issue by TristanWatanabe** [microsoft/fluentui#26744]
## Story:
- This issue will serve as the main hub for any 1JS VR tool feature requests that you may have. Please add a comment to this issue for any requests you may have and then update this issue.

### Feature Requests:
- [ ] Have VR results be integrated as blocking github checks.
- [ ] "Magnify" feature does not zoom in to the component in snapshot
		- Example: Open [link ](https://staticpagerelease.z16.web.core.windows.net/azurestaticapps/vr-fluent/index.html?organization=uifabric&project=fabricpublic&prId=26725&commitId=df778e39c0c3daaa507128377960e6a391372506&env=prod), click on VR result and click on magnify to observe issue. 
- [ ] A way to view ALL existing snapshots (changed and unchanged)

**Comment by layershifter** [comment]
+ make screenshots/differences visible for non authorized users, so third party contributors can check regressions

**Comment by Hotell** [comment]
any progress on this ?

**Comment by Hotell** [comment]
we will ping folks owning storywright and close/keep-open this based on their status.

**Comment by layershifter** [comment]
keep open
