### ISSUE TITLE
BasicList

### ISSUE THREAD

**Issue by paulgildea** [microsoft/fluentui#27382]
💡 When you create a PR for any of the checklist items, add a link to this Epic under the PR's **Related Issues** section.

## Preparation

- [x] [Open UI Research](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#open-ui-research)
  - [link to https://open-ui.org/]
- [x] [Open GitHub issues related to component](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#find-open-issues-on-github)
  - [link to each issue]
- [x] [Create react-\* package and component from template](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#component-package)
  - [link to package: https://github.com/microsoft/fluentui/tree/master/packages/react-components/react-(your-component)]
- [x] (Optional) [Draft implementation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#draft-implementation)
  - [link to draft implementation, if applicable]
- [x] [Component Spec authored](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#component-spec) and [reviewed](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#spec-review)

## Implementation

- [x] [Component implementation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#implementation)
- [x] Initial conformance and unit tests (validate basic functionality)
- [x] [Initial documentation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#documentation)
  - [x] [Storybook stories](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#storybook-stories)
  - [x] README.md covering basic usage
  - [x] MIGRATION.md guide (include v8 and v0)
- [x] [Component released as unstable](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#unstable-release) from `@fluentui/react-components/unstable`

## Validation

- [ ] [Add tests](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#tests)
  - [x] Unit and conformance tests
  - [x] VR tests  - _N/A, The List itself doesn't have any visuals out of the box_
  - [x] #31656
  - [x] #31659
  - [x] Accessibility behavior tests
  - [ ] Create an issue and run [manual accessibility tests](https://github.com/microsoft/fluentui/wiki/Manual-Accessibility-Review-Checklist): [link to issue]
- [x] [Validate with partners](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#validation)
- [x] [Run a bug bash with other FUI crews](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#bug-bash)
- [x] [Finalize documentation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#finalize-documentation)
  - [x] Review and add any missing storybook stories
  - [x] Finalize migration guide
- [ ] [Component released as stable](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#stable-release) from `@fluentui/react-components`
  - [ ] Ensure exports are removed from from `@fluentui/react-components/unstable`
  - [ ] In package.json: Remove the alpha/beta tag from the version number in package.json
  - [ ] In package.json: Change beachball's `disallowedChangeTypes` to `"major", "prerelease"`

**Comment by gouttierre** [comment]
📢 "Leslie is exploring the differences between BasicList and DataGrid with Sarah and the component club. The investigation process is ongoing, and the PM has pushed the end date to December. Jiri is testing components to see what engineering can accomplish."

**Comment by gouttierre** [comment]
📢
-  "Leslie & Lydia are editing the Decision Tree and discussing what a spec would look like in defining what a List should do and the types of things contained within. They plan to repurpose some parts of DataGrid and discuss with Toshie."
- "Leslie & Lydia will work together on a Usage Guidance doc as a part of the spec, which will be shared with the Development team. The design team feels this will be ready for handoff to DEV in the new year and will have a more concrete update after the next few weeks." 
- "Jiri is ready to demo the prototype/interactions and talk about some of the limitations he found."

**Comment by miroslavstastny** [comment]
@gouttierre - moving the ETA to Mar 2024 as the design spec is still not available

**Comment by gouttierre** [comment]
📢 "Brian scheduled a follow up for the designers and engineering to meet on the 30th." "Jiri is ready to demo the prototype/interactions and talk about some of the limitations he found."

**Comment by gouttierre** [comment]
📢 
"Leslie/ Brian will confirm the design spec commitment date in the new year. Jiri shared the prototype with the design team and  created the PR for List shim"

**Comment by gouttierre** [comment]
📢 
- Leslie shared some thoughts around aria roles in what they are proposing. 
- Milan watched the recording and shared thoughts on the navigation which Jiri agrees with as it "covers" the gap between what is a list with multiple actions and what is a data grid. 
- Another meeting might be needed where Brett can join as well to weigh in.

**Comment by gouttierre** [comment]
📢 
"Jiri has a new keyboard navigation pattern which takes inspiration from Treegrid and Datagrid. Jiri will schedule a meeting for some time this week to sync on progress"

**Comment by gouttierre** [comment]
📢 
- Jiri demonstrated the accessibility roles and their limitations in different scenarios of grid / list navigation. 
- He showed how the final navigation would work in various use-cases. The narrator for the grid / experience could be improved . 
- The devs need to polish the code examples for the accessibility patterns and will speak with Sarah.
- Leslie will watch the recording

**Comment by gouttierre** [comment]
📢 
 - Leslie's waiting for a link to Jiri's PR and decision tree. Leslie is going to take a stab at seeing what they can combine with their design-decision tree for one tree to rule them all. Since we're leading with usage guidance and examples, it would be helpful to have Lydia's help on this when she's back from vacation and ramped up.  - @george-cz

**Comment by gouttierre** [comment]
📢 
- This week, Leslie will review the decision tree. 
- Jiri, will continue working on the list documentation and include the selection and primary actions. Also, Jiri, will update everything to match the new changes.

**Comment by gouttierre** [comment]
📢 
- Design and engineering had met to review Jiri's shared examples in the doc. 
- Jiri is looking to incorporate some of his super thorough markup doc into the actual documentation. 
- Lydia and Leslie are making adjustments to the decision tree and usage guidance, then talking about what this means for the spec components. 

cc @george-cz , @tudorpopams

**Comment by gouttierre** [comment]
📢
- Per request from Design (Kari / Roma). List design work will be put on hold for 4-6 weeks so design (Leslie) can help another initiative. 
- Teams (Ling) is aware and will shift Teams ETA to uptake List to June.
- Design (Leslie) will have a completed design spec ready, no later than the 30th May.
- The ETA for List to stable has been updated to June.

cc @george-cz, @ling1726, @tudorpopams , @miroslavstastny , @JustSlone

**Comment by gouttierre** [comment]
📢
- List is in [preview](https://react.fluentui.dev/?path=/docs/preview-components-list--default)
- ETA for a stable version is by the end of August, following the completion of partner feedback during the validation phase.

cc @george-cz , @khmakoto , @paulgildea , @tudorpopams , @JustSlone

**Comment by gouttierre** [comment]
📢
- The Engineering lead is currently prioritizing reflow work due to its higher importance.
- The team is awaiting on feedback from internal partners during preview before moving towards a stable.
- Given the current progress, we anticipate achieving stability before the end of September.

cc~ @george-cz , @tudorpopams , @paulgildea , @JustSlone

**Comment by gouttierre** [comment]
📢

- All required development, bug bashing, designs are completed [[preview](https://react.fluentui.dev/?path=/docs/preview-components-list--default)] and partners are validating.
- React team is still awaiting partners privacy approvals before activation in R0 to use Fluentv9 List and ListItem component instead of the TACO table; then only can List can moved to stable.

cc @george-cz , @tudorpopams , @paulgildea

**Comment by gouttierre** [comment]
📢
- Shipped to stable. [Storybook React v9](https://react.fluentui.dev/?path=/docs/components-list--docs)

**Comment by sydsutton** [comment]
Hey, @gouttierre , any idea when a new version will be pushed out with this update? Usually the storybook is aligned with what's available in the most recent version. Thanks.
