### ISSUE TITLE
ColorPickerCompat

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#27734]
Issues to complete for ColorPicker compat to be complete:

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/fluentui/issues/28055
- [ ] Copy over files
- [ ] Remove v8 Dependencies
- [ ] Review and write up takeaways from this [codesandbox](https://codesandbox.io/s/rough-lake-pljz7r?file=/src/ToggleColorPickerButton.tsx)
```
