### ISSUE TITLE
Fluent UI Web Components v3 beta release

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#27793]
## Problem

As we are getting closer to an initial beta release of Web Components v3, this document defines what Preview (and Final) version is and will track the required work for the release.

## What is Preview

Beta is ready for use in production but may have breaking API changes before becoming final and has higher risk of bugs.

- [x] Works with browser matrix -> @procload
- [x] Passes manual a11y test pass -> @procload
- [x] Touch test -> @procload  
- [ ] Has unit tests #28078 -> @chrisdholt, team
  - check what Fast Foundation does, see what we should and could cover
  - can we do "50% of API coverage" bar?
  - think about conformance tests
- [x] Has screenshot tests #28079 -> @miroslavstastny 
  - light and dark theme
  - forced-colors HC
  - rtl (+ rtl support in storybook)
- [ ] Aligns with FUIR9: v9 - wc comparison #28081 [P2 - not blocking]
  - manual spec approval pass for every component? by design team?
  - side-by-side screenshots?
- [ ] Passes performance audit #28082 -> @spmonahan, **team**
  - fast folllow after the initial release
- [ ] Is documented #28083
  - concepts doc
  - component doc
  - every component has a public facing readme.md. Move FUIR9 - FUIWC3 differences to a spec.md?
  - per-story description
  - review attributes table / playground
  - best effort, fast follow after the initial release

### Preview components
_(copy & paste the list to the individual issues)_

- [ ] Accordion
- [ ] Avatar
- [ ] Badge
- [ ] Button
- [ ] Divider
- [ ] Image
- [ ] Label
- [ ] Menu
- [ ] MenuList
- [ ] ProgressBar
- [ ] Radio
- [ ] Slider
- [ ] Spinner
- [ ] Switch
- [ ] Tabs
- [ ] Text
- [ ] TextInput
- [ ] Checkbox

## What is Final
Final is recommended for use in production, has a stable API, and low risk of bugs.

- Core architecture principles are validated: 40 essential components implemented (all problem areas covered - single/collection, out of order rendering, floating content...)
- Has no more breaking changes in major version
- Is verified by at least 2 partners in production
  - API works for the partners (no risk of breaking API changes after final release)
  - Commitment from 1-2 partners that they will use the components in production
- Has 90% API coverage in tests
- Is documented on public the Fluent documentation site

## Additional action items

- [ ] #28077
- [ ] FUIWC3 engineers understand Fast Foundation by contributing
