### ISSUE TITLE
[Feature]: migrate v8,v0 from EOL size-auditor to monosize

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#27933]
### Library

v8 (@fluentui/react) and v0 (@fluentui/fluentui-northstar )

### Describe the feature that you would like added

v8,v0 is using lightrail service + size-auditor bot (github app) which is "unmaintained" and it will reach end of life by 31st Jan 2024 ( unless we will inherit and maintain it - we dont wanna do that) .

 We have implemented `bundle-size` (now `monosize`) tool (used for v9)  which has several advantages in comparison with `size-auditor` + lightrail:

- can be run locally
- does not need to query the github api
- outputs the bundled code in prettified mode for analysis
- can create multiple fixtures for one component to test different import scenarios, size auditor only runs once on the whole package

We need  migrate all v8 and v0 from `bundle-size-auditor` to `monosize`

### Have you discussed this feature with our team

@microsoft/fluentui-react-build 

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Tasks
- [x] migrate to latest monosize / https://github.com/microsoft/fluentui/pull/30381
- [x] migrate v8 https://github.com/microsoft/fluentui/pull/30382
- [x] migrate v0 https://github.com/microsoft/fluentui/pull/30383
- [x] delete bundle-size-auditor package and pipeline https://github.com/microsoft/fluentui/pull/30405
- [x] remove SizeAuditor github app and lightrail service from pipelines https://github.com/microsoft/fluentui/pull/30425
- [x] rename ADO pipeline from SizeAuditor to `Fluent UI React - Bundle-Size`
- [x] remove `Fluent UI React - Bundle-Size` from branch restriction check (master, 7.0)
- [x] add nx generator for bundle-size setup per project / https://github.com/microsoft/fluentui/pull/30428
- [x] remove SizeAuditor pipelines from 7.0 branch / https://github.com/microsoft/fluentui/pull/30427

**Comment by Hotell** [comment]
Epic implemented !
