### ISSUE TITLE
[Bug]: labels in stories are not SSR safe

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#27957]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

N/A

### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

None

### Reproduction

N/A

## Actual Behavior
SSR tests are failing

## Expected Behavior
SSR tests are passing

## Repro
- Open `scripts/test-ssr/src/commands/main.ts`
- Uncomment following
  ```diff
  const EXCLUDED_STORIES = [
  -  // TODO: re-enable ISSUE LINK
  - '**/react-datepicker-compat/**',
    // TODO: re-enable ISSUE LINK
    '**/react-toast/**',
    // Portals currently do not support hydration
    // https://github.com/facebook/react/issues/13097
    '**/react-portal/**',
    // https://github.com/microsoft/fluentui/issues/27338
    '**/react-table/stories/DataGrid/Virtualization.stories.tsx',
    '**/react-table/stories/Table/Virtualization.stories.tsx',
  ];
  ```
- Run tests `yarn workspace @fluentui/react-datepicker-compat test-ssr`
- Notice that tests are failing
- The problem is with a `Date` used in a story:
  https://github.com/microsoft/fluentui/blob/ab53a4c86a49a4d4268f3d87809bee263f818c5d/packages/react-components/react-datepicker-compat/stories/DatePicker/DatePickerErrorHandling.stories.tsx#L23-L26
  

### Logs

```shell
N/A
```

### Requested priority

High

### Products/sites affected

N/A

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

### Logs

```shell
N/A
```

### Requested priority

High

### Products/sites affected

Fluent UI repo itself

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.
