### ISSUE TITLE
Coachmark Component

### ISSUE THREAD

**Issue by paulgildea** [microsoft/fluentui#28389]
💡 When you create a PR for any of the checklist items, add a link to this Epic under the PR's **Related Issues** section.

## Preparation

- [ ] [Open UI Research](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#open-ui-research)
  - [link to https://open-ui.org/]
- [ ] [Open GitHub issues related to component](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#find-open-issues-on-github)
  - [link to each issue]
- [ ] [Create react-\* package and component from template](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#component-package)
  - [link to package: https://github.com/microsoft/fluentui/tree/master/packages/react-components/react-(your-component)]
- [ ] (Optional) [Draft implementation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#draft-implementation)
  - [link to draft implementation, if applicable]
- [ ] [Component Spec authored](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#component-spec) and [reviewed](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#spec-review)

## Implementation

- [ ] [Component implementation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#implementation)
- [ ] Initial conformance and unit tests (validate basic functionality)
- [ ] [Initial documentation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#documentation)
  - [ ] [Storybook stories](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#storybook-stories)
  - [ ] README.md covering basic usage
  - [ ] MIGRATION.md guide (include v8 and v0)
- [ ] [Component released as unstable](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#unstable-release) from `@fluentui/react-components/unstable`

## Validation

- [ ] [Add tests](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#tests)
  - [ ] Unit and conformance tests
  - [ ] VR tests
  - [ ] Bundle size fixtures
  - [ ] Performance test scenario
  - [ ] Accessibility behavior tests
  - [ ] Create an issue and run [manual accessibility tests](https://github.com/microsoft/fluentui/wiki/Manual-Accessibility-Review-Checklist): [link to issue]
- [ ] [Validate with partners](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#validation)
- [ ] [Run a bug bash with other FUI crews](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#bug-bash)
- [ ] [Finalize documentation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#finalize-documentation)
  - [ ] Review and add any missing storybook stories
  - [ ] Finalize migration guide
- [ ] [Component released as stable](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#stable-release) from `@fluentui/react-components`
  - [ ] Ensure exports are removed from from `@fluentui/react-components/unstable`
  - [ ] In package.json: Remove the alpha/beta tag from the version number in package.json
  - [ ] In package.json: Change beachball's `disallowedChangeTypes` to `"major", "prerelease"`

**Comment by brandonthomas** [comment]
Pushing the date out here as we're still waiting on design concepts. Coachmark and TeachingBubble weren't being designed in parallel as once thought but in sequence.

**Comment by briandrouin** [comment]
Design: Karina

ADO task

**Comment by gouttierre** [comment]
📢 "The spec shouldn't be much work and will play off the Teachingbubble's work. Karina will see if the focus should be on completing the FRE design spec before starting this spec. Karina will focus on removing the watermark waterdrop animation altogether."

**Comment by gouttierre** [comment]
📢"The spec shouldn’t be much work and will play off the Teachingbubble’s work. `Karina` will start the design spec in the week of Ignite as she wraps up `TeachingBubble's` reaming work."

**Comment by gouttierre** [comment]
📢"Karina will be starting the design spec this week. A lot of the work is built on TeachingBubble implementations"

**Comment by gouttierre** [comment]
📢 " Karina conducted an investigation. The Teams team has been referring to the teaching popover as a coachmark, and so the design team will ensure that we are clear on the need and purpose. After the investigation, Karina believes that we may not need to create the traditional coachmark. Design asked Geoff Cox for telemetry on how many people are currently using the coachmark in V8 to verify the hypothesis before resuming work on the spec."

**Comment by gouttierre** [comment]
📢 
- The work has been paused with Coachmark until the end of this quarter. 
The designers have assessed the need for the coachmark and they don’t need this component in the eco system right now as the TeachingPopover is so adaptable.
- If partners need the component, then a meeting with design will be held to review their use cases. cc @JustSlone , @behowell , @miroslavstastny, @tudorpopams

**Comment by gouttierre** [comment]
📢 

- The design team has reviewed the Coachmark component and determined that it's currently unnecessary within the fluent ecosystem, thanks to the flexibility of the TeachingPopover.
- As a result, the fluent teams should archive the design and code for the Coachmark until there's a need for it in the future.
- The engineering team is advised to go through the code, ensuring proper documentation is in place or marking the component as deprecated with a recommendation to use the TeachingPopover or submit a request for additional functionality. 
- @tudorpopams to determine engineering's next steps.
- PM is closing this Epic for now.
