### ISSUE TITLE
SwatchPicker

### ISSUE THREAD

**Issue by ValentinaKozlova** [microsoft/fluentui#28606]
💡 When you create a PR for any of the checklist items, add a link to this Epic under the PR's **Related Issues** section.

## Preparation

- [X] [Open UI Research](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#open-ui-research)
  - OpenUI does not have research on a SwatchPicker.
  - #28376
- [X] [Open GitHub issues related to component](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#find-open-issues-on-github)
  - #22687
  - #26907
  - #27819 
- [X] [Create react-\* package and component from template](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#component-package)
  - #29496
  - https://github.com/microsoft/fluentui/tree/master/packages/react-components/react-swatch-picker-preview
- [X] (Optional) [Draft implementation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#draft-implementation)
  - #28700
  - #30190
  - #30631(for a11y review)
- [X] [Component Spec authored](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#component-spec) and [reviewed](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#spec-review)
  - #29436
  - #30880
## Implementation

- [X] [Component implementation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#implementation)
    - #30544
    - #30650
    - #30600
    - #30769
    - #30781
    - #30843
    - #30868
    - #30953
    - #31014
- [X] Initial conformance and unit tests (validate basic functionality)
     - #30861 
- [X] [Initial documentation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#documentation)
  - [X] [Storybook stories](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#storybook-stories)
  - [X] README.md covering basic usage - #30877
  - [X] MIGRATION.md guide (include v8 and v0) - #30878
- [X] [Component released as unstable](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#unstable-release) from `@fluentui/react-components/unstable` - #30881

## Validation

- [X] [Add tests](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#tests)
  - [X] Unit and conformance tests - #31083
  - [X] VR tests
     - #30887
     - #31029
  - [X] Bundle size fixtures
  - [X] Performance test scenario - #31081
  - [X] Accessibility behavior tests
     - #31060
  - [X] Create an issue and run [manual accessibility tests](https://github.com/microsoft/fluentui/wiki/Manual-Accessibility-Review-Checklist): #31078
- [X] [Validate with partners](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#validation)
- [X] [Run a bug bash with other FUI crews](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#bug-bash)
- [X] [Finalize documentation](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#finalize-documentation)
  - [X] Review and add any missing storybook stories - #31280
  - [X] Finalize migration guide
- [X] [Component released as stable](https://github.com/microsoft/fluentui/wiki/Component-Implementation-Guide#stable-release) from `@fluentui/react-components`
  - #31389 
  - [X] Ensure exports are removed from from `@fluentui/react-components/unstable`
  - [X] In package.json: Remove the alpha/beta tag from the version number in package.json
  - [X] In package.json: Change beachball's `disallowedChangeTypes` to `"major", "prerelease"`

**Comment by briandrouin** [comment]
Design contact: Toshie

ADO task

**Comment by gouttierre** [comment]
📢"Toshie is happy with the progress and has given Valentyna some feedback. The next step would be to schedule the design spec with the trusted testing team. Brian has contacts to start the review process with the TTT. Gouttierre and Brian will discuss. 
This component will be renamed to `SwatchPicker`."

**Comment by gouttierre** [comment]
📢"The next step would be to schedule the` design spec` with the `trusted testing team`. `Gouttierre` and `Brian` will discuss."

**Comment by gouttierre** [comment]
📢 
- Valentyna had followed up questions with engineering regards to the preferred navigation and is updating the spec. Valentyna will resume when she returns from vacation next week on Monday; followed by a trusted testing meeting spec review session.

**Comment by gouttierre** [comment]
📢 
- Valentyna and Toshie completed the spec review with the trusted testers. 
- Valentyna began working on the component implementation. The updated the eta is set for the start of April based on devs estimates of completion. 
cc @tudorpopams, @JustSlone

**Comment by gouttierre** [comment]
📢 
- Valentyna has released first part of SwatchPicker that is ready for review:
[feat(swatch-picker): Added ColorSwatch sub component and selection logic by ValentinaKozlova · Pull Request #30544 · microsoft/fluentui (github.com)](https://github.com/microsoft/fluentui/pull/30544)
- It contains new ColorSwatch component and selection logic. Styles and states will be added later

**Comment by gouttierre** [comment]
📢 
- The first part of the implementation will be merged by Valentyna today.

**Comment by gouttierre** [comment]
📢
- Valentyna had a call with Lydia, we discussed writing user guidance. This will be next plan after main implementation
- This week Valentyna will have a call with Toshie about working on UI kit
- Valentyna shared current design and implementation with Office folks

**Comment by gouttierre** [comment]
📢 
- SwatchPicker preview is merged. Tomorrow the developer can test it and then update the status. (Valentyna)

**Comment by gouttierre** [comment]
📢 
- Discussed with Tudor. For now; the end date has been shifted to end of May from April. 
- Valentyna will confirm the ETA once returned from PTO in the [1st or 2nd] week of May.
- WXP will start experiments in their upcoming sprint to validate the component.

cc @tudorpopams , @ValentinaKozlova, @JustSlone
