### ISSUE TITLE
[Chore]: migrate all v9 packages to new slot API

### ISSUE THREAD

**Issue by bsunderhus** [microsoft/fluentui#28740]
Migrates all v9 packages to the new slot API, using the `slot` methods and `assertSlots`.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/fluentui/pull/28751
- [ ] https://github.com/microsoft/fluentui/pull/28752
- [ ] https://github.com/microsoft/fluentui/pull/28753
- [ ] https://github.com/microsoft/fluentui/pull/28754
- [ ] https://github.com/microsoft/fluentui/pull/28773
- [ ] https://github.com/microsoft/fluentui/issues/28778
- [ ] https://github.com/microsoft/fluentui/pull/28775
- [ ] https://github.com/microsoft/fluentui/pull/28774
```

**Comment by sopranopillow** [comment]
@bsunderhus, looks like this is done, is it safe to close?
