### ISSUE TITLE
[@fluentui/react-calendar-compat]: Extract Calendar from DatePicker compat into its own package 

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#29438]
Issue to track work for Calendar Compat

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/fluentui/issues/29439
- [x] Scaffold Calendar Component
- [ ] https://github.com/microsoft/fluentui/issues/29464
- [ ] https://github.com/microsoft/fluentui/issues/29487
- [ ] https://github.com/microsoft/fluentui/issues/29538
- [x] Update tests if needed
- [x] Update styles if needed
- [ ] https://github.com/microsoft/fluentui/issues/29541
- [ ] https://github.com/microsoft/fluentui/issues/29540
- [ ] https://github.com/microsoft/fluentui/issues/29586
```

`react-calendar-compat` has been released and can be found in [npmjs](https://www.npmjs.com/package/@fluentui/react-calendar-compat)

Fixes #29374
