### ISSUE TITLE
Error messaging for chart/component rendering failures

### ISSUE THREAD

**Issue by AtishayMsft** [microsoft/fluentui#29574]
We need visuals and messages to display failures while rendering the charts.
```[tasklist]
### Tasks
- [ ] Create a common control that can show error and empty states.
- [ ] Use the common control to show already implemented empty messages.
- [ ] Use the common control to show type errors (eg: when string data is used on x axis for Line chart or area chart which is not supported)
```
