### ISSUE TITLE
[Epic]: Support interoperability between web components and `@fluentui/react-components`

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#30239]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

We want to ensure that Fluent UI React v9 and web components can interop well together. This means that things like theming, styling, keyboard and eventing should all "just work". This work includes discovering where functionality gaps exist, adding features, fixing bugs and documenting how to configure Fluent for interop.

## Keyboarding

- [x] [Implement shadow DOM support in Tabster](https://github.com/microsoft/tabster/issues/340)

## Styling

- [x] [Expose "insertion point" API in `@griffel/react-shdow`](https://github.com/microsoft/griffel/pull/480)
- [x] [Add support for "insertion point" to react-shadow](https://github.com/microsoft/fluentui-contrib/issues/59)

## Theming

- [x] #30241 

## Documentation

- [x] #30242

### Priority

High
