### ISSUE TITLE
[Epic]: v9 Card component updates 

### ISSUE THREAD

**Issue by tudorpopams** [microsoft/fluentui#30269]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

This epic covers all the updates that will be handled for the Card component, as follows:

- [x] https://github.com/microsoft/fluentui/issues/30142
- [x] https://github.com/microsoft/fluentui/issues/28281

### Have you discussed this feature with our team

@cxe-prg

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

None

**Comment by marcosmoura** [comment]
Closing this as all the tasks were finished. We can reopen in case any related issues get created.
