### ISSUE TITLE
[Epic]: v9 Dialog and Drawer visual updates

### ISSUE THREAD

**Issue by tudorpopams** [microsoft/fluentui#30268]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

This epic covers all the visual updates that should be handled for the Dialog and Drawer components, as follows:

- [x] https://github.com/microsoft/fluentui/issues/28359
- [x] https://github.com/microsoft/fluentui/pull/29137
- [x] https://github.com/microsoft/fluentui/issues/29408

### Have you discussed this feature with our team

@cxe-prg

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

None
