### ISSUE TITLE
[Feature]: replace lerna with nx / make v0 release work

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#30265]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### Describe the feature that you would like added

As we are moving towards nx (that is used under the hood by lerna) and nx starting v17 provides release management (in beta) that we intend to use for all monorepo projects in future, it makes sense to remove unnecessary abstraction and unify our toolchain.

With that said, `react-northstar` release pipeline hasn't been working for quite some time and needs to be fixed which goes hand in hand with this initiative.

### Have you discussed this feature with our team

v-build

### Tasks

- [x] cleanup northstar release task and monorepo global scripts
- [x] remove northstar nightly/canary releases
- [x] replace lerna with nx release  | https://github.com/microsoft/fluentui/pull/30251
- [x] update Northstar release docs
- [x] enable Northstar release pipeline

### Related

- https://github.com/microsoft/fluentui/issues/30220

**Comment by Hotell** [comment]
northstar pipelines:
- work
- are compliant
- leverage `nx release` including `dryRun` capabilities

🎉
