### ISSUE TITLE
[Feature]: add internal workspace eslint-rules

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#30332]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

ATM any custom eslint rule goes to public @fluentui/eslint-plugin.

This has various issues:

- exposing publicly eslint rules that might be only for internal stuff
- adding technical depth to already very complex configuration within the existing plugin
- authoring rules in vanilla js / no type guarantees within tests
 
All of these can be mitigated with **monorepo internal set of lint rules.**

_Implementation of internal rules:_

new project  bootstrapped -> `tools/eslint-rules`, under the hood this uses nx workspace lint rule resolution.

_Registration of internal rules:_

As a contrived example let say we implement custom lint rule named `uppercase-const`

This is how on ca use it in particular project:

```json
{
 "rules": {
     "@nx/workspace-uppercase-const": "error"
  }
}
```

### Additional Context

In order to make this work we need `@nx/eslint-plugin` registered within our monorepo eslint root config which will load these custom rules under the hood. 

To make that work we need overhaul of eslint configs within our projects to extend from monorepo root eslint config

**Tasks:**
- [ ] bootstrap workspace eslint rules
- [ ] provide workspace eslint rule generator
- [ ] implement temporary solution to make workspace lint rules be loaded with existing eslint setup
- [ ] overhaul lint configuration ( for "new" packages - react-components family for now )

### Have you discussed this feature with our team

v-build

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

None

**Comment by Hotell** [comment]
"keep open"
