### ISSUE TITLE
[Feature]: migrate to latest eslint/@typescript-eslint

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#30334]
### Library

whole monorepo

### Describe the feature that you would like added

ATM we are at eslint v7 and typescript-eslint v5 while latest are: eslint v9 and typescript-eslint v8.

This has various issues:

- security implications
- slower performance
- outdated AST parsers and APIs used within our codebase

This feature request will track migration to latest versions.

### Have you discussed this feature with our team

v-build

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

None

### Tasks

- [x] migrate to ts-eslint v5 / https://github.com/microsoft/fluentui/pull/31517
- [x] migrate to ts-eslint v6 and eslint v8 / https://github.com/microsoft/fluentui/pull/31988
- [x] migrate to ts-eslint v7 / https://github.com/microsoft/fluentui/pull/32272
- [x] migrate to ts-eslint v8 / https://github.com/microsoft/fluentui/pull/32369
- [x] eslint v9 ( EOF for eslint v8 is 2024-10-05 / need to wait on nx support ) / https://github.com/nrwl/nx/issues/27451
