### ISSUE TITLE
[Feature]: improve type-checking performance

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#30516]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

v9 and some cross project libraries/apps use TS path aliases, which provide excellent DX and blazing fast Application Bundling speeds with tools like swc or esbuild.

We also leverage TS solution config files within our libraries, and use tsc -b for type checking.

This inflicts huge performance penalty on type-checking execution, because TSC needs to traverse and parse all the paths on every run.

By stopping using TS path aliases mapped to source files on CI for type-checking, we can gain significant performance boost.

### Have you discussed this feature with our team

@microsoft/fluentui-react-build

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

High

### Related Issues

- part of https://github.com/microsoft/fluentui/issues/27359

### Tasks

- [x] RFC / https://github.com/microsoft/fluentui/pull/30514
- [x] improve generate-api performance
- [x] improve build task performance
- [x] improve type-check task performance
- [x] migration generator / https://github.com/microsoft/fluentui/pull/31086
- [x] add monosize support https://github.com/microsoft/monosize/issues/62
- [x] update all library related generators/automations https://github.com/microsoft/fluentui/pull/31142
- [x] normalize storybook setup within react-components suite / https://github.com/microsoft/fluentui/pull/31440
- [x] migrate all apps to new setup / https://github.com/microsoft/fluentui/pull/31426
- [x] migrate all libraries to new setup
   - [x] v9 with stories
      - [x] prg https://github.com/microsoft/fluentui/pull/31565
      - [x] teams 
        -  https://github.com/microsoft/fluentui/pull/31586 
        -  https://github.com/microsoft/fluentui/pull/31601
      - [x] red 
         - https://github.com/microsoft/fluentui/pull/31579
         - https://github.com/microsoft/fluentui/pull/31580
         - https://github.com/microsoft/fluentui/pull/31581
   - [x] v9 without stories / https://github.com/microsoft/fluentui/pull/31454
   - [x] all `scripts/*` / https://github.com/microsoft/fluentui/pull/31475

**Comment by Hotell** [comment]
implemented !
