### ISSUE TITLE
Update api and docs for Rating based on bug bash feedback

### ISSUE THREAD

**Issue by tomi-msft** [microsoft/fluentui#30652]
This issue is to track the work for addressing the feedback from the `Rating` bug bash. Based on the feedback, I need to: 
 - [x] Resolve TODOs in code and JSdoc: #30653 
 - [x] Resolve type in `itemLabel` JSdoc:: #30666 
 - [x] Update interface to use `React.ElementType` instead of `React.ReactElement`: #30666 
 - [x] Allow `useId()` pass a generated id: #30666 
 - [x] Similarly to Accordion, Menu & etc. Rating should use an approach with useContextSelector() to reduce re-renders on context updates: [This](https://github.com/microsoft/fluentui/issues/30647#issuecomment-1971787696) comment explains why this is unnecessary
 - [x] It looks that the spec is outdated, please ensure that it's up to date: #30712 

Offshoot of #30647
