### ISSUE TITLE
[Feature]: migrate to Storybook 7

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#30858]
### Library

all

### Describe the feature that you would like added

our repo is long overdue for latest SB migrations

### Tasks

- [x] Convert `vr-tests` to CSF #31941 
- [x] Convert `vr-tests-react-components` to CSF #31939 
- [x] switch default to named import for `import { addons } from @stortbook/addons`
- [x] exclude/rename files with individual stories (without default exports)
- [x] update all workspace addons
- [x] resolve in memory loading for workspace addons
- [x] mdx v2 migration (possibility to opt out)
- [x] swc addon may not work ?
- [x] check/update all manual style overrides for storybook Docs and shell rendering
   -  https://github.com/microsoft/fluentui/pull/32012
- [ ] TBA

### Things to revert as part of migration:

- [ ] https://github.com/microsoft/fluentui/pull/30816/files

### Closes
- https://github.com/microsoft/fluentui/issues/29265
- TBA 

### Have you discussed this feature with our team

v-build

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

None

**Comment by radium-v** [comment]
Storybook 7 should be skipped in favor of Storybook 8, which has a more stable plugin API (including better support for web components).

**Comment by levithomason** [comment]
Agree, any reason not to go as green as possible here @Hotell?

**Comment by Hotell** [comment]
- our vr-testing solution doesn't support storybook 8 so that's a showstopper for now 
- as a general scalable migration practice we migrate 1 major at a time - v8 is planned ofc once we will be unblocked

> Storybook 7 should be skipped in favor of Storybook 8, which has a more stable plugin API (including better support for web components).

can you provide more details on "more stable plugin API" ?
