### ISSUE TITLE
Use `useTimeout()` and `useAnimationFrame()` rather than globals.

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#30968]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

`@fluentui/react-utilities` provides [`useTimeout()`](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-utilities/src/hooks/useTimeout.ts) and [`useAnimationFrame()`](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-utilities/src/hooks/useAnimationFrame.ts) for working with timers and animation frames respectively. In several places in Fluent UI v9 `window.setTimeout` and `window.requestAnimationFrame` are used instead of these hooks.

We should probably update these instances to use the hooks but codeowners are in the best position to decide.

See #30967

## Relevant packages

- [x] react-menu
    - [x] [useMenu](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-menu/src/components/Menu/useMenu.tsx)
    - [x] [useMenuPopover](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-menu/src/components/MenuPopover/useMenuPopover.ts)
- [x] react-popover
    - [x] [usePopover](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-popover/src/components/Popover/usePopover.ts)
- [x] react-table
    - [x] [useTableColumnResizeMouseHandler](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-table/src/hooks/useTableColumnResizeMouseHandler.ts)
- [x] react-toast
    - [x] [useAriaLive](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-toast/src/components/AriaLive/useAriaLive.ts)
- [x] react-virtualizer
    - [x] [useVirtualizer](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-virtualizer/src/components/Virtualizer/useVirtualizer.ts)
    - [x] [useDynamicPagination](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-virtualizer/src/hooks/useDynamicPagination.ts)
    - [x] [useIntersectionObserver](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-virtualizer/src/hooks/useIntersectionObserver.ts)
    - [x] [useStaticPagination](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-virtualizer/src/hooks/useStaticPagination.ts)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by spmonahan** [comment]
Leaving this one untriaged to talk about at Tech Sync.
