### ISSUE TITLE
[Feature]: ship `nx-console` CLI

### ISSUE THREAD

**Issue by Hotell** [microsoft/fluentui#32192]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

We wanna streamline our `yarn start` Deveoper Experience to every Fluent repo using Nx.

initial implementation is here https://github.com/microsoft/fluentui/pull/32108

### Tasks:

- [ ] bootstrap new package
- [ ] encapsulate reusable logic
- [ ] publish package

### Have you discussed this feature with our team

@microsoft/react-fliuent-build

### Validations

- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

### Priority

Normal
