### ISSUE TITLE
[Feature]: Storybook v8 migration

### ISSUE THREAD

**Issue by dmytrokirpa** [microsoft/fluentui#32386]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Migrate to storybook v8, [migration guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-7x-to-800)

- [ ] Bump `storybook-addon-performance` to the compatible with SB8 version
- [ ] Bump `storywright` to the compatible with SB8 version and make sure that visual regression tests are passing.
- [ ] Migrate mdx docs to MDX3
- [ ] Migrate `*.stories.mdx` to `mdx` docs or `*.stories.tsx`
- [ ] Switch `ArgsTable` to `ArgTypes`, ([related PR](https://github.com/microsoft/fluentui/pull/32382/files#diff-661afe41552bed0a3643e167ff32d3e5f9d1a392edf7fde2dc33296a1449967bR174))

### Have you discussed this feature with our team

Martin

### Validations

- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

### Priority

None
