### ISSUE TITLE
☂ Feedback on Form component or approach

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#5582]
### Code mockup/example

__Code Sample__

```

```

__Types__

| Name      | Type     | Default Value | Description |
|-----------|----------|---------------|-------------|
| className | string   |               | Optional class name to be added to the root |

## Todos

- [ ] Consider adding inline list mode to support defining tabular data with a form

## Steps

- [ ] Themable (Component.base/Component.styles)
- [ ] Unit tests
- [ ] Visual tests
- [ ] Documentation and examples
- [ ] Keyboard Accessible
- [ ] High Constrast Support
- [ ] RTL Support
- [ ] Design Review
- [ ] API review
- [ ] Public Preview
- [ ] Ready for Publishing

Contact forms team, Dynamsics and other form heavy teams to come up with a data driven solution that will work for as many products as possible. Checkout https://redux-form.com for inspiration as well.

**Comment by dagoltz** [comment]
We have implemented a form component internally (Microsoft Cloud App Security) using React and are very happy from it.

It covers front end and back end validations, state managment etc.
We will be happy to share the design amd code.

**Comment by micahgodbolt** [comment]
Thanks @dagoltz! I'd be happy to take a look at it. My goal is to discuss form needs with several partners and determine if there is a common approach that will allow a single component to add value to each partner.

**Comment by micahgodbolt** [comment]
#1164 brought up the question of adding validation error messages to many of our form components. In looking at this Forms component I feel we should determine if every input control have built in messaging, or if the <Form> component could be useful as a 1 off for getting an individual input with validation.

```
<Form item={[{type: date, required: true, errorMessage: "This item is required"]} />
```

This way date picker doesn't have to include specific error message functionality.

**Comment by micahgodbolt** [comment]
BUT if we are going to support a child syntax

```
<Form>
<TextInput />
<DatePicker />
</Form>
```
We'll need to make sure that each component can support all of the necessary props (validation, error message etc) otherwise we need to wrap every input of ours in some Form.TextField wraper...which might be good, or not.

**Comment by redoz** [comment]
It would be really nice if all components had a consistent way of lighting up the error state. This is currently quite high on my list of frustrations working with the various input components. The controls that do offer outside control do so only by setting an error message, which I don't want displayed, so now I have hack out by using a "display: none" on the error message. 

Given that a lot of validation will happen outside the scope of the control itself (and outside of React even), it seems more important to be able to manually control the error states, than having a control that can validate itself.

I also think if the components are going to render errors they need means for overriding the default error rendering. But I find the inconsistency in what various input controls support is the worst part, I know it's a lot of work to maintain all of these things, but I'd rather help put in the effort in making the framework consistent and useful than having to replicate it in every application that uses it.

**Comment by micahgodbolt** [comment]
Yup, that's the goal as well. Look up a level to #7636 and you'll see a list of form improvements we want to make. One of them is a unified error and validation approach.

**Comment by micahgodbolt** [comment]
co-worker pointed out this project:

https://github.com/mozilla-services/react-jsonschema-form

This is definitely what I had in mind with json schemas creating forms that return form data. It'd be worthwhile if/when pursuing this to look at this project to either build off of, or take similar approach.

**Comment by redoz** [comment]
@micahgodbolt Didn't we try this with XForms once already?

**Comment by jmfrancois** [comment]
We have used react-jsonschema-form during two years. One of the main issue we had with:
Data model drive the ui, so if you want to add a button in the middle of the form, or just add fieldset or tabs you must first change the payload.

At talend we have evalutate http://schemaform.io/ and port it to React
https://github.com/Talend/ui/tree/master/packages/forms/src/UIForm

After two years on it we are pretty happy with the UISchema part but jsonschema still suck at validation.

If I add to choose today I will go away from jsonschema which is clearly not nice for forms.
Sinple use case complex when using a schema driven approch:

* `oneOf` two fields are required (password or token)
* hide/display fields dependings on business rules (check box ssl -> display certificat field which is required) We use jsonLogic for that but ... its a bit overkill :D
* optional object (fieldset) but if you start to fill it you have some required field in it.

I still don t understand why mozilla is happy with that lib, you never build a UI from a data model.
You want to build a form which send a valid data against a model.

Schema driven forms are powerful and attractive but you are very easly break in simple use case
 for example is very boring, or object with optional field make it hard to handle

**Comment by micahgodbolt** [comment]
I think schema driven forms have a ton of value (especially in our org). I agree that special cases will pop up where a hand crafted form is better. I'd like to imagine a form element could handle either scenario.

**Comment by gokuldhanvanthri** [comment]
Hi, 
What is the status of this issue? Do we have the schema driven forms or anything similar to that which can be used?

**Comment by onlyann** [comment]
May I suggest to look at https://github.com/final-form/react-final-form for inspiration, as the author suggests in the [introduction of redux-form](https://github.com/erikras/redux-form/#%EF%B8%8F-attention-%EF%B8%8F) ?
