### ISSUE TITLE
Refactor: Button

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#6134]
## Component Details

The implementation of the `Button` component currently existing in the `office-ui-fabric-react` package has become more complex and its api more confusing as time has gone by. In an effort to simplify the api we are rewriting `Button` into a new component that's easier to use and easier to maintain.

In tandem with these efforts, we are taking this opportunity to use all of the latest developments in the new `Button` component, including:
- Slots
- Tokens for styling
- Foundation library for separating state and view
- Theming

## Steps

- [x] Make button styleable via styles function or object
- [x] Consider multiline button support
- [x] Make button themable (support themes and schemes)
- [x] Separate `ContextualMenu` from new `Button` (#8291)
- [x] Make `Button` more modular
- [x] Add new `Button` to size auditor (#8898, #8985)
- [x] Make `menu` prop optional (first mentioned in #8754 and done in #8975)
- [x] Make new Button use Fluent styles (#8963)
- [x] Fix styling of vertical buttons (#8963)
- [x] Implement toggle buttons (#9016)
- [x] Add keytips to buttons (#9061)
- [x] Add `Alt+Down` menu behavior in `SplitButton` (#9136)
- [x] Add controlled menu behavior (removed by design)
- [x] Add VR tests (#9159)
- [x] Make `getNativeProps` get the correct set of native props (#9456)
- [x] Write test to guard against regressions on the use of the `focus` method (#9490)
- [x] Rename `BaseButton` to `Actionable` and strip down functionality, then have `Button` extend from `Actionable` (first mentioned in #8963.) (#9436)
- [ ] Remove use of palette colors, using semantic colors instead (#8963)
- [ ] Bundlesize improvements (#8291)
- [ ] Perf improvements (#9250, #9276, #9516, #9984, #9995, #10152)
- [ ] Fix styling and theming of variants via the use of `extendComponent` (waiting on #8331 and mentioned in #8645)
- [ ] Resolve Button variant themeability. (Issue #9093)
- [ ] Deprecate old props used in variants via code mods (`text`, `iconProps`, etc) (mentioned in #8645) (#9354)
- [ ] Render menu "next" to button instead of inline (first mentioned as a comment in #7552)
- [ ] Add themability test for work in #9605

## Upgrade Plan

Part of upgrading usage of the old `Button` component to the new one is having a compelling story of how to transition current users seamlessly. In order to do that we need to establish what are we going to do with all existing exports.

Below is a list of all existing exports under the current `Button` (except the ones tha come from example files) and the actions we're taking for each one:

| Component | Existing export | Action taken | PR |
|:-------------:|:-----------------:|:--------------:|:----:|
| `ActionButton` | `getStyles` | Styling in `ActionButtonTokens` | #8645 |
| `ActionButton` | `ActionButton` | Created `ActionButton` variant | #8645 |
| `BaseButton` | `IButtonClassNames` | Styling in `BaseButtonStyles` and `BaseButtonTokens` | #8679 |
| `BaseButton` | `ButtonGlobalClassNames` | Styling in `BaseButtonStyles` and `BaseButtonTokens` | #8679 |
| `BaseButton` | `getBaseButtonClassNames` | Styling in `BaseButtonStyles` and `BaseButtonTokens` | #8679 |
| `BaseButton` | `getStyles` | Styling in `BaseButtonStyles` and `BaseButtonTokens` | #8679 |
| `BaseButton` | `IBaseButtonProps` | Gotten rid of the props | &#9477; |
| `BaseButton` | `IBaseButtonState` | Gotten rid of the state | &#9477; |
| `BaseButton` | `BaseButton` | Created `BaseButton` variant | #8679  |
| `Button` | `Button` | Replaced by new `Button` | &#9477; |
| `Button` | `IButton` | See `API Review` section below | &#9477; |
| `Button` | `IButtonProps` | See `API Review` section below | &#9477; |
| `Button` | `ElementType` | Functionality emulated by `IButtonProps` | &#9477; |
| `Button` | `ButtonType` | Functionality emulated by variants | &#9477; |
| `Button` | `IButtonStyles` | Styling emulated in `IButtonSlots` and `IButtonTokens` | &#9477; |
| `ButtonThemes` | `standardStyles` | Styling in `Button.styles.ts` | &#9477; |
| `ButtonThemes` | `primaryStyles` | Styling in `Button.styles.ts` | &#9477; |
| `CommandBarButton` | `getStyles` | Styling in `CommandBarButtonTokens` | #8721 |
| `CommandBarButton` | `CommandBarButton` | Created `CommandBarButton` variant | #8721 |
| `CommandButton` | `CommandButton` | Created `CommandButton` variant | #8721 |
| `CompoundButton` | `getStyles` | Styling in `CompoundButtonStyles` and `CompoundButtonTokens` | #8679 |
| `CompoundButton` | `CompoundButton` | Created `CompoundButton` variant | #8679 |
| `DefaultButton` | `getStyles` | Styling in `Button.styles.ts` | &#9477; |
| `DefaultButton` | `DefaultButton` | Created `DefaultButton` variant | #8641 |
| `IconButton` | `getStyles` | Styling in `IconButtonTokens` | #8721 |
| `IconButton` | `IconButton` | Created `IconButton` variant | #8721 |
| `MessageBarButton` | `getStyles` | Styling in `MessageBarButtonTokens` | #8721 |
| `MessageBarButton` | `MessageBarButton` | Created `MessageBarButton` variant | #8721 |
| `PrimaryButton` | `PrimaryButton` | Created `PrimaryButton` variant | #8641 |
| `SplitButton` | `ISplitButtonClassNames` | Created `SplitButton` variant | &#9477; |
| `SplitButton` | `getClassNames` | Styling in `SplitButtonStyles` and `SplitButtonTokens` | &#9477; |
| `SplitButton` | `getStyles` | Styling in `SplitButtonStyles` and `SplitButtonTokens` | &#9477; |

## Fluent style parity between old and new Button

For every example, the `Buttons` above are the old `Buttons` and the `Buttons` below are the new ones.

__Base Buttons:__

![image](https://user-images.githubusercontent.com/7798177/57170423-a6703d00-6dc1-11e9-81a4-7487f690e4ef.png)

__Default and Primary Buttons:__

![image](https://user-images.githubusercontent.com/7798177/57049343-83f8eb00-6c2c-11e9-8a2e-3e76a901313b.png)

__Menu Buttons:__

![image](https://user-images.githubusercontent.com/7798177/57170038-06191900-6dbf-11e9-80c6-fe506597bedf.png)

__Split Buttons__:

Slightly different to fix some visual bugs in these buttons:

![image](https://user-images.githubusercontent.com/7798177/57170043-0e715400-6dbf-11e9-8f84-b0f83efe182f.png)

__Action Buttons:__

![image](https://user-images.githubusercontent.com/7798177/57049769-5b71f080-6c2e-11e9-8463-967db0bbcdd7.png)

__CommandBar Buttons:__

![image](https://user-images.githubusercontent.com/7798177/57169762-90607d80-6dbd-11e9-818a-c9a158cccf92.png)

__Compound Buttons:__

![image](https://user-images.githubusercontent.com/7798177/57169214-580b7000-6dba-11e9-9572-448a58d3dc52.png)

__Icon Buttons:__

Slightly different to fix some visual bugs in these buttons:

![image](https://user-images.githubusercontent.com/7798177/57158280-eae6e300-6d97-11e9-979f-2fa770069226.png)

__MessageBar Buttons:__

![image](https://user-images.githubusercontent.com/7798177/57170988-2fd53e80-6dc5-11e9-92fc-dedae4154f40.png)

## API Review

As part of the migration from the old `Button` approach currently in the `office-ui-fabric-react` package to the new one currently in the `experiments` package, there needs to be a functional parity between the two components. This is so taht we can have a compelling story when promoting the new `Button`.

Below is a mapping between the properties of the old `Button` and the actions we took for each one to transition them to the new `Button` component:

__IButtonProps__

| Old Button prop | Action taken | Property transitioned? | Breaking change? | Codemod created? | 
|-------------------|----------------|:------------------------:|:--------------------:|:---------------------:|
| `href` | Included in the new `Button` component as part of `IButtonProps` | &#9745; | &#x274C; | Not needed |
| `primary` | Included in the new `Button` component as part of `IButtonProps` | &#9745; | &#x274C; | Not needed |
| `disabled` | Included in the new `Button` component as part of `IButtonProps` | &#9745; | &#x274C; | Not needed |
| `ariaLabel` | Included in the new `Button` component as part of `IButtonProps` | &#9745; | &#x274C; | Not needed |
| `checked` | Included in the new `Button` component as part of `IButtonProps` | &#9745; | &#x274C; | Not needed |
| `allowDisabledFocus` | Included in the new `Button` component as part of `IButtonProps` | &#9745; | &#x274C; | Not needed |
| `keytipProps` | Included in the new `Button` component as part of `IButtonProps` | &#9745; | &#x274C; | Not needed |
| `uniqueId` | Included in the new `Button` component as part of `IButtonProps` | &#9745; | &#x274C; | Not needed |
| `componentRef` | Included in the new `Button` component as part of `IBaseProps` | &#9745; | &#x274C; | Not needed |
| `styles` | Included in the new `Button` component as part of `IBaseProps` | &#9745; | &#x274C; | Not needed |
| `theme` | Included in the new `Button` component as part of `IBaseProps` | &#9745; | &#x274C; | Not needed |
| `className` | Included in the new `Button` component as part of `IBaseProps` | &#9745; | &#x274C; | Not needed |
| `text` | Included in the new `Button` component as `content` slot in `IButtonSlots` | &#9745; | &#9745; | &#9745; |
| `iconProps` | Included in the new `Button` component as `icon` slot in `IButtonSlots` | &#9745; | &#9745; | &#9745; |
| `menuProps` | Included in the new `Button` component as `menu` slot in `IButtonSlots` | &#9745; | &#9745; | &#9745; |
| `menuIconProps` | Included in the new `Button` component as `menuIcon` slot in `IButtonSlots` | &#9745; | &#9745; | &#x274C; |
| `onAfterMenuDismiss` | Included in the new `Button` component as `onMenuDismiss` in `IButtonViewProps` | &#9745; | &#9745; | &#x274C; |
| `onRenderChildren` | Functionality provided by slot approach via `root` or `stack` slots | &#9745; | &#9745; | &#x274C; |
| `onRenderIcon` | Functionality provided by slot approach via `icon` slot | &#9745; | &#9745; | &#x274C; |
| `onRenderText` | Functionality provided by slot approach via `content` slot | &#9745; | &#9745; | &#x274C; |
| `onRenderMenuIcon` | Functionality provided by slot approach via `menuIcon` slot | &#9745; | &#9745; | &#x274C; |
| `menuAs` | Functionality provided by slot approach via `menu` slot | &#9745; | &#9745; | &#x274C; |
| `onMenuClick` | Included in `MenuButton` variant as `onClick` in `IMenuButtonProps` | &#9745; | &#9745; | &#x274C; |
| `split` | Included as new `Button` variant `SplitButton` | &#9745; | &#9745; | &#9745; |
| `primaryDisabled` | Included in `SplitButton` variant as `primaryActionDisabled` in `ISplitMenuButtonProps` | &#9745; | &#9745; | &#x274C; |
| `splitButtonAriaLabel` | Included in`SplitButton` variant as `secondaryAriaLabel` in `ISplitMenuButtonProps` | &#9745; | &#9745; | &#x274C; |
| `buttonType` | Removing as already deprecated | &#9745; | &#9745; | &#x274C; |
| `rootProps` | Removing as already deprecated | &#9745; | &#9745; | &#x274C; |
| `onRenderMenu` | Removing as already deprecated in favor of `menuAs` | &#9745; | &#9745; | &#x274C; |
| `toggled` | Removing as already deprecated in favor of `checked` | &#9745; | &#9745; | &#x274C; |
| `description` | Removing as already deprecated in favor of `secondaryText` | &#9745; | &#9745; | &#x274C; |
| `ariaHidden` | Removing in favor of native prop | &#9745; | &#9745; | &#x274C; |
| `getClassNames` | Removing given new styling and theming approach | &#9745; | &#9745; | &#x274C; |
| `getSplitButtonClassNames` | Removing given new styling and theming approach | &#9745; | &#9745; | &#x274C; |
| `secondaryText` | Removing given that this multiline functionality is provided with new slot approach | &#9745; | &#9745; | &#x274C; |
| `toggle` | Removing in favor of a stateless approach towards toggle buttons. | &#9745; | &#9745; | &#x274C; |
| `onRenderDescription` | Removing given that `secondaryText` is being deprecated | &#9745; | &#9745; | &#x274C; |
| `onRenderAriaDescription` | Removing given that `secondaryText` is being deprecated | &#9745; | &#9745; | &#x274C; |
| `ariaDescription` | Removing given that `secondaryText` is being deprecated | &#9745; | &#9745; | &#x274C; |
| `persistMenu` | Removing controlled menu behavior in new `Button` | &#9745; | &#9745; |&#x274C; |
| `data` | Removing in new `Button` | &#9745; | &#9745; |&#x274C; |
| `menuTriggerKeyCode` | TBD | &#x274C; | &#x274C; | &#x274C; |

__IButton__

| Old Button prop | Action to take | Property transitioned | Breaking change? | Codemod created? | 
|--------------------|----------------|:------------------------:|:--------------------:|:---------------------:|
| `focus` | Included in the new `Button` component as part of `IButton` | &#9745; | &#x274C; | Not needed |
| `dismissMenu` | Removing controlled menu behavior in new `Button` | &#9745; | &#9745; | &#x274C; |
| `openMenu` | Removing controlled menu behavior in new `Button` | &#9745; | &#9745; | &#x274C; |

### Imports

TBD

### Exports/ Component Breakdown

TBD

### Intended Package

Initially in `@uifabric/experiments` while we drive the changes to have the correct api, but with the intention of moving it to `office-ui-fabric-react` after that is done.

### Code mockup/example

TBD

#### Button

__IButtonSlots__

| Name  | Type | Description |
|---------|:-----:|--------------|
| `root` | `IHTMLElementSlot<Button>` | Defines the root slot of the component. |
| `stack` | `IStackSlot` | Defines the horizontal stack used for specifying the inner layout of the `Button`. |
| `content` | `ITextSlot` | Defines the text that is displayed inside the `Button`. |
| `icon` | `IIconSlot` | Defines the icon that is displayed next to the text inside the `Button`. |

__IButtonProps__

| Name      | Type     | Default Value | Description |
|-----------|:---------:|:--------------:|-------------|
| `href` | `string` | | Defines an href reference that, if provided, will make this component render as an anchor. |
| `primary` | `boolean` | `false` | Defines whether the visual representation of the `Button` should be emphasized. |
| `circular` | `boolean` | `false` | Defines whether the `Button` should be circular. In general, circular `Buttons` should not specify the menu and container slots. |
| `disabled` | `boolean` | `false` | Defines whether the `Button` is disabled. |
| `onClick` | `(ev: React.MouseEvent<HTMLElement>) => void` | | Defines an event callback that is triggered when the `Button` is clicked. |

__IButtonViewProps__

__IButtonTokens__

| Name  | Type |
|---------|:-----:|
| `backgroundColor` | `strong` |
| `backgroundColorHovered` | `string` |
| `backgroundColorPressed` | `string` |
| `color` | `string` |
| `colorFocused` | `string` |
| `colorHovered` | `string` |
| `colorPressed` | `string` |
| `borderColor` | `string` |
| `borderColorHovered` | `string` |
| `borderColorPressed` | `string` |
| `iconColor` | `string` |
| `iconColorHovered` | `string` |
| `iconColorPressed ` | `string` |
| `outlineColor` | `string` |
| `borderRadius` | `number` \| `string` |
| `borderWidth` | `number` \| `string` |
| `contentPadding` | `number` \| `string` |
| `contentPaddingFocused` | `number` \| `string` |
| `textFamily` | `string` |
| `textSize` | `number` \| `string` |
| `textWeight` | `IFontWeight` |
| `width` | `number` \| `string` |
| `height` | `number` \| `string` |
| `iconSize` | `number` \| `string` |
| `iconWeight` | `number` |
| `lineHeight` | `number` \| `string` |
| `minWidth` | `number` \| `string` |
| `minHeight` | `number` \| `string` |
| `backgroundClip` | `IRawStyleBase['backgroundClip']` |

#### MenuButton

__IMenuButtonSlots__

| Name  | Type | Description |
|---------|:-----:|--------------|
| `root` | `IHTMLElementSlot<div>` | Defines the root slot of the component. |
| `button` | `IButtonSlot` | Defines the button that is going to be rendered. |
| `menu` | `IContextualMenuSlot` | Defines the contextual menu that appears when you click on the `MenuButton`. |
| `menuIcon` | `IIconSlot` | Defines the icon that is displayed next to the text inside the `MenuButton`. |

__IMenuButtonProps__

| Name      | Type     | Default Value | Description |
|-----------|:---------:|:--------------:|-------------|
| `defaultExpanded` | `boolean` | false | Defines the inital expanded state of the `MenuButton`. If you want the `MenuButton` to maintain its own state, use this. Otherwise, refer to `expanded`. |
| `expanded` | `boolean` | `defaultExpanded` | Defines whether the `MenuButton` is in an expanded state. |
| `onKeyDown` | `(ev: React.KeyboardEvent<HTMLElement>) => void` | | Defines an event callback that is triggered when a keypress is made with the focus on a `MenuButton`. |

__IMenuButtonViewProps__

| Name      | Type     | Default Value | Description |
|-----------|:---------:|:--------------:|-------------|
| `onMenuDismiss` | `() => void` | | Defines a callback that runs after the `MenuButton`'s contextual menu has been closed (removed from the DOM). |
| `menuTarget` | `HTMLElement` \| `undefined` | `undefined` | Defines the target that the contextual menu uses to position itself. |

__IMenuButtonTokens__

#### SplitButton

__ISplitButtonSlots__

| Name  | Type | Description |
|---------|:-----:|--------------|
| `root` | `IStackSlot` | Defines the root slot of the component. |
| `menuButton` | `IMenuButtonSlot` | Menu button that is going to be rendered. |
| `splitDivider` | `IHTMLSlot` | Defines the divider that separates the left and right parts of a `SplitButton`. |

__ISplitButtonProps__

| Name      | Type     | Default Value | Description |
|-----------|:---------:|:--------------:|-------------|
| `primaryActionDisabled` | `boolean` | `false` | Defines whether the first action of the `SplitButton` is disabled. |

__ISplitButtonViewProps__

| Name      | Type     | Default Value | Description |
|-----------|:---------:|:--------------:|-------------|
| `onSecondaryActionClick` | `(ev: React.MouseEvent<HTMLElement>) => void` | | Defines whether the first action of the `SplitButton` is disabled. |

__ISplitButtonTokens__

### Bundle Size Improvements
__Old Button (Stat: 564.5KB, Parsed: 175.3KB, Gzipped: 47.35KB):__
![image](https://user-images.githubusercontent.com/7798177/58350076-c8396e80-7e19-11e9-9e1a-e0689fcae6ec.png)

__New Button (Stat: 325.08KB, Parsed: 88.83KB, Gzipped: 26.6KB):__
![image](https://user-images.githubusercontent.com/7798177/58350118-e1421f80-7e19-11e9-85a1-60c0463d6be3.png)

### Perf Comparison
The scenarios render the components 5000 times. Each scenario is run 10 times to get an average number and account for variants.

__DefaultButton:__

| Scenario | Run 1 | Run 2 | Run 3 | Run 4 | Run 5 | Run 6 | Run 7 | Run 8 | Run 9 | Run 10 | __Average__ |
|----------|:-------:|:-------:|:-------:|:------:|:-------:|:-------:|:------:|:-------:|:-------:|:-------:|:--------------:|
| Old Button | 498 | 545 | 521 | 536 | 548 | 544 | 509 | 539 | 536 | 553 | __538.9__ |
| Before Stack removal | 1451 | 1515 | 1473 | 1454 | 1498 | 1439 | 1531 | 1498 | 1604 | 1508 | __1497.1__ |
| After Stack removal | 1152 | 1039 | 1100 | 1132 | 1143 | 1169 | 1099 | 1165 | 1156 | 1184 | __1133.9__ | 

_210.41% worse than old Button._
_24.26% better after Stack removal._

__PrimaryButton:__

| Scenario | Run 1 | Run 2 | Run 3 | Run 4 | Run 5 | Run 6 | Run 7 | Run 8 | Run 9 | Run 10 | __Average__ |
|----------|:-------:|:-------:|:-------:|:------:|:-------:|:-------:|:------:|:-------:|:-------:|:-------:|:--------------:|
| Old Button | 574 | 565 | 581 | 627 | 604 | 564 | 594 | 610 | 612 | 614 | __594.5__ |
| Before Stack removal | 1459 | 1541 | 1427 | 1550 | 1521 | 1492 | 1492 | 1546 | 1630 | 1534 | __1519.2__ |
| After Stack removal | 1093 | 1162 | 1139 | 1207 | 1182 | 1201 | 1167 | 1166 | 1154 | 1200 | __1167.1__ | 

_196.32% worse than old Button._
_23.18% better after Stack removal._

__MenuButton:__

| Scenario | Run 1 | Run 2 | Run 3 | Run 4 | Run 5 | Run 6 | Run 7 | Run 8 | Run 9 | Run 10 | __Average__ |
|----------|:-------:|:-------:|:-------:|:------:|:-------:|:-------:|:------:|:-------:|:-------:|:-------:|:--------------:|
| Old Button | 924 | 952 | 920 | 899 | 883 | 910 | 959 | 905 | 879 | 924 | __915.5__ |
| Before Stack removal | 2392 | 2413 | 2514 | 2494 | 2434 | 2448 | 2406 | 2455 | 2537 | 2421 | __2451.4__ |
| After Stack removal | 2150 | 2127 | 2137 | 2128 | 2118 | 2146 | 2197 | 2203 | 2206 | 2161 | __2157.3__ | 

_235.64% worse than old Button._
_12.00% better after Stack removal._

__SplitButton:__

| Scenario | Run 1 | Run 2 | Run 3 | Run 4 | Run 5 | Run 6 | Run 7 | Run 8 | Run 9 | Run 10 | __Average__ |
|----------|:-------:|:-------:|:-------:|:------:|:-------:|:-------:|:------:|:-------:|:-------:|:-------:|:--------------:|
| Old Button | 1645 | 1722 | 1697 | 1698 | 1702 | 1651 | 1668 | 1774 | 1616 | 1646 | __1681.9__ |
| Before Stack removal | 5088 | 5024 | 4988 | 5015 | 5102 | 5026 | 5031 | 5117 | 5110 | 5098 | __5059.9__ |
| After Stack removal | 3810 | 3847 | 3910 | 3771 | 3810 | 3656 | 3709 | 3724 | 3847 | 3803 | __3788.7__ | 

_225.26% worse than old Button._
_25.12% better after Stack removal._

### Component Ownership

- @khmakoto who is contributing to the rewrite and doing the api review against the old Button component already in `office-ui-fabric-react`.

### Deadlines

After 7.0 release.

## Promotion Checklist

- [x] Themable (Component.base/Component.styles)
- [x] Unit tests
- [x] Visual tests (#9159)
- [x] Documentation and examples
- [x] Keyboard Accessible
- [x] High Constrast Support (#8624)
- [ ] Accessibility Insights for Web Fast Pass
- [x] RTL Support
- [x] Design Review (#8963)
- [x] API review
- [ ] Public Preview
- [ ] Ready for Publishing

**Comment by micahgodbolt** [comment]
Closing down #3308 and moving the new button experiment to here.

**Comment by JustSlone** [comment]
This is covered via button convergence, not needed anymore

Check out the new button here: https://github.com/microsoft/fluentui/tree/master/packages/react-button
