### ISSUE TITLE
List Components: Performance issues and improvement areas

### ISSUE THREAD

**Issue by KevinTCoughlin** [microsoft/fluentui#8826]
Catch-all issue tracking performance issues / areas of optimization across List components:

This is needed because often while investigating one issue, numerous others become known. The below issues are not necessarily in priority order in terms of cost-savings. Will follow-up with potential savings.

#### Reflow

- [ ] List's `setState` call in render path causes initial async hop, see https://github.com/OfficeDev/office-ui-fabric-react/blob/963bedb18604d38792d7ac57d280877f52a597ae/packages/office-ui-fabric-react/src/components/List/List.tsx#L574
- [ ] List's `'scroll'` event handlers cause reflow and take too long; use `IntersectionObserver` instead, see https://github.com/OfficeDev/office-ui-fabric-react/issues/5557
- [ ] Window as scrollable container causes `List` to never utilize page height cache, see https://github.com/OfficeDev/office-ui-fabric-react/issues/8740

#### React reconciliation:

- [ ] When `shouldVirtualize`'s return value is flipped, the items after the first page flash. @ThomasMichon debugged this a bit and believes the solution is to not group all items in an individual page when `shouldVirtualize() => false`, but share the page creation logic for the inverse case.
- [ ] Materialized List pages re-render on scroll stop due to `this.setState` in https://github.com/OfficeDev/office-ui-fabric-react/blob/963bedb18604d38792d7ac57d280877f52a597ae/packages/office-ui-fabric-react/src/components/List/List.tsx#L555

#### CSS-in-JS

- [x] https://github.com/OfficeDev/office-ui-fabric-react/pull/8803 Wasteful usage of className concatenation

---

#### React reconciliation:

- [ ] DetailsHeader re-renders on selection change, see https://github.com/OfficeDev/office-ui-fabric-react/pull/8799
- [ ] DetailsHeader cells re-render on selection change, see https://github.com/OfficeDev/office-ui-fabric-react/issues/8799
-- I briefly investigated this and it is due to `column` prop mutating and causing re-render.
- [x] https://github.com/OfficeDev/office-ui-fabric-react/pull/8799 `DetailsRowFields` re-render on selection change

#### CSS-in-JS:

- [ ] `DetailsRowCheck` / `Check` take significant % of row render time
- [ ] `$isRowHeader`, specifically in high-contrast mode styles are producing invalid output / are unnecessary, see https://github.com/OfficeDev/office-ui-fabric-react/pull/8799#discussion_r277826912.

---

### GroupedList

TBD

cc: @aditima @natalieethell @Vitalius1 @margoflynn

**Comment by KevinTCoughlin** [comment]
Also tracking high-contrast issues @Vitalius1 brought to my attention in this issue until we have a better home:

### DetailsList - High Contrast

- Anchor text color when selected turns to black and should probably be `HighlightText`
- Focus outline in both high-contrast and non are clipped with the scrollbar (low priority)

### GroupedList - High Contrast

- Spacer is a different background than the highlighted selected row

**Comment by KevinTCoughlin** [comment]
### Documentation

#### DetailsList

- [ ] Add documentation to and improve visibility into inner props such as `SelectionZone` and `Selection` to help developers working with `DetailsList`, for example: https://github.com/OfficeDev/office-ui-fabric-react/issues/8808#issuecomment-487230767

**Comment by KevinTCoughlin** [comment]
### Customization Asks

**DetailsList**

- [ ] Allow for header cell customization, see https://github.com/OfficeDev/office-ui-fabric-react/pull/8619#issuecomment-486616354

**Comment by xugao** [comment]
also related : #5487
